### ISSUE TITLE
Request to Join as a Maintainer for the Job Board Project

### ISSUE THREAD

**Issue by guranshdeol** [code100x/job-board#1]
Hello @hkirat  Sir,

I hope this message finds you well.

My name is **Guransh Deol**, and I am a **Final Year Computer Science Engineering student**. I am writing to express my interest in joining your job board project as a **maintainer**.

Here is a brief overview of my qualifications and experience:
- I have been the **community lead** of **Open Source Chandigarh**, an open-source community at our university.
- I have served as the **lead student hackathon organizer** at Chitkara University.
- I am **GitHub Foundations certified**, with my certification valid until 2027.
- I hold an **owner role** in our university's enterprise GitHub organization, which has equipped me with the skills to manage repositories in depth.

I am confident that my background and skills make me a strong candidate for the maintainer role. I am passionate about open-source projects and am eager to contribute to your job board project.

You can find more about me and my work through the following links:
- Socials: [https://bio.link/guranshdeol](https://bio.link/guranshdeol)
- Resume: [https://drive.google.com/file/d/1WyCW93odX4_wPVadrkDV_QzkbxeKXcw0/view?usp=sharing](https://drive.google.com/file/d/1WyCW93odX4_wPVadrkDV_QzkbxeKXcw0/view?usp=sharing)

Thank you for considering my request. I look forward to the possibility of contributing to your project.

Best regards,
Guransh Deol

**Comment by AnishDubey0712** [comment]
Yes I'm excited to contribute to this project
