### ISSUE TITLE
📦 [FEATURE]: Add new page for job posting with rich text editor for description 

### ISSUE THREAD

**Issue by ezhil56x** [code100x/job-board#107]
# Current Implementation
A modal is used to create a new job posting in the admin page. Currently we can should fill in text paragraphs as description which is not looking good

# Proposed Implementation
Create a new page for posting job details with rich text editor support so that we can add bullet points, bold text and much more

**Comment by ezhil56x** [comment]
@VineeTagarwaL-code
If this is in the list. Kindly assign I'll get it done asap!

**Comment by VineeTagarwaL-code** [comment]
The issue is not very descriptive as its needs to be, please make sure you attach images and references to help anyone understand better 

thank you !
