### ISSUE TITLE
HomePage + Job Post Page and form based on remotejobs.com + Some Ideas.

### ISSUE THREAD

**Issue by Pheewww** [code100x/job-board#11]
homepage -> 
![image](https://github.com/user-attachments/assets/959b610d-4839-4cc0-aec7-d7ef8c4ae4fc)

Post Job -> 
![image](https://github.com/user-attachments/assets/6808e77e-76c7-45c6-8ebc-e78ee3ae6ecb)

Job Form -> 
![image](https://github.com/user-attachments/assets/e578324e-e0e3-4db9-bae2-e18453bcda98)

Repo Link - https://github.com/Pheewww/Job-portal
db - postgress + prisma

Some More Ideas - 
1) Proposals from top 20 people from cohort github contribution standing project can be shown at top of received applications OR these profiles get a badge to get distinguish

2) For making it B2B, anyone can register, but HR can chose from everyone and Only cohort dev option while filling up job post.

Thanks and regards

**Comment by Ankur02Sarkar** [comment]
Nice Idea! Would love to work on it

**Comment by kushwahramkumar2003** [comment]
I love to contribute on it.

**Comment by Ameerjafar** [comment]
@Pheewww working on it.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Looks great ...wanna contribute

**Comment by Abishek-Newar** [comment]
@Pheewww looks great.. but I think that the Ui can be a little better

**Comment by Pheewww** [comment]
> @Pheewww looks great.. but I think that the Ui can be a little better
> 
> 

Yes. you should also checkout remotejobs, it's based on that as @hkirat mentioned it in video.

**Comment by Abishek-Newar** [comment]
> > @Pheewww looks great.. but I think that the Ui can be a little better
> 
> Yes. you should also checkout remotejobs, it's based on that as @hkirat mentioned it in video.

@Pheewww  looks great then. have you build the entire thing or else I can contribute

**Comment by VineeTagarwaL-code** [comment]
Great work man !

Some improvements which i would love to see here

1. UI improvements, Making it clean and simple ... main idea is to allow user to navigate without any confusion 
2. The form needs more work, need to know if the validation is setup + a lot of other important fields are required here 
3. Landing page need more work with respect to UI and UX
