### ISSUE TITLE
Better loding during job fetch.

### ISSUE THREAD

**Issue by AyushShivhare79** [code100x/job-board#110]
Before it looks something like this

![Screenshot from 2024-08-08 15-16-29](https://github.com/user-attachments/assets/435ea916-5b81-40d9-8589-ce6a61886225)

The better loader has been added in the PR request #109

[Screencast from 2024-08-08 15-02-53.webm](https://github.com/user-attachments/assets/66b02e1b-c5c7-422a-b9af-40d38348906e)

@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
Okay this is a good one, can you add a good loading page after #137 is merged today ? , i will be closing this for now but will surely merge it when you open afterwards
