### ISSUE TITLE
🚀 Feature Request : Admin Job Management and Pagination in Job Board

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/job-board#111]
# Feature Request: Admin Job Management and Pagination in Job Board Application

## Description

We are introducing new features to the Job Board web application to enhance admin functionality. The following features will be added:

- **Edit Existing Jobs**: Admins will have the ability to modify job postings.
- **View Existing Jobs**: Admins will be able to see a list of all current job postings.
- **Delete Jobs**: Admins will have the capability to remove job postings.
- **Pagination**: Implement pagination on the jobs page to improve navigation and user experience.

### Requirements

- Ensure that admins can perform CRUD (Create, Read, Update, Delete) operations on job postings.
- Update the database schema if necessary to accommodate new functionalities.
- Implement necessary API endpoints for these actions.
- Ensure proper authentication and authorization to restrict access to these features.
- Implement pagination to split job listings into multiple pages.
- Use loading state with skeleton components to enhance the user experience during data fetching.

### Acceptance Criteria

- Admins should be able to view, edit, and delete job postings from the admin panel.
- The UI should be user-friendly and consistent with the existing design.
- All changes should be reflected in the database and visible in the application.
- Job listings should be paginated, allowing users to navigate through jobs efficiently.
- Loading state with skeleton components should be implemented to improve user experience.

## Current Situation

Currently, the admin management page only has a "Create New Job" button. There are no features to view, edit, or delete existing jobs. Here's an image showing the current state:

![2024-08-08_15-44](https://github.com/user-attachments/assets/331cd54a-911f-4b33-9e46-57533f006f78)

## Request to Work on the Feature

I would like to work on implementing this feature. Please assign this task to me.

Thank you!

---

**Comment by VineeTagarwaL-code** [comment]
Great Issue and well given description, you have been assigned waiting to hear from in 1 day and deadline for the 1st PR is 4 days 

thanks

**Comment by MetriSomesh** [comment]
@kushwahramkumar2003 Great description, thanks a lot from now on I will be using your reference to open a issue.

**Comment by kushwahramkumar2003** [comment]
### Progress Update on Feature Request: Admin Job Management and Pagination in Job Board Application

Hi there,

I've made significant progress on the feature request. Here's what has been implemented so far:

1. **Display All Jobs in the Manage Section**: 
   - The admin panel now shows a list of all job postings. Admins can easily view the details of each job.

2. **Edit and Delete Job Buttons**:
   - I've added buttons that allow admins to edit or delete existing jobs directly from the manage section. The delete action is accompanied by a confirmation prompt to prevent accidental deletions.

3. **Pagination Feature**:
   - Pagination has been implemented, enabling admins to navigate through job postings more efficiently by splitting them across multiple pages.

4. **Loading Skeleton**:
   - A loading skeleton has been added to enhance the user experience while data is being fetched. This provides a visual cue that the content is loading.

Please find attached a video demonstration of the current implementation.

### Video : 

https://github.com/user-attachments/assets/0407edde-6dad-4e7b-b463-382378e8a599


I believe this is a good starting point, but I'd appreciate your feedback. If all the changes are satisfactory, could I go ahead and open a pull request for this? If any modifications or additional features are needed, please let me know @VineeTagarwaL-code .

**Comment by VineeTagarwaL-code** [comment]
sounds good, how is the progress to it ?

**Comment by kushwahramkumar2003** [comment]
@VineeTagarwaL-code Please check pr [https://github.com/code100x/job-board/pull/179](url)
