### ISSUE TITLE
[IMPROVEMENT] Fix Dark Theme Styling for Some Components

### ISSUE THREAD

**Issue by MetriSomesh** [code100x/job-board#113]
I noticed that the dark theme styling for some of the components in the application could be improved to ensure a more consistent user experience. Currently, there are a few issues that I'd like to address:

1.In login page background is not changing to dark background, which it changes in home page.
2.In login form background, text colours are remaining same as light theme colour.

![login](https://github.com/user-attachments/assets/0e10ac19-2318-4c6d-a4a0-45e1a1cfceaf)

3.On jobs page texts of section who's colours are not changing and also border colour for the sidebar is not changing.

![Screenshot from 2024-08-08 14-42-21](https://github.com/user-attachments/assets/c9826417-4eb5-4b21-88ae-0b5ce0693fd7)

**Comment by VineeTagarwaL-code** [comment]
Great Issue, assigning you first !

**Comment by MetriSomesh** [comment]
@VineeTagarwaL-code sir I just found out that there are some issues related to dark theme in jobs/manage as well, should I link a new PR, like reverting or closing current PR and then open a new one?

**Comment by VineeTagarwaL-code** [comment]
Yep go ahead complete the work and then let me know

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
