### ISSUE TITLE
There is no dialog for confirmation for Logout 

### ISSUE THREAD

**Issue by pruthviraj7714** [code100x/job-board#116]
It directly log out after Clicking on Logout in dropdown menu. There should be the Dialog to confirmation for Logout.
Can You assign this to me.

**Comment by VineeTagarwaL-code** [comment]
Go ahead great !

**Comment by VineeTagarwaL-code** [comment]
Make the dialog box of logout more attractive, wont be merging without good looks

**Comment by Mandipbhattarai** [comment]
@VineeTagarwaL-code can you assign the task to me?

**Comment by Mandipbhattarai** [comment]
@VineeTagarwaL-code is this issue still there? I would like to work on it.

**Comment by VineeTagarwaL-code** [comment]
already a issue is opened for removing the login flow
