### ISSUE TITLE
[IMPROVEMENT] Responsiveness Issues in the Jobs page

### ISSUE THREAD

**Issue by ai-is-awesome** [code100x/job-board#119]
Currently, the website's jobs page has some issues with respect to design and responsiveness.

1. Misaligned Job Card Container:  The job card container is not properly aligned with the rest of the section. It is positioned too close to the left edge, causing a noticeable imbalance in the layout.
2. Lack of Responsiveness: The current layout of the jobs page is not responsive. On smaller screens, the sidebar appears on the left, while the main content is on the right. The layout should be adjusted to improve the mobile experience so that the sidebar renders above the job cards container.

I'm attaching the images of current UI for reference

![image](https://github.com/user-attachments/assets/65968955-9dd7-44bb-9de9-eafe50268053)
![image](https://github.com/user-attachments/assets/a1a9a2c4-0c3a-44ee-9711-effdf44a7847)

Woud be great if I can work on this issue. Thanks!

**Comment by MetriSomesh** [comment]
@ai-is-awesome are you working on this?

**Comment by ai-is-awesome** [comment]
> @ai-is-awesome are you working on this?
> 
> 

Hi yes I've written the code already

**Comment by MetriSomesh** [comment]
> Hi yes I've written the code already

Great I was just asking, because Vineet asked me to check responsiveness for my  PR #113 so I will mention yours there.

**Comment by VineeTagarwaL-code** [comment]
I think @MetriSomesh is already working on this

**Comment by MetriSomesh** [comment]
Yes

**Comment by ai-is-awesome** [comment]
@MetriSomesh thats great, you can implement it then. I might work on something else

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
