### ISSUE TITLE
Add the husky for the project

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/job-board#123]
We do not currently have a husky folder in our project. It is quite useful to perform various tasks before committing if we add the.husky folder to the project. The majority of contributors are beginners, so one use case is that when they attempt to commit, the code is automatically formatted. Additionally, we can add constraits to the commit message in the future.

**Comment by MetriSomesh** [comment]
That will help maintainers a lot.

**Comment by VineeTagarwaL-code** [comment]
Good PR
