### ISSUE TITLE
NavBar alignments are misplaced and diff. color for manage tab

### ISSUE THREAD

**Issue by Dikshantw** [code100x/job-board#124]
Profile and theme toggle should be placed together and Mange Tab have different hover color than the other tabs.

https://github.com/user-attachments/assets/32a2afb3-e356-4621-9f2f-b855c854710d

**Comment by Dikshantw** [comment]
@VineeTagarwaL-code  you can assign this issue to me.

**Comment by Fardeen26** [comment]
Just fix the issue and create a pull request

**Comment by VineeTagarwaL-code** [comment]
@Fardeen26 without assigning wont be accepting any PR, will directly close the issue as well as the PR without proper discussion happening

**Comment by VineeTagarwaL-code** [comment]
Great attention to detail @Dikshantw Fix and open the PR

**Comment by Fardeen26** [comment]
> @Fardeen26 without assigning wont be accepting any PR, will directly close the issue as well as the PR without proper discussion happening

Thank You for clarification!

**Comment by MetriSomesh** [comment]
@VineeTagarwaL-code I am already done that.
