### ISSUE TITLE
🐞 [Bug]/[Bad Code]: Sidebar makes multiple backend requests immediately after changing filter.

### ISSUE THREAD

**Issue by prateekkumaroriginal** [code100x/job-board#126]
While typing the job title, company name or something else or changing the salary range, the frontend doesn't even wait a millisecond before calling `getJobs` from `<Sidebar/>`. This can flood the server even when nobody's intention is to do that.

This should ideally wait for atleast 300 - 500 milliseconds after user has changed any filter.

Video of too many requests:-

https://github.com/user-attachments/assets/cafb669f-f452-4912-96de-0b1fb81bb33b

**Comment by prateekkumaroriginal** [comment]
@VineeTagarwaL-code I have explained the problem and attached the video showcasing it.

**Comment by prateekkumaroriginal** [comment]
> Good work can you refactor the whole component btw ?

`Sidebar` ? Should i do it using `react-hook-forms`?

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/137 check this out !

**Comment by zeghabi01** [comment]
this issue have been solved in good way check my pull request #138

**Comment by zeghabi01** [comment]
my comment removed why?

**Comment by destructo570** [comment]
@VineeTagarwaL-code I also noticed that there was unnecessary API call for fetching jobs in Jobs page on initial load, which ended up calling the jobs api 2 times. I fixed it in #185 and also added a reusable debouce function in util and refactored the code a little bit.

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
