### ISSUE TITLE
[Bug] New Job Form Hides When Clicking Outside, Causing Data Loss

### ISSUE THREAD

**Issue by Fardeen26** [code100x/job-board#130]
## Description
When an admin is filling out the "New Job" form in the admin panel, the form unexpectedly hides when the admin clicks anywhere outside of the form. This behavior causes all entered data to be lost, which is frustrating and disrupts the job creation process.

## Steps to Reproduce
1. Login as Admin and Navigate to the Manage tab.
2. Click on the "Create Job" button to open the job creation form.
3. Begin entering data into the form fields.
4. Click anywhere outside the form (e.g., on the background or another part of the screen).

## Expected Behavior

- The "New Job" form should remain visible and not hide when clicking outside of it.
- The entered data should be preserved unless the admin explicitly cancels or submits the form.

## Proposed Solution

- **Cancel Button**: Add a "Cancel" button to the form, allowing admin to cancel the job creation process if needed. Clicking the "Cancel" button should close the form and clear any entered data.
- **Prevent Unintended Hiding**: Prevent the form from hiding when clicking outside of it. The form should only be dismissed via the "Cancel" button or after successful submission.

## Impact
This issue is causing inconvenience for admin who lose his progress unintentionally, leading to a poor experience.

## Demo Video

https://github.com/user-attachments/assets/d857b2d1-21df-434b-b415-014cc23638b8

## Additional Context
Implementing the above solution will ensure that the job creation process is more user-friendly and prevents accidental data loss.

**Comment by DevHrithik** [comment]
@VineeTagarwaL-code can I work on this issue!?

**Comment by Fardeen26** [comment]
@VineeTagarwaL-code I created this issue, so can you assign it to me?

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
