### ISSUE TITLE
refactored login page UI + replaced static css vars with theme vars + fixed sitebar styles and unwanted state updated after login

### ISSUE THREAD

**Issue by Harit007x** [code100x/job-board#134]
**Login UI**

before :
![image](https://github.com/user-attachments/assets/6f787eee-33ed-4c8a-a57e-1a6ef3603dc9)

After :
![image](https://github.com/user-attachments/assets/4744346b-b8d9-4b40-b21f-ee8702690df1)

**Jobs page User profile nav**
before:
![image](https://github.com/user-attachments/assets/2e1b1aec-54fc-4691-a673-c73e502982c8)

After:
![image](https://github.com/user-attachments/assets/024c7d83-a150-46db-bc61-e970ec65814d)

Covered these changes :
- [x] Replaced static tailwind vars with theme compatible vars
- [x] Refactored Login Page UI
- [x] Improvised styles and code for siteheader, navbar and mobile nav
- [x] Created a Logo component instead of using copy pasting same code multiple times
- [x] Replaced normal lucide imports with Icon component for better code pratices
- [x] Removed unwated useState updates after login that was causing error

**Comment by Harit007x** [comment]
@VineeTagarwaL-code I have made some improvisations in these PR that I think are important and should be dealt in early phase of the project. To set a general standard as the project progresses.

**My PR is ready for the review.**

Just a FYI, I am working on refactoring the UI for the Jobs Page. If you have anything specific to it or any suggestion, then do share it.

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/137, check this
