### ISSUE TITLE
[feat]  Thoughts on Improving the Job Portal

### ISSUE THREAD

**Issue by VenkataBhaskarr** [code100x/job-board#136]
## Key Points:

1. Remove Explore Section and Add Employee and Employer Sections. This will help organize the information and make it easier for users to find what they're looking for.

## Employer View 

1. Employers should be able to view information about all the currently enrolled students in the portal. This information should be presented in a way that allows employers to directly assess the candidates without the need for further checking.

2. The process of hiring a candidate should be streamlined, where further checking only happens if the employer decides to hire a specific candidate. This will make the hiring process more efficient for both employers and employees.

3. If the Employee want to hire from a pool then it comes down to general hiring platform where employer post the job application and users can apply.

### How the above process should happen 

1. There should be a ranking system which is directly dependent on the contributions to cohort projects. This ranking will help employers quickly identify top-performing candidates and facilitate the hiring process. ( This is usually done by harikirat when he wants to refer someone )

### How to fetch users contributions into our application 

1. We should create an application/ algorithm that will automatically fetches users contributions for cohort 3 projects and displays them.

## Employee View

Employees should be able to see all their job applications in the portal similar to  the same general features and functionality as other job portals.

## I am open for discussions

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/137 , check this for now

**Comment by VineeTagarwaL-code** [comment]
reach out to me on discord lets talk !
