### ISSUE TITLE
:wrench: [ FIX ] : Immediate Fixes Required - No PRs Will Be Merged Until Resolved

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#137]
The following issues need to be addressed as soon as possible. No pull requests (PRs) will be merged until all these issues are fully resolved:

   - Social Links: Fix the links for "Star us on GitHub" and "GitHub link" to point to 100xdev socials. Ensure all social media links are directed to 100xdev's official accounts.
   - NextAuth Migration: Migrate NextAuth from the beta version to the stable version.
   - Toaster UI: Improve the toaster UI for better user experience.
   
   -    /jobs Page: Resolve any issues on the /jobs page.
   -  Dark Theme: Ensure the dark theme is functioning correctly on all pages.
   - Fix the filter component
   - Fix the UI of filter component 
   

Please get assigned to the issue first. Only PRs from the assigned person will be accepted. Your PR must address all the issues mentioned above; partial fixes will not be accepted.

ScreenShot # 1 
- Login and check the navbar 
![image](https://github.com/user-attachments/assets/2f2a2a90-b5ed-4e9c-b80d-f13c04701352)

- Screenshot # 2
![image](https://github.com/user-attachments/assets/1489be84-ed11-4b9b-841f-93af4b8d9b54)

- Screenshot # 3 
![image](https://github.com/user-attachments/assets/02bdcb01-9445-4566-b990-44ff559c9c76)

Fix the UI, bugs that appear in the jobs page .. will be taking only one pr with all the solutions. will be bounty worthy !

**Comment by ofcljaved** [comment]
Can you assign it to me

**Comment by Dikshantw** [comment]
I can work on this @VineeTagarwaL-code . Assign me

**Comment by Fardeen26** [comment]
Can you assign any of one to me @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
@ofcljaved waiting to hear  from you soon !, no pr will be merged up until this is fully resolved

**Comment by Harit007x** [comment]
@VineeTagarwaL-code  Shall I pick this up too ?

**Comment by VineeTagarwaL-code** [comment]
javed is assigned, no one should open any pr in the meantime ref this issue

**Comment by keshav-exe** [comment]
Hey @VineeTagarwaL-code, I helped in the app.100xdevs page too, I would love to work on this!

**Comment by SwetanshuSingh** [comment]
@VineeTagarwaL-code Can I be assigned to this issue now?

**Comment by Harit007x** [comment]
Can I be assigned to this now ? @VineeTagarwaL-code

**Comment by SwetanshuSingh** [comment]
@VineeTagarwaL-code Can i be assigned now?

**Comment by VineeTagarwaL-code** [comment]
javed will be completing soon and opening it today only

**Comment by Nikhil7282** [comment]
**[Enhancement]**Replace Salary Slider with Range Inputs in Filtering form
![image](https://github.com/user-attachments/assets/c999108d-412d-489f-8450-4431e2c4437e)
