### ISSUE TITLE
[Feat] Contact Us Page

### ISSUE THREAD

**Issue by yash-kh** [code100x/job-board#141]
Features to be added:

- Contact form components.
- Added server-side logic aka Controller, Extended the Prisma schema to support contact form submissions.
- Added the contact-us page to the list of public routes.

**Comment by yash-kh** [comment]
I have already worked on the above features, What more can be done, whould i work on these as well:
1 - View for ADMIN
2 - Optional images, setup for S3 or any other storage.

**Comment by VineeTagarwaL-code** [comment]
Great will review and merge after #137 is solved
