### ISSUE TITLE
Server makes multiple requests when filtering

### ISSUE THREAD

**Issue by Sahil-Gulihar** [code100x/job-board#146]
This 

https://github.com/user-attachments/assets/9f97174d-a132-4ef8-9f9e-980ef9873c4a

PS the fact that login button throws an error (Needs optional chaining)

![Screenshot-07_08_2024-07-47-40](https://github.com/user-attachments/assets/61c850ff-30ac-48bc-9ee3-4a2c5d3d78bf)

**Comment by pranav-deshmukh** [comment]
working on it

**Comment by KaranMali2001** [comment]
I am not able to reproduce login error 

About debouncing effect , There are two problems 
1) ReactStrict mode , thats why it is re-rendering twiice
![image](https://github.com/user-attachments/assets/2c18458f-76f4-40f1-b226-b2e58ac79246)


2)in (protected)/jobs/page.tsx
we dont need to use useEffect hook as getJob function is getting called by SideBar.tsx 
![image](https://github.com/user-attachments/assets/bb3a94ea-183e-42d7-9131-951ad95c13e0)

3) In Slider.tsx Post request is going out for every time slider value changes (working on it )
@pranav-deshmukh  has proposed  solution by adding delay 
another way to do that is by using onValueCommit Property of Slider

**Comment by iamlikeaproforyou** [comment]
i propose the side bar should have a submit button which when clicked fetches the jobs as per filters. This will resolve the performance issue @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
#137 duplicate issue, please check pre opened issues and then only make a new one
