### ISSUE TITLE
Basic API Implementations for User, Cohort Student, Job Post, and Job Application Management (BACKEND)

### ISSUE THREAD

**Issue by Ur-Code-Buddy** [code100x/job-board#15]
**Implemented APIs:**

1. **User Management**

   - **Endpoints:**
     - `POST /api/users`: Create a new user.
     - `GET /api/users/:id`: Retrieve user details by ID.
     - `PUT /api/users/:id`: Update user details by ID.
     - `DELETE /api/users/:id`: Delete a user by ID.

2. **Cohort Student Management**

   - **Endpoints:**
     - `POST /api/cohortstudents`: Register a new cohort student.
     - `GET /api/cohortstudents/:id`: Retrieve cohort student details by ID.
     - `PUT /api/cohortstudents/:id`: Update cohort student details by ID.
     - `DELETE /api/cohortstudents/:id`: Delete a cohort student by ID.

3. **Job Post Management**

   - **Endpoints:**
     - `POST /api/jobposts`: Create a new job post.
     - `GET /api/jobposts/:id`: Retrieve job post details by ID.
     - `PUT /api/jobposts/:id`: Update job post details by ID.
     - `DELETE /api/jobposts/:id`: Delete a job post by ID.
     - `GET /api/jobposts`: Retrieve all job posts.

4. **Job Application Management**

   - **Endpoints:**
     - `POST /api/jobapplications`: Apply for a job.
     - `GET /api/jobapplications/job/:jobId`: Retrieve all applications for a specific job post.
     - `GET /api/jobapplications/cohortstudent/:cohortStudentId`: Retrieve all applications made by a specific cohort student.

**Note:**
- These APIs are basic templates intended to be a starting point for further development.
- The current implementations handle basic CRUD operations and data retrieval. 
- Additional features such as validation, authentication, and detailed error handling need to be integrated as the project evolves.

**Tasks:**
-  Implement detailed validation and error handling.
-  Add authentication and authorization where needed.

For detailed information about the implementation, please refer to the repository: [job-portal/backend](https://github.com/Ur-Code-Buddy/job-portal/tree/main/backend)

**Comment by NishantCoder108** [comment]
**Hi, I would like to work on this issue. Can you please assign it to me?**

**Comment by VineeTagarwaL-code** [comment]
nice suggestions, added them in my notion doc
