### ISSUE TITLE
[FEATURE]: Enhancing the current  Jobs Page, Admin CRUD Functionality, and Bug Fixes

### ISSUE THREAD

**Issue by devansh193** [code100x/job-board#150]
1. Enhancing the current jobs page with CRUD functionality for Admin.

I have already completed the jobs page and Edit Job Details form.

![Skeleton](https://github.com/user-attachments/assets/647b1771-940e-45dc-86ba-69be1c0fc035)
![Job](https://github.com/user-attachments/assets/a31a2eb5-b030-44a3-93dc-49797fe380cf)
![EditForm](https://github.com/user-attachments/assets/f8cdb55a-b468-4b2a-9f04-44f7aad97300)

2. Adding the active and inactive job functionality for admin to keep track of publish and unpublished jobs. 

@VineeTagarwaL-code as i am almost done with completing the features, i want you to assign this issue to me. I will raise a PR soon.

**Comment by mayank2130** [comment]
looks nice! Kudos to you. @devansh193

**Comment by VineeTagarwaL-code** [comment]
i will highly recommend you to check for issues first, i mentioned a total rewrite for all of this at #137,  without discussing and assigning wont be accepting any pr's
