### ISSUE TITLE
[improvement] Extract out sidebar from jobs to layout

### ISSUE THREAD

**Issue by aakash2330** [code100x/job-board#155]
Problem:
- The sidebar component currently handles managing the selected filter state as well as fetching jobs . This setup causes unnecessary re-renders of the sidebar, leading to potential performance issues.

Expected Behavior:
- The sidebar should only be responsible for updating the selected filter state.
Job fetching logic should be moved server-side and handled separately, reducing unnecessary sidebar re-renders.

Proposed Solution:
- Decouple the Sidebar Logic

- Move the job fetching logic out of the sidebar component. The sidebar should focus solely on managing and updating the selected filter state.

This change will improve the performance of the application by minimizing unnecessary re-renders and keeping the sidebar lightweight and focused on its primary function.

**Comment by aakash2330** [comment]
@VineeTagarwaL-code I'd like to be assigned if it's approved

**Comment by VineeTagarwaL-code** [comment]
duplicate issue : #137
