### ISSUE TITLE
[Bug] Dark Mode UI for Login page

### ISSUE THREAD

**Issue by DeepanshuMishraa** [code100x/job-board#156]
# Dark Mode Inconsistency on Login Page

## Issue
Login area not applying dark mode, while navbar and footer are dark.

## Expected
All elements should be in dark mode when enabled.

## Visual
![Dark Mode Issue](https://github.com/user-attachments/assets/dbf50535-2b83-4b4e-97f2-afc275c421a0)

@VineeTagarwaL-code

**Comment by DeepanshuMishraa** [comment]
@VineeTagarwaL-code Can you please assign this issue to me? I'd like to work on the fix.

**Comment by anuragnegi000** [comment]
This will be covered under #137

**Comment by VineeTagarwaL-code** [comment]
Covered under #137
