### ISSUE TITLE
Backend Schema + Notification Service Design for v1

### ISSUE THREAD

**Issue by Pheewww** [code100x/job-board#16]
Db Schema:
 USER ->   `user_id(PK), name, email, pwd, and github_profile. role - (hr/user), cohort_student, and badge`
JOB POSR -> attaching an image simply + [schema link](https://github.com/Pheewww/Job-portal/blob/main/prisma/schema.prisma)

![image](https://github.com/user-attachments/assets/72f8e108-24a0-4dea-8a62-64c051949e4b)

Subscription ->`subs_id, user_id, job_type`
either we chose to simply all notification to each user or they can subscribe to topics they want to be alerted for. But they will still get notified from discord/twitter etc.  webhooks. I am thinking they all follow a channel where notification will hit or maybe a bot can alert them each time.

Application -> user proposes for the job, `app_id, job_id, user_id, status - accept/reject/pending, created_at`

Notification Service:

Looking at the simplicity of remotejobs, it doesn't make sense to build our own notification service at this point. To build the MVP fast, we can implement use of webhooks for Discord, Twitter and Linkedin.

All users who will be associated with it will get the notifications. Apart from it, we must implement email notifications also.

![image](https://github.com/user-attachments/assets/24dbd94d-1d15-453e-b4c9-e61ebd246bf3)

**Comment by VineeTagarwaL-code** [comment]
Noted thanks, will open a issue soon on this for you guys to work on
