### ISSUE TITLE
Bug Report: Footer Misalignment and Sidebar Border Brightness in Dark Mode and Hamburger Sign Out Button

### ISSUE THREAD

**Issue by Rahul-Bhati** [code100x/job-board#162]
**Description:**

When dark mode is enabled, the footer is not positioned at the bottom of the page, which creates a noticeable UI bug.

![Screenshot (179)](https://github.com/user-attachments/assets/eb953e37-7580-4aa1-8280-44f1f2868386)

Additionally, the sidebar border in dark mode appears too bright compared to the rest of the UI. It would be better if the sidebar border matched the appearance of the navbar border.

**Expected Behavior:**
The footer should be aligned at the bottom of the page in dark mode. The sidebar border should have a consistent appearance with the navbar border.

**Final Version of the UI:**

![Screenshot (180)](https://github.com/user-attachments/assets/aec22966-2800-44a4-a8ba-ee1a23ec6b30)

**Comment by Rahul-Bhati** [comment]
Could you please assign me this issue?

**Comment by VineeTagarwaL-code** [comment]
#137 duplicate issue + PR
