### ISSUE TITLE
Prisma migrations might not be applied in the production stage if they are needed.

### ISSUE THREAD

**Issue by nolostra** [code100x/job-board#170]
Here are the main issues and improvements:

Caching layers effectively: Ensure that COPY package*.json ./ and npm install are separated from copying the entire application code. This allows Docker to cache the npm install layer and reuse it if package.json or package-lock.json hasn't changed.

Running Prisma migrations in production: Ensure the Prisma migrations are applied when the container starts in the production stage.

**Comment by nolostra** [comment]
@VineeTagarwaL-code can you please assign it to me ?

**Comment by VineeTagarwaL-code** [comment]
Yes go for it !
