### ISSUE TITLE
Add job type selection functionality (Full-time/Part-time/Internship)

### ISSUE THREAD

**Issue by Supsource** [code100x/job-board#171]
Implement a feature that allows users to select the type of job they are interested in (Full-time, Part-time, or Internship) when creating or searching for job postings. 
This will enhance user experience by providing more tailored job results and listings.

**Comment by Sajal0208** [comment]
Taking this up

**Comment by VineeTagarwaL-code** [comment]
We will be having a all new filter / logic for filtering and showing the jobs, i will high recommend you to wait for it it will be merged by today

**Comment by Sajal0208** [comment]
Sure, will look forward to it. Will implement this functionality on the new merged logic

**Comment by VineeTagarwaL-code** [comment]
#137 i highly recommended to wait for this to get resolved to open any pr or working, closing this right now but ready to review new  issues and pr on the current codebase

**Comment by Supsource** [comment]
Hey @VineeTagarwaL-code, I’m really interested in contributing to this repository. Would it be okay if I raise more issues or feature requests? I’d like to contribute according to the current codebase.
