### ISSUE TITLE
Bookmark the jobs 

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/job-board#174]
Currently, our webpage lacks a bookmark feature. By adding this functionality, users will be able to easily track the jobs they have applied for, as well as bookmark job postings they are interested in but have not yet applied to, allowing them to return and apply at a later time.

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code can i work on this feature.

**Comment by VineeTagarwaL-code** [comment]
for now we dont have such functionality that keeps tracks of users applications, we will have it in future but for now we only have links to application that companies give and not a personal record table to maintain
