### ISSUE TITLE
🚀 Feature: Add github Integrations to show the top contributors for selected repo's

### ISSUE THREAD

**Issue by shaurya35** [code100x/job-board#176]
### 🔖 Feature description

This feature is for the people who are hiring. We can make an Interface where they can see the top cohort contributors of selected repo's and list the top contributors for the same.

This will be made on a new page because it's different from normal hiring systems.

### 🎤 Why is this feature needed ?

Ease of Hiring.

### ✌️ How do you aim to achieve this?

Integrate GitHub api's to show the most contributions and the top contributors.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by shaurya35** [comment]
@VineeTagarwaL-code 
@hkirat 
How does it sound?

I tagged both to get a review on this idea or some improvements based on this.

**Comment by VineeTagarwaL-code** [comment]
How do you plan to execute this ?

**Comment by shaurya35** [comment]
@VineeTagarwaL-code 

I haven't worked on this type of code implementation before. 

The thing I can predict is github OAuth. 

Though I will be able to figure it out while on the way I code. 

Github OAuth -> Github API -> fetch data for top contributors -> make a db instance for the same -> store it -> render it on client

I guess this would be the structure. 
Feel free to improve it 
Open for suggestions.

**Comment by Yashodeeps** [comment]
hey @shaurya35  are you still working on this?

**Comment by shaurya35** [comment]
> hey @shaurya35  are you still working on this?
> I am waiting for a green signal to start
From @VineeTagarwaL-code Or @hkirat

**Comment by VineeTagarwaL-code** [comment]
coming back to this, i dont think we are building something as linkedin, its a simple job board, we dont need to overburden it with diff providers and info's
