### ISSUE TITLE
[ FEATURE ] : ⭐ Intializing the Repo 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#18]
#### Description
We need to set up the initial repository with the following technologies: Next.js, Prisma, Shadcn, Tailwind CSS, and TypeScript. Additionally, we require a well-designed landing page and an authentication setup. Bonus points for including a job ad posting feature.

#### Goals
1. Initialize the repository with Next.js, Prisma, Shadcn, Tailwind CSS, and TypeScript.
2. Create a visually appealing landing page.
3. Implement user authentication.
4. (Optional) Add a job ad posting feature.

#### Steps
1. **Initialize the Project**
   - Set up a new Next.js project.
   - Integrate TypeScript into the Next.js project.
   - Add Tailwind CSS for styling.
   - Integrate Prisma for database management.
   - Add Shadcn components.

2. **Create the Landing Page**
   - Design and implement a responsive landing page.
   - Ensure the landing page includes sections for the main features and a call to action.

3. **Set Up Authentication**
   - Implement authentication using a suitable library (e.g., NextAuth.js).
   - Include login, registration, and logout functionalities.
   - Ensure user sessions are managed securely.

4. **(Optional) Job Ad Posting Feature**
   - Implement functionality for users to post job ads.
   - Create a form for job ad submission.
   - Display submitted job ads on a separate page or section.

#### Acceptance Criteria
- [ ] The repository is initialized with Next.js, Prisma, Shadcn, Tailwind CSS, and TypeScript.
- [ ] A well-designed landing page is implemented and responsive.
- [ ] Authentication setup is completed with login, registration, and logout functionalities.
- [ ] (Optional) Users can post job ads, and these ads are displayed correctly.

#### Additional Notes
- Ensure the code follows best practices and is well-documented.
- Tests should be included where applicable.
- Provide clear instructions on how to set up and run the project locally.

By completing this feature, we will have a solid foundation for our project, making it easier to add new features in the future. Contributions that include the optional job ad posting feature will be given priority for merging.

**Comment by Praashh** [comment]
> First come, First server basis !

will we be using turborepo or nextJS ? @VineeTagarwaL-code ser?

**Comment by VineeTagarwaL-code** [comment]
also we are looking forward to making this repo beginner friendly, turborepo would be complex for them to understand

**Comment by dyaipayan22** [comment]
@VineeTagarwaL-code do you want a basic setup for people to get started with? People are making PRs with so many features already added.

**Comment by shaurya35** [comment]
![Screenshot 2024-08-05 183244](https://github.com/user-attachments/assets/1a263f36-0368-48fe-9d6f-04bcaab65380)

@VineeTagarwaL-code 
I think this could be a good landing page and could be improved.
I haven't made a pull request since few people have already made it.

I think let's start with the app structure on Excalidraw and then start implementing the app

**Comment by aay7ush** [comment]
@VineeTagarwaL-code I'm working on it. Please don't merge any pull requests today. Give it a day and then merge the best one out.

**Comment by VineeTagarwaL-code** [comment]
as written it will be on first come first serve, the best PR will be merged no matter the order of which it came in .. so make sure you pr is good

**Comment by aay7ush** [comment]
@VineeTagarwaL-code bhai I told you to wait, still you merged the PR
