### ISSUE TITLE
🚀 Feature: 

### ISSUE THREAD

**Issue by ppratik07** [code100x/job-board#184]
### 🔖 Feature description

 User Registration Feature

### 🎤 Why is this feature needed ?

This feature will allow new users to register for an account on the platform. The registration process will include collecting essential user details, validating the information, and securely storing it. The feature will also include options for email verification, password strength checks etc

### ✌️ How do you aim to achieve this?

1. Develop a registration form.
2. Implement secure APIs for handling registration data.
3. Checking validations
4. Storing the data in database.
5. Allowing the user to popup alert showing registration is sucessfull.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by OmkarK97** [comment]
Can you please assign me this, @ppratik07?

**Comment by OmkarK97** [comment]
I have created a pr for this feature. Can you please check it once @ppratik07

**Comment by VineeTagarwaL-code** [comment]
We already have signup form
