### ISSUE TITLE
✨ Improvement: Align the placeholders of input fields and text inside buttons on the "/jobs" page

### ISSUE THREAD

**Issue by balkishan-gh** [code100x/job-board#187]
### 📜 Description

Please take note of the following issue: The input field placeholders and the text inside buttons in the Job Filters section on the "/jobs" page are not aligned and require some additional padding. It's a minor issue, but it should be fixed as it affects the visual appeal. Thank you.

### 👟 Reproduction steps

1. Go to the "/jobs" page

### 👍 Expected behavior

 The input field placeholders and the text inside buttons should be aligned.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by balkishan-gh** [comment]
Hey @VineeTagarwaL-code, can I fix this?

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
