### ISSUE TITLE
✨ Improvement: Add little bit more space between "Job Location" button and salary slider and remove extra padding on the left from social icons section

### ISSUE THREAD

**Issue by balkishan-gh** [code100x/job-board#188]
### 📜 Description

Add some space between the "Job Location" button and the salary slider, and remove the extra padding on the left from the social icons section on the "/jobs" page. On the "/home" page, it looks good as there's nothing above it. It's a minor issue, but it needs to be fixed as it's not visually appealing.
Before:
![job_board_01](https://github.com/user-attachments/assets/e331d93f-e71c-4d74-8874-c42e44cfa959)

### 👟 Reproduction steps

1. Go to the "/jobs" page

### 👍 Expected behavior

After:
![job_board_02](https://github.com/user-attachments/assets/d81cfc58-5f4c-4706-a3d0-f3ab81bdd66e)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by balkishan-gh** [comment]
Hey @VineeTagarwaL-code, can I fix this?

**Comment by VineeTagarwaL-code** [comment]
new Code is up, would love to see issues on that
