### ISSUE TITLE
Improving the job creating modal

### ISSUE THREAD

**Issue by patha2702** [code100x/job-board#191]
### 📜 Description

Enhancing the job creating modal with nice ui, and adding editor for taking job and company description. Here is the reference of ui: 

https://github.com/user-attachments/assets/b0946580-6971-4e0e-8f35-45c06aa0f084

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by patha2702** [comment]
can I work on it @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
No proper expected images, ref given ... closing
