### ISSUE TITLE
✨ Improvement: CI Workflow for linting and integrity

### ISSUE THREAD

**Issue by pawann-2000** [code100x/job-board#192]
### 📜 Description

It's an improvement when there are pre-commit hooks for checking linting and code integrity

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
Great go ahead
