### ISSUE TITLE
🐛 Bug Report: Responsiveness in Explore Page

### ISSUE THREAD

**Issue by Ashutoshpadhi629** [code100x/job-board#196]
### 📜 Description

The Explore Page is Not Responsive .

### 👟 Reproduction steps

Explore page ... job Filter component

### 👍 Expected behavior

The job filter Component should be a sidebar in mobile view

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/cd0e3d38-90c2-4af1-96ed-abb2c7e4d14a

### OS name

MacOS

### browser name

Brave

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Ashutoshpadhi629** [comment]
hey @VineeTagarwaL-code , can you assign me to work on this?

**Comment by dinesh8368** [comment]
![image](https://github.com/user-attachments/assets/4123eb0d-2af5-430a-8c3f-d0ceacee2fa5)
What do you about this flow in response devices?
1. use shadcn drawer.

**Comment by VineeTagarwaL-code** [comment]
very nicely explained and detailed, assigning you for this issue .... expecting to hear back within 2 days atleast

**Comment by VineeTagarwaL-code** [comment]
who wants to take this up ? @Ashutoshpadhi629 @dinesh8368 ?

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code , I will like to work on this

**Comment by VineeTagarwaL-code** [comment]
a new issue is up with new figma design, please look onto that ... thanks for the pr but this wont work for now
