### ISSUE TITLE
✨ Improvement: Enhancing job creating modal

### ISSUE THREAD

**Issue by patha2702** [code100x/job-board#198]
### 📜 Description

Enhancing job creating modal with nice ui and editor for taking job description and company description as input. Here are the references of the ui: 
![job-create-1](https://github.com/user-attachments/assets/d870872c-3e48-4d9a-864b-366062e51741)
![job-create-2](https://github.com/user-attachments/assets/5c50fcf0-7789-4595-86b7-3de0376f1ce6)
![job-create-3](https://github.com/user-attachments/assets/836ff247-f5bf-4765-b6f8-a0b3212e2124)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by patha2702** [comment]
can I work on it @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
The issues seem good, but dont you think that having a good page dedicated for just form is more better than cramping it up in this small place or atleast use a bigger modal

**Comment by justanuragmaurya** [comment]
@VineeTagarwaL-code since there is no rsponse from yesterday , i would like to work on this

**Comment by patha2702** [comment]
Instead of creating a modal I have restyled the existing job creating page, is this ok @VineeTagarwaL-code : 
![job-1](https://github.com/user-attachments/assets/13853695-dadb-4d04-a591-c099edc9db10)
![job-2](https://github.com/user-attachments/assets/70cef4e3-8528-4652-8b12-a2e719b2ff93)
![job-3](https://github.com/user-attachments/assets/ac01e349-6026-40e0-8b60-8e6e75edb63b)

**Comment by VineeTagarwaL-code** [comment]
https://github.com/code100x/job-board/issues/288

refer to this and open a pr if you can
