### ISSUE TITLE
🐛 Bug Report: TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by AmiyaPiyush1** [code100x/job-board#203]
### 📜 Description

Everytime I try to Login for the very first time,This error pops 

### 👟 Reproduction steps

1.Go to Jobs 2.Enter your details to login 3.For the very first time you will see this error message 4. But if you reload the page the issue goes away

### 👍 Expected behavior

"I expected to be logged in successfully without encountering any errors on the first attempt."

### 👎 Actual Behavior with Screenshots

"Upon submitting the login form, the page throws a TypeError: Cannot read properties of undefined (reading 'status'). However, when I reload the page and attempt to log in again, the issue no longer occurs."

### OS name

Windows

### browser name

Chrome

### 📃 Provide any additional context for the Bug.

"This issue only occurs during the first login attempt. It seems like there might be a race condition or uninitialized variable causing the error. I'm using Windows with Chrome as my browser, and the error is consistent across different systems with similar setups

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by pawann-2000** [comment]
Looks fine on my end, please attach screenshot or video for reference

![image](https://github.com/user-attachments/assets/fa4f52eb-52c8-457f-9d0f-4434a1c35653)

**Comment by VineeTagarwaL-code** [comment]
We are looking forward to remove that login flow

**Comment by Ashish-simpleCoder** [comment]
Login for admin and users working fine on my side too.
