### ISSUE TITLE
✨ Improvement: There is no debouncing in filters like Job title and company name

### ISSUE THREAD

**Issue by AmiyaPiyush1** [code100x/job-board#204]
### 📜 Description

Go to the job search page.
Start typing in the Job Title or Company Name filter fields.
Observe that with each keystroke, a request is immediately sent to the backend.

### 👍 Expected behavior

"I expected the filters to implement debouncing, so the request is sent only after the user stops typing, reducing unnecessary backend requests and improving the user experience."

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by AmiyaPiyush1** [comment]
There is no debouncing added in Job filter sections which increases the load in backend. Can you please assignme this task

**Comment by pawann-2000** [comment]
Please attach a screenshot for the issue from your end, and can you ensure that you have the latest changes pulled?

**Comment by AmiyaPiyush1** [comment]
https://github.com/user-attachments/assets/d454fc78-b576-4334-8c59-331d052e93a8            
here i am attached a video which shows that after every click the app is hitting the backend

**Comment by dinesh8368** [comment]
@AmiyaPiyush1 please take pull of latest changes.

**Comment by VineeTagarwaL-code** [comment]
@AmiyaPiyush1 Please pull first
