### ISSUE TITLE
🐛 Bug Report: The loading was not aligned properly in the explore page.

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/job-board#205]
### 📜 Description

![Screenshot 2024-08-17 190744](https://github.com/user-attachments/assets/9392bd9b-664f-4863-a2b1-235ae9944bfa)

### 👟 Reproduction steps

1. go to the explore page
2. you can find the see the loader when it is quering the jobs

### 👍 Expected behavior

it should come in the center of that particular page.

### 👎 Actual Behavior with Screenshots

it actually come in the center of that particular web page.

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by pawann-2000** [comment]
Can you share server logs like so?

![image](https://github.com/user-attachments/assets/e18c4819-2b18-4e27-bb88-cc2efb8d2a10)

**Comment by Sam-Frost** [comment]
I have fixed the issue, it was an easy fix. Should I create a pull request?
P.S : New to contributing to open source(This would be my first contribution)
![Screenshot 2024-08-17 at 10 11 42 PM](https://github.com/user-attachments/assets/6e32aad6-2454-43d5-b9bb-540d0433af88)

**Comment by justanuragmaurya** [comment]
@VineeTagarwaL-code could i work on this?

**Comment by VineeTagarwaL-code** [comment]
@Sam-Frost worked on this and it looks quite clean too, will be assigning sam frost for this issue

**Comment by VineeTagarwaL-code** [comment]
also sam i think using that loading icon is much better than " Loading... ", good job hoping to see a pr on that soon

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code @Ameerjafar  i also fixed this
![Screenshot (139)](https://github.com/user-attachments/assets/40b7751a-3e2c-439e-94d6-8111d6dcc317)
or
![Screenshot (140)](https://github.com/user-attachments/assets/c7059dda-e604-4d84-8fd8-e7666cc782e6)

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code @Ameerjafar i also fixed this issue 
should i make a pull req 
![Screenshot (141)](https://github.com/user-attachments/assets/40754e72-d835-49e5-bbd1-05aee9b5ee6a)
and
![Screenshot (142)](https://github.com/user-attachments/assets/ac95af36-e3fe-4484-ae04-7cf2a0e12002)
this is my first time i solve issue

**Comment by Satyam3245** [comment]
> I have fixed the issue, it was an easy fix. Should I create a pull request? **Loading in Center** ![Screenshot 2024-08-17 at 10 11 42 PM](https://private-user-images.githubusercontent.com/40019398/358857813-6e32aad6-2454-43d5-b9bb-540d0433af88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTU3NDMsIm5iZiI6MTcyMzkxNTQ0MywicGF0aCI6Ii80MDAxOTM5OC8zNTg4NTc4MTMtNmUzMmFhZDYtMjQ1NC00M2Q1LWI5YmItNTQwZDA0MzNhZjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE3MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDA1NTllMmY1NjEzOWE1OThiN2UwMjU0MmNiZmVlYTAyNDVhYjQ5YjJmNzhiNGRmYzY4MmMyZWI0MDZmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I4_8BXvglpg6y9-u5pV1lCjTscb_ECdBQY9xamzeW_c) **OR** **Spinning Loader in Center** ![Screenshot 2024-08-17 at 10 20 30 PM](https://private-user-images.githubusercontent.com/40019398/358858253-d804542b-6d4d-4841-9b03-60af0f4a9444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTU3NDMsIm5iZiI6MTcyMzkxNTQ0MywicGF0aCI6Ii80MDAxOTM5OC8zNTg4NTgyNTMtZDgwNDU0MmItNmQ0ZC00ODQxLTliMDMtNjBhZjBmNGE5NDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE3MjQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYzk4NmU1NGM3NjhkZDRmNmY3OTUxY2I4Mjg3MmQzY2Q2YzcyNDQyYWUzZjhkNDkwZWVlMmY1ZThjNTk3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EvZL03q3v8kWiE6Zpr5Hitk1Y049N_fEUh51u5Ozgxs)
> 
> P.S : New to contributing to open source(This would be my first contribution)

in this approach I think the height of the all jobs component is increase as the jobs are post and loader is seen in the middle of the screen which is seen through the scrolling because the height is increase as the more job post which cause the loader to present in the middler of the <AllJobs/> comp with . or am I wrong ?

**Comment by Sam-Frost** [comment]
@Satyam3245 I am not sure about what you are asking, when the loader shows the jobs won't be appearing on the screen and it disappears as soon as the jobs show up on the screen. The loader is contained inside div which is 100% height and width of its parent. I have created a PR, you can have a look at my code there.

**Comment by Ameerjafar** [comment]
@Sam-Frost congrats for your first contribution.

**Comment by Ameerjafar** [comment]
closing the issue now.
