### ISSUE TITLE
✨ Improvement:  create_jobs: remove jitter on toggle button     - add animation     - increase size of form

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#207]
### 📜 Description

when you toggle the select salary range button it will jitter the screen and the form appears abruptly 

### 👟 Reproduction steps

1.go to create jobs page
2.click on select salary range button

### 👍 Expected behavior

it should smoothly show the change  

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by subhadeepsonu** [comment]
https://github.com/user-attachments/assets/4110b120-2ec5-49ac-bd9d-74a206acc26b

There is jitter effect when u click on the button

https://github.com/user-attachments/assets/af4d34c0-bb3a-489d-98d0-328f09e4e8ea

Add animation to make the form appear smoothly and added padding to stop jitter caused the scrollbar

i have already done this i will make a pr if its ok

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code can i make a pr ?

**Comment by VineeTagarwaL-code** [comment]
1. dont work before before being assigned 
2. we will be adding a very nice detailed ui posting page, would advice you to wait until that issue is up
