### ISSUE TITLE
✨ Improvement: Moving toast from shadcn to sooner

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#208]
### 📜 Description

The toast now does not look good 

### 👟 Reproduction steps

go to sign up create acc  and many more

### 👍 Expected behavior

i will add sooner library to get good ui for the toast similar to cms repo toast 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by subhadeepsonu** [comment]
Can i work on this ?

**Comment by VineeTagarwaL-code** [comment]
what are we migrating our toasters from shadcn to sooner ?

**Comment by subhadeepsonu** [comment]
yes
