### ISSUE TITLE
🚀 Feature: Add database Schema model applying for jobs,skills,resume for jobsekker

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#209]
### 🔖 Feature description

Add database schema 
job seeker can have many to many relationship with skills table 
job seeker will have resume link as an additional attribute 
job seeker and jobs will have many to many relationship as applied jobs

 

### 🎤 Why is this feature needed ?

This feature will make recruiter know the skills of job seeker and see who all have applied for the job 

### ✌️ How do you aim to achieve this?

i will make 2 new tables 
skills and applications will relate them to job seeker and jobs 
will alter job seeker table and add optional resume link

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code can i work on this

**Comment by VineeTagarwaL-code** [comment]
wont be having any account info for jobseeker in our portal as for now, thanks for suggesting though

**Comment by subhadeepsonu** [comment]
Can you tell me when we will do this so i can make a pr
