### ISSUE TITLE
✨ Improvement: home page git hub link button improved in light mode

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#210]
### 📜 Description

The button which redirects to the git hub repo is not having good ui in light mode

### 👟 Reproduction steps

landing page 
git hub redirect button

### 👍 Expected behavior

It should  be clear and look good

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by subhadeepsonu** [comment]
![image](https://github.com/user-attachments/assets/88d8b819-10d7-4023-8ebf-d76dded5a026)
before
![image](https://github.com/user-attachments/assets/1517f6cd-0ba9-4a87-b894-182fcc16a690)
after

**Comment by VineeTagarwaL-code** [comment]
great open a pr for it asap

**Comment by VineeTagarwaL-code** [comment]
closing
