### ISSUE TITLE
🐛 Bug Report: When there are no jobs it says nothing 

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#212]
### 📜 Description

When there are no jobs for the filters applied or intially i it says nothing

### 👟 Reproduction steps

go to jobs 
apply filter such that no jobs appear

### 👍 Expected behavior

it should say no jobs availble right now

### 👎 Actual Behavior with Screenshots

says nothing 
![image](https://github.com/user-attachments/assets/2d3abdba-da2f-4b66-a915-ab5a3db40b9c)

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code can i work on this

**Comment by VineeTagarwaL-code** [comment]
great find, can you answer me one thing ? was your db seeded or not ?

**Comment by subhadeepsonu** [comment]
i tested it before seeding to see what happens

**Comment by VineeTagarwaL-code** [comment]
yep sure

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code made the pr for both the issues please merge

**Comment by VineeTagarwaL-code** [comment]
where are the pr's ?

**Comment by subhadeepsonu** [comment]
i have made the pr on the same day @VineeTagarwaL-code i closed it saying already done

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code https://github.com/code100x/job-board/pull/213/commits/c4e76b59c1539de67da30f5b36cc19fa40217bc1
