### ISSUE TITLE
✨ Improvement: User should own a company which can offer jobs

### ISSUE THREAD

**Issue by subhadeepsonu** [code100x/job-board#217]
### 📜 Description

1.Currently the admin have to review every job posting
2. by doing this a user can have the company and if the company is verified then all the job postings they post can be verified by default 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by subhadeepsonu** [comment]
@VineeTagarwaL-code can we do this 
as this is something that can be helpful and avoid the wait for well recognized organizations

**Comment by VineeTagarwaL-code** [comment]
we will have pay wall and after that admin will verify, wont be automating that for now
