### ISSUE TITLE
✨ Improvement: Wrong Placeholders in /create page

### ISSUE THREAD

**Issue by justanuragmaurya** [code100x/job-board#218]
### 📜 Description

There are wrong placeholders for the inputs in the create page , the placeholders for  Location and the price range are  incorrect.
<img width="1822" alt="Screenshot 2024-08-18 at 10 54 53 AM" src="https://github.com/user-attachments/assets/ed08ef1f-07b6-4c1f-9df9-6a2efc1f1a38">

### 👟 Reproduction steps

1. Go to https://localhost:3000/create
2. You can see the wrong placeholder for the Location is incorrect. 
3. Click on Salary Range checkbox/option .
4. Erase the input and now you can see the placeholders having wrong info.

### 👍 Expected behavior

The placeholders should display respective correct info.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by justanuragmaurya** [comment]
@VineeTagarwaL-code i would like to work on this , last time you assigned my raised issue to someone else... 😢

**Comment by subhadeepsonu** [comment]
they are changing the whole ui of create jobs page its already assigned to someone else
