### ISSUE TITLE
🚀 Feature: top loader bar

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#223]
### 🔖 Feature description

When the page is rendering we can show loading animation 

### 🎤 Why is this feature needed ?

Displaying a loading screen while data is being fetched from the database is essential for a better user experience. It reassures users that the page is loading properly, preventing confusion and frustration that might occur with a blank screen. This simple feature helps make the application appear more professional and keeps users engaged, reducing the chance of them leaving the page.

### ✌️ How do you aim to achieve this?

I can implement nextjs progress bar package to do this.

### 🔄️ Additional Information

I will like to work on this issue. plz assign this to me.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code can you plz check this out.

**Comment by VineeTagarwaL-code** [comment]
Please reopen this with proper images and video references
