### ISSUE TITLE
🚀 Feature: Automated Email Notification for New Job Posts

### ISSUE THREAD

**Issue by Satyam3245** [code100x/job-board#228]
### 🔖 Feature description

Implement an email sender service that triggers and sends an automated email notification to subscribed users when a new job is posted on the website.
The email will contain details about the job post, including the job title, company, location, and a link to view the full job description on the website.
The email should be sent to all users who have opted in to receive notifications for new job postings.

### 🎤 Why is this feature needed ?

To notify users via email whenever a new job is posted on the website, ensuring they are informed promptly and can act on new opportunities quickly

### ✌️ How do you aim to achieve this?

using nodemailer and a admin email like 100xdevs@gmail.com and the pass key that we pass in the .env file

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code can i make a pr

**Comment by praneash2** [comment]
@VineeTagarwaL-code  so my approach for this issue will be when a job is posted ill fetch the subscribers for the email from the db and then iterate through them and using the node mailer ill send the mail as you've mentioned in the format.Can i work on this pr?

**Comment by Yashodeeps** [comment]
@VineeTagarwaL-code  I have worked with email notification service before it was RESEND that i used. I would be happy to work on it if you assign me the issue

**Comment by Satyam3245** [comment]
@Yashodeeps @praneash2 @VineeTagarwaL-code what if the user want to locally set up the project and it need to be a email account which will have all function that need to start a smpt server it take more time to setup the project locally

**Comment by Yashodeeps** [comment]
You could use an email service like Resend, or SendGrid. In there, you have to update the DNS of the domain and then you can send emails from any mail address you want. You can define an email template in the code base and use it whenever job posting occurs.

**Comment by VineeTagarwaL-code** [comment]
Some iterations on the idea : 

1. user can subscribe 
2. user can only subscribe based on certain location and job role, if any job matching the role and nearby location then we can send the email 


for now it doesn't sounds for now but maybe a good addition in future
