### ISSUE TITLE
✨ Improvement: Add option to sort jobs with salary amount

### ISSUE THREAD

**Issue by Rohan-Hazari** [code100x/job-board#230]
### 📜 Description

Add an option to sort the jobs in descending order based on their salary (minimum salary)

### 👍 Expected behavior

https://github.com/user-attachments/assets/83553571-bf0d-463b-b478-2c004c6485f3

Selecting the option Highest Pay from dropdown will sort the jobs in descending order based on their minimum Salary in the salary range.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Rohan-Hazari** [comment]
@VineeTagarwaL-code can I raise PR? the changes are ready

**Comment by aakash2330** [comment]
did you remove the latest jobs sort ?

**Comment by Rohan-Hazari** [comment]
> did you remove the latest jobs sort ?

I dont think so check my PR

**Comment by Rohan-Hazari** [comment]
@VineeTagarwaL-code ??

**Comment by Rohan-Hazari** [comment]
Hi @VineeTagarwaL-code  can I raise the PR?

**Comment by VineeTagarwaL-code** [comment]
this looks good please open the pr again
