### ISSUE TITLE
✨ Improvement: Add Location in Job Listings 

### ISSUE THREAD

**Issue by kanishkraj07** [code100x/job-board#232]
### 📜 Description

Integrate the job location and work mode within parentheses in job listings.

### 👍 Expected behavior

![image](https://github.com/user-attachments/assets/8fb91fe4-aa35-43de-8429-507f699de972)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by kanishkraj07** [comment]
I have made changes for this, can i raise PR ? @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
yep lets do it
