### ISSUE TITLE
✨ Improvement: Make input elements (input boxes, selects, sliders, toggles) look better.

### ISSUE THREAD

**Issue by amanDhiran** [code100x/job-board#233]
### 📜 Description

The current focus rings around input elements (input boxes, selects, sliders, toggles, etc.) are too thick and have a weird offset, which affects the visual appeal and user experience. Reducing the ring thickness and adjusting the offset would result in a cleaner UI.
current: 

![before](https://github.com/user-attachments/assets/f88cea27-9f67-4975-aec8-1ba2f3cb4b8b)
![select-before](https://github.com/user-attachments/assets/b85a59b1-cf46-4b01-9362-a3185e2d2062)

Improved Input elements:
![after](https://github.com/user-attachments/assets/85faae01-ab87-4f74-911d-cf6e7c50ef9d)
![select-after](https://github.com/user-attachments/assets/f72f3fec-3870-4971-bd81-f1e75d608308)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
go ahead lets how you do

**Comment by VineeTagarwaL-code** [comment]
new form is up, please look on that and suggest / do changes there
