### ISSUE TITLE
🚀 Feature: New ui for the jobs page

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#235]
### 🔖 Feature description

The filter can be placed at the bottom of the search results, and the search bar can be large. There's no need to create separate pages for each job; they can all be managed on the jobs page.

Just like in the image below:

![Screenshot 2024-08-19 231306](https://github.com/user-attachments/assets/1aa104f2-acb2-4711-932d-d31969bd5401)
![Screenshot 2024-08-19 233248](https://github.com/user-attachments/assets/8ec21245-6451-46b9-af2b-9f5363111245)

### 🎤 Why is this feature needed ?

This feature improves user experience by offering flexible filter placement and a more accessible search bar, making the job search process more intuitive. It also simplifies navigation by managing all jobs on a single page, eliminating the need for separate pages for each job.

### ✌️ How do you aim to achieve this?

i will create a ui just like in the above images.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Anastand** [comment]
Still woundn't it be better for us to view each Job as a page and look through it

**Comment by Paribesh01** [comment]
Yes, you are correct. But we can provide preview of all the job description , then when user click on the apply button, you can go to the each job page

**Comment by Anastand** [comment]
@Paribesh01 


I like the idea of that , it allows easy look through the posted jobs and detail view when needed

**Comment by VineeTagarwaL-code** [comment]
we already are working on the it for example a issue is up with new design, pleaese discuss before starting to work
