### ISSUE TITLE
✨ Improvement: Reset All Filters in Job searching filters

### ISSUE THREAD

**Issue by BearerOP** [code100x/job-board#236]
### 📜 Description

Currently, when users apply multiple filters while searching for jobs, there isn't an option to **reset all filters at once**. This can be cumbersome, especially when users need to clear all selected filters and start a new search.

### 👟 Reproduction steps

1. Go to the Job Search page.
2. Apply multiple filters (e.g., job type, location, salary range).
3. Notice that there is no option to reset all filters simultaneously.
4. Users currently have to manually deselect each filter, which is time-consuming.

https://github.com/user-attachments/assets/f825a659-131a-44fc-90e0-87b200c86a95

### 👍 Expected behavior

When the "Reset All Filters" button is clicked, all selected filters (e.g., job type, location, salary range) should be cleared instantly, returning the job search results to their default, unfiltered state. The page the unfiltered results, allowing the user to start a new search without any previous filters applied.

https://github.com/user-attachments/assets/f819d04b-d464-42ac-b538-1090e2dcfdae

### 📃 Provide any additional context for the Bug.

The absence of a "Reset All Filters" button requires users to manually deselect each filter. This can be frustrating and time-consuming, especially for users who frequently adjust their search criteria. Implementing this feature would streamline the job search process, improve user satisfaction, and reduce the time spent on unnecessary actions.

This feature is particularly important for users who rely on the platform for extensive job searches, as it would greatly enhance the overall usability and efficiency of the job search tool.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by BearerOP** [comment]
Hey @VineeTagarwaL-code ! I've completed the improvement to reset all filters in the job searching filters. Could you please assign the issue to me so I can submit the pull request? Thanks!

**Comment by VineeTagarwaL-code** [comment]
the expected result is correct, but i believe after the reset is clicked the params should also be updated

**Comment by BearerOP** [comment]
Corrected the code you can check in pr #238
