### ISSUE TITLE
🚀 Feature: Logged In user can able to see which are the Jobs they have applied

### ISSUE THREAD

**Issue by Ameerjafar** [code100x/job-board#239]
### 🔖 Feature description

User can easliy see the applied jobs if they logged into the website,

### 🎤 Why is this feature needed ?

With the help of this feature the user does not need to re search the applied jobs.

### ✌️ How do you aim to achieve this?

whenever the user applied for the jobs I will store the jobId in the users table with the help of this implement we can easily able to retrieve the applied jobs of the specific user. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code can you assign this issue to me?

**Comment by VineeTagarwaL-code** [comment]
#201, please check out pre existing issues before opening or workin
