### ISSUE TITLE
feature:Add a tooltip box showing the name of the social site that appears when the user hovers over social icons in the footer

### ISSUE THREAD

**Issue by AmiyaPiyush1** [code100x/job-board#243]
### 🔖 Feature description

The proposed feature will enhance the user interface by displaying a tooltip box that shows the name of the social media site when a user hovers over the social icons in the footer. This tooltip will provide clear, immediate feedback to users about which social media site each icon represents, improving accessibility and user experience.

### 🎤 Why is this feature needed ?

In my use case, this feature will improve the usability of the footer section by ensuring that users can easily identify the purpose of each social media icon. It will enhance the overall user experience and make the interface more intuitive.

### ✌️ How do you aim to achieve this?

I aim to achieve this feature by:

Adding tooltip functionality to the social icons.
Styling the tooltip to appear above the icon when hovered, with a chat-like bubble appearance.
Ensuring the tooltip is accessible and visually appealing

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
Nice issue, checking it out rn if all good will merge directly
