### ISSUE TITLE
🚀 Feature: Display Time Elapsed Since Job Posting

### ISSUE THREAD

**Issue by Satyam3245** [code100x/job-board#244]
### 🔖 Feature description

Add a feature to display the time elapsed since a job was posted. This will help users quickly see how long ago a job was posted, such as "1 day ago" or "2 days ago." This feature will improve the user experience by providing context on the recency of job postings, which can influence their decision to apply.

### 🎤 Why is this feature needed ?

this feature help user to find the Job Posting Timing

### ✌️ How do you aim to achieve this?

Using Date() function 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Satyam3245** [comment]
This is How it Look After Adding this Feature 

After
![Screenshot (147)](https://github.com/user-attachments/assets/04b14c14-9f47-4971-92e3-c6aa4215175d)
Before

![Screenshot (148)](https://github.com/user-attachments/assets/485fc8f7-552a-4ef7-9ac2-a93b66cec551)

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code  Do i make a Pull request

**Comment by VineeTagarwaL-code** [comment]
nice issue man

**Comment by VineeTagarwaL-code** [comment]
yeah pleaes make the pr here i will merge

**Comment by kanishkraj07** [comment]
Hello @VineeTagarwaL-code  the same feature i have developed before in this issue #234

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code 
The feature to display the job posting time has been added. You can review the implementation in #263 
 Let me know if there are any changes needed.

**Comment by Satyam3245** [comment]
@VineeTagarwaL-code I have implemented the requested feature and opened a pull request for it :  #266
Please let me now if any changes is made .
