### ISSUE TITLE
🚀 Feature: Add Password Visibility Toggle Feature to Signup and Signin forms

### ISSUE THREAD

**Issue by Fardeen26** [code100x/job-board#245]
### 🔖 Feature description

Should add a toggle button to show/hide the password in the signup and signin form.

### 🎤 Why is this feature needed ?

This feature would enhance the user experience by giving users the option to verify their password input before submission. In my use case, it's helpful for users to double-check their password without needing to retype it in case of errors.

### ✌️ How do you aim to achieve this?

I want this feature to include an eye icon next to the password field that allows users to toggle between showing and hiding their password.

### 🔄️ Additional Information

I tried implementing this and have successfully added the functionality on my local branch.

## Before

https://github.com/user-attachments/assets/5555b2b7-5f3c-4768-9fd3-11b248e1dc40

## After

https://github.com/user-attachments/assets/f2914b43-a7f0-49d6-a125-92b7f913e180

@VineeTagarwaL-code , can I create a PR for this

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Fardeen26** [comment]
Hey @VineeTagarwaL-code , I have created and solved the password visibility toggle issue (#245), but it looks like Yash-KK jumped in and submitted a PR for it without asking. Not sure how we should handle this, but I thought I'd let you know since I had already worked on it.

**Comment by Yash-KK** [comment]
@Fardeen26.,
I noticed the password visibility toggle issue (#245) was not assigned to anyone, so I went ahead and submitted a PR to address it. 
@VineeTagarwaL-code,
If @Fardeen26  already worked on it, please feel free to ignore my PR.

**Comment by Fardeen26** [comment]
> @Fardeen26., I noticed the password visibility toggle issue (#245) was not assigned to anyone, so I went ahead and submitted a PR to address it. @VineeTagarwaL-code, If @Fardeen26 already worked on it, please feel free to ignore my PR.

Hey Buddy , Thanks for your understanding! There’s no issue at all with your PR. I just wanted to clarify that it's generally a good practice to wait for issue assignments before submitting a PR to avoid overlaps. I understand that Vineet is quite busy this week and hasn't had a chance to assign it yet.
I value your effort and contributions!

**Comment by VineeTagarwaL-code** [comment]
guys please do check the pre existing issues before opening any new ones, i clearly mentioned we want to remove the signin / signup forms

**Comment by VineeTagarwaL-code** [comment]
#201 for you ref
