### ISSUE TITLE
✨ Improvement: After login  "Login Successful Welcome Back" Stays for long time.

### ISSUE THREAD

**Issue by Ankit7rma** [code100x/job-board#250]
Currently, after a successful login, the message "Login Successful, Welcome Back" remains on the screen for an extended period. This can be distracting or redundant for users who wish to proceed with their tasks quickly.

🎤 Why is this Improvement Needed?
Reducing the duration of the success message improves user experience by allowing them to focus on their next actions without unnecessary delays. A shorter display time will make the interface feel more responsive and efficient.

✌️ How Do You Aim to Achieve This?
The improvement will involve adjusting the duration of the success message display to a shorter period. Additionally, ensuring that users can continue interacting with the application without needing to wait for the message to disappear will create a smoother experience.

### 👟 Reproduction steps

1 .Login using Creds.

### 👍 Expected behavior

it should be for 2-3 seconds for better user experience.

### 📃 Provide any additional context for the Bug.

This change can be tested by adjusting the timeout settings on the success message component and observing user interactions to find the optimal display duration.

We are using const TOAST_REMOVE_DELAY = 1000000; in use-toast hook . Changing it to 3000 , (3 Seconds)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
i already opened an issue stating we want to remove this auth / signup feature in our website its not needed as of now
