### ISSUE TITLE
🚀 Feature: UI improvement

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#256]
### 🔖 Feature description

https://www.figma.com/design/QaVDc6blTKfbQHuATFHdEN/100xJobs---Redesign?node-id=3069-56788&t=8KWlqdOGjpHX2lUm-0

### 🎤 Why is this feature needed ?

UI IMPROVEMENTS FOR 100XJOBS

### ✌️ How do you aim to achieve this?

Landing page improvements

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by pratiiikkk** [comment]
assign me

**Comment by saketsingh0078** [comment]
can I also try ? @VineeTagarwaL-code

**Comment by Ameerjafar** [comment]
@pratiiikkk any help? 
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
pratik is assigned, you can contact him if he needs help etc etc

**Comment by VineeTagarwaL-code** [comment]
Looks good !

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code anything we should do for this issue?
