### ISSUE TITLE
🚀 Feature: User Profile Page with Integrated Scalable Storage

### ISSUE THREAD

**Issue by siddhu12980** [code100x/job-board#259]
### 🔖 Feature description

New Page for user Profile:

Profile Management: Users will be able to view and update their personal information, including setting their availability status (e.g., "Open to Work" or "Not Open to Work").

File Uploads: The feature will support uploading a profile picture and resume, allowing users to maintain an up-to-date and professional presence.

Status Management: A dedicated option will be available for users to toggle their work availability status.

**Schema Update: To support these functionalities, necessary updates to the existing schema will be required, ensuring seamless integration and data integrity within the system.**

### 🎤 Why is this feature needed ?

- Improved User Experience: Allows users to easily update their information such as profile picture, bio, and name in one place.

- Future Expansion: Provides a foundation to add more features to the profile page down the line.

### ✌️ How do you aim to achieve this?

I plan to implement storage using one of the following options:

[Vercel Blob](https://vercel.com/docs/storage/vercel-blob#vercel-blob): A scalable and cost-effective object storage service for static assets such as images, videos, and audio files.

Cloudflare R2 Bucket: Provides a key for each image or file upload, which can be used for easy retrieval.

Initially, we'll use one of these solutions and later consider migrating to an AWS S3 bucket if the need arises.

### 🔄️ Additional Information

![Screenshot from 2024-08-25 08-11-16](https://github.com/user-attachments/assets/fbc798e4-d114-4cc1-8c49-82102d1ca61b)

Should look like this!
I agree would be better if someone helped with design but this is used just to describe Feature.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by OmPanpatil** [comment]
May i please ask, if i am willing to contribute in it can you please assign it to me!

**Comment by siddhu12980** [comment]
I have seen in your profile that you have done some UI/UX can you design this profile page.I am not a moderator but I would like to work on this feature if approved.I will open another feature request feel free to go for that.

**Comment by VineeTagarwaL-code** [comment]
we wont be having any user profile as such, just simply come in look for jobs  and apply directly to the link provided by them
