### ISSUE TITLE
🚀 Feature: Signin using google and other platforms

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#260]
### 🔖 Feature description

Right now you can signin using only credentials, but we can add other signin methods

### 🎤 Why is this feature needed ?

You can login using google and other platforms 

### ✌️ How do you aim to achieve this?

I am using nextauth provides to do so

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by shivasankaran-18** [comment]
could you assign this issue to me

**Comment by VineeTagarwaL-code** [comment]
we wont be having any kind of signing, only for posting jobs we will have a paywall and some info thats it
