### ISSUE TITLE
🚀 Feature: Top Loader Bar

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#264]
### 🔖 Feature description

top loader bar to indicate loading of page

![Screenshot from 2024-08-25 11-18-03](https://github.com/user-attachments/assets/21ec2750-f56a-4e17-9e7c-95989237d4b8)

### 🎤 Why is this feature needed ?

When we navigate to pages, there is nothing to indicate loading, so it feels like nothing is happening

### ✌️ How do you aim to achieve this?

i will achieve this by applying nextjs-toploader package

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by IAmRiteshKoushik** [comment]
Hey, I would like to work on this issue. Is this open or is it being worked upon currently ?

**Comment by Paribesh01** [comment]
@IAmRiteshKoushik bro this issue is not reviewed by the @VineeTagarwaL-code, so don't open a pr before that, also I am willing to submit a pr

**Comment by IAmRiteshKoushik** [comment]
@Paribesh01 Ah, sorry bro. I was not exactly aware of how to contribute to this repo. Saw this as a low-hanging fruit so send a fix.

**Comment by Paribesh01** [comment]
No worries, can you close your pr, so that I can open mine
@IAmRiteshKoushik

**Comment by IAmRiteshKoushik** [comment]
Hey, can we co-author this PR ? I am sure we have similar code so how about we build on top of each other ?

**Comment by VineeTagarwaL-code** [comment]
@Paribesh01 open your pr

**Comment by Paribesh01** [comment]
@IAmRiteshKoushik 
ok
