### ISSUE TITLE
🚀 Feature: Pagination in Job  Application Submission

### ISSUE THREAD

**Issue by siddhu12980** [code100x/job-board#265]
### 🔖 Feature description

When a user clicks "Apply" for a specific job, they should be directed to a dedicated page containing the job description. On this page, users will have the ability to submit their resume and provide additional details such as their skills, certifications, connection links, and other relevant information.

### 🎤 Why is this feature needed ?

This feature is essential because recruiters need a concise and detailed overview of each applicant. By providing a dedicated space for users to submit their resume, skills, certifications, and other relevant information, we ensure that recruiters receive the necessary details to evaluate candidates effectively.

### ✌️ How do you aim to achieve this?

When a user clicks "Apply" on a job application, they will be redirected to a confirmation page containing details about the recruiter and the company. On this page, the applicant can submit their resume, contact information, and any other relevant details required for the application.

somewhat like this:
Along with field for userinfo
![Screenshot from 2024-08-25 21-17-30](https://github.com/user-attachments/assets/7284ceb4-ff40-43c3-899b-c4f25426d577)

### 🔄️ Additional Information

Visibility into each other’s details is essential. Users should see employer information and position requirements during the application process to ensure informed decisions.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by shivasankaran-18** [comment]
is this project contributions active...can you assign this issue to me?

**Comment by Satyam3245** [comment]
@siddhu12980 @shivasankaran-18 i think our database is not as much as dense as you shown in picture like education , skills , educational , industry type or more ?

**Comment by siddhu12980** [comment]
@Satyam3245  I am not suuggesting to populate entirely new DB or new schema , i simply mean when user click on apply that should go to page of Job and company Description  like : Salary, working hours, Skills , and task expections.
And , When user decide to apply on that job let user set contact info,social Links, skills i.e [ "skill 1","skill 2"] and resume .

without which i don't the whole job-board is  possible
Needless to say we do need to make some changes in user Schema 
to Handel Skills , Social Links and Key of Resume image/PDF

**Comment by Satyam3245** [comment]
@siddhu12980 please mention the @VineeTagarwaL-code for approval ?

**Comment by siddhu12980** [comment]
@VineeTagarwaL-code  Can you Please approve this Feature Request?  If approved can you assign it to me .
