### ISSUE TITLE
📦 [FEATURE]: add docker file for the project

### ISSUE THREAD

**Issue by SwetanshuSingh** [code100x/job-board#27]
We need to add a docker file for the project, which will help contributors to setup this project locally without any hassle

**Comment by pawann-2000** [comment]
I'll do this, assign this to me

**Comment by NishantCoder108** [comment]
Hi @SwetanshuSingh ,

can i work on this , can you assign me?

**Comment by SwetanshuSingh** [comment]
@pawann-2000 @NishantCoder108 This is up for grabs, you guys can work on it. The PR will be reviewed by the maintainers.

**Comment by Ameerjafar** [comment]
@SwetanshuSingh working on that

**Comment by Shubham-Kumar1** [comment]
@SwetanshuSingh added the Dockerfile and updated the instructions in README.md file to run in a container way.

**Comment by iharsh02** [comment]
![image](https://github.com/user-attachments/assets/868d7b1e-69de-48f5-9b14-fd825cbc0ded)

**Comment by VineeTagarwaL-code** [comment]
Great PR's reviewing every single one of them

**Comment by abhishek-shivale** [comment]
is it still open ??? @VineeTagarwaL-code

**Comment by SwetanshuSingh** [comment]
> is it still open ??? @VineeTagarwaL-code

I think there are many open PR's and one of them will get merged, you can look into other issues
