### ISSUE TITLE
✨ Improvement: Inconsistent code styling between condition check for navitem.tsx

### ISSUE THREAD

**Issue by Ashish-simpleCoder** [code100x/job-board#270]
### 📜 Description

- There is inconsistent code styling between condition check for navitem.tsx. As some conditions are wrapped in braces and other one is missing. So we can just wrap it in braces to make it consistent.

![image](https://github.com/user-attachments/assets/0dae9a4d-2a8f-4667-96c5-4796a4ac2b10)

### 👟 Reproduction steps

1. Head to the navitem.tsx file and see the provided screenshot.

### 👍 Expected behavior

- Just need to wrapped the highlighted code in red block provided in screenshot in braces.

### 📃 Provide any additional context for the Bug.

- I can create PR for this issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by rakshit0960** [comment]
can you assign it to me?

**Comment by Ashish-simpleCoder** [comment]
Yes @rakshit0960, just wrap the code in braces. Let's wait for the confirmation.
