### ISSUE TITLE
🚀 Feature: Create a Job Management Page for Admins

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/job-board#284]
### 🔖 Feature description

This feature request involves the creation of a dedicated job management page specifically for admins. On this page, admins will have full control over job postings, including the ability to view, edit, and delete existing jobs, as well as create new job postings. The page will be designed to ensure efficient and secure job management within the Job Board application.

### 🎤 Why is this feature needed ?

Currently, there is no specific page dedicated to job management for admins. The lack of such a page makes it difficult for admins to efficiently manage job postings. This feature is needed to centralize job management tasks, allowing admins to perform CRUD (Create, Read, Update, Delete) operations on job postings in a streamlined and user-friendly manner.

### In my use-case...

In the current situation, admins have limited capabilities, with no dedicated page to manage existing jobs. Adding this feature will simplify the process of managing job postings, improve navigation, and enhance the overall user experience for admins.

---

### ✌️ How do you aim to achieve this?

**Implementation Plan:**

1. **Create a New Admin-Only Job Management Page**: 
   - Design and develop a new page within the admin panel that will allow admins to manage job postings.
   
2. **Add CRUD Functionalities**:
   - Integrate functionalities that enable admins to view all jobs, edit job details, delete jobs, and create new jobs from this page.
   
3. **Ensure Secure Access**:
   - Implement authentication and authorization checks to ensure that only admins can access and perform actions on this page.

4. **UI/UX Enhancements**:
   - Ensure that the page design is consistent with the existing application UI and provides a seamless experience for admins.

### I want this feature to...

Allow admins to efficiently manage all aspects of job postings from a single, dedicated page, thereby improving the usability and functionality of the Job Board application.

---

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by kushwahramkumar2003** [comment]
@VineeTagarwaL-code please assign to me

**Comment by dev13-suthar** [comment]
@kushwahramkumar2003 admin should see all job posting on this page right??

**Comment by dev13-suthar** [comment]
@VineeTagarwaL-code Can u check this PR
