### ISSUE TITLE
🚀 Feature: Post a job

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#288]
### 🔖 Feature description

https://remotejobs.com/post

Build exactly like this, add a post to job feature and the flow should also be same 

change the schema to meet the needs etc 

### 🎤 Why is this feature needed ?

To allow for companies to come and post job 

### ✌️ How do you aim to achieve this?

By allowing people to contribute to it

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by DeepanshuMishraa** [comment]
can i try?

**Comment by SwetanshuSingh** [comment]
assign me

**Comment by anuragnegi000** [comment]
assign me

**Comment by pratiiikkk** [comment]
assign me  : /

**Comment by VineeTagarwaL-code** [comment]
i will give this issue to first time contributor and the one who first asked @DeepanshuMishraa go for it
