### ISSUE TITLE
✨ Improvement: Sync constants with db enums

### ISSUE THREAD

**Issue by aakash2330** [code100x/job-board#289]
### 📜 Description

Using enums / prisma types in the repo instead of repeating constants

### 👍 Expected behavior

keeping constants dry and in sync with DB

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
any updates ?

**Comment by aakash2330** [comment]
> any updates ?

#299

here
