### ISSUE TITLE
🛠️ [UPDATE]: improve responsiveness of the landing page & mobile nav menu 

### ISSUE THREAD

**Issue by SwetanshuSingh** [code100x/job-board#29]
The landing page needs to be responsive and we need to have a mobile nav menu, desktop navbar and mobile navbar can be kept as sperated components to avoid complexity. 

- Here is some references for the mobile nav menu: 
![image](https://github.com/user-attachments/assets/690c08bc-85b2-47f6-b730-147a0d738403)

The navmenu can be implemented using shacn's sheet component
https://ui.shadcn.com/docs/components/sheet

**Comment by Girishbari** [comment]
why separate we use one only, adding more navbars would increase the complexity

**Comment by Sahil-Gulihar** [comment]
can this be assigned to me?

**Comment by SwetanshuSingh** [comment]
> why separate we use one only, adding more navbars would increase the complexity

Would you rather have two components named Navar and MobileNavbar and render them conditionally depending on the screen size or you drill down all the unnecessary logic and styles in one file. I think the first approach is better.

As the mobile navbar does not have any shared logic with the desktop navbar, there is no need to keep them in a single file and bloat it. This will also make sure the code is more readable.

I hope this clears my approach :)

**Comment by YadlaMani** [comment]
@SwetanshuSingh I can work on this assign me this issue

**Comment by Satyajit-Sahoo45** [comment]
@SwetanshuSingh @VineeTagarwaL-code can I work on this issue?

**Comment by isrark005** [comment]
is any one working on this or i can pick this?

**Comment by NawinKumarSharma** [comment]
@SwetanshuSingh  can you review t=it? #40

**Comment by VineeTagarwaL-code** [comment]
@NawinKumarSharma PR is the best among all and one that is made the fastest, so will go with it thank you all
