### ISSUE TITLE
✨ Improvement: explore job page improvement

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#290]
### 📜 Description

if no job is present  show a fallback card and fix the navbar colliding with the search box 
![image](https://github.com/user-attachments/assets/6c58b22f-7e60-4861-82ee-2ee5b593ec29)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by lingaraj2020** [comment]
assign me

**Comment by anuragnegi000** [comment]
assign me

**Comment by lingaraj2020** [comment]
thank you

**Comment by VineeTagarwaL-code** [comment]
@lingaraj2020 updates ?

**Comment by lingaraj2020** [comment]
@VineeTagarwaL-code Solving it, 
it was my first issue, so it was taking a bit longer.

**Comment by anuragnegi000** [comment]
@VineeTagarwaL-code I noticed there hasn't been any activity on the project for the past week, and I would love to contribute. Please let me know 

Looking forward to your response!

**Comment by anuragnegi000** [comment]
> @VineeTagarwaL-code I noticed there hasn't been any activity on the project for the past week, and I would love to contribute. Please let me know
> 
> Looking forward to your response!

@VineeTagarwaL-code

**Comment by lingaraj2020** [comment]
hey @anuragnegi000 I've been unassigned, Feel free to start whenever you're ready.

**Comment by anuragnegi000** [comment]
sure i would like to work on this, assign me please
