### ISSUE TITLE
✨ Improvement: ui improvement for explore page

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#291]
### 📜 Description

Solve this responsiveness issues asap 

![Screen Shot 2024-08-31 at 15 44 46](https://github.com/user-attachments/assets/8a23586e-5199-4d9e-a73e-5a84226ec9da)
![Screen Shot 2024-08-31 at 15 44 13](https://github.com/user-attachments/assets/96e9740f-bd74-4228-82fe-0fef7b985d2a)
![image](https://github.com/user-attachments/assets/76915a5e-352b-474f-8a71-f04e02ae8359)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
![Screen Shot 2024-08-31 at 15 45 16](https://github.com/user-attachments/assets/942feeb4-a00c-4067-b89a-2fec725ffc07)

**Comment by anuragnegi000** [comment]
assign me

**Comment by pratiiikkk** [comment]
assign me

**Comment by toufiqfarhan0** [comment]
assigned people should have to work on this or anyone can??

**Comment by VineeTagarwaL-code** [comment]
@pratiiikkk whats the update ?

**Comment by pratiiikkk** [comment]
@VineeTagarwaL-code  already fix  and  merged 

Close this
