### ISSUE TITLE
✨ Improvement: Add scroll to top and improve navbar

### ISSUE THREAD

**Issue by vanshavenger** [code100x/job-board#296]
### 📜 Description

To add a scroll to top button that will help the user to smoothly scroll to top and improved navbar that will  be some blur and it will hide when user scroll down and show when user stop scrolling or scroll up,

Imrpoving the Create job page with better Ui and Ux, and revamp it to make it better and cleaner
@VineeTagarwaL-code 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by sidhuiwnl** [comment]
i like to work on this

**Comment by vanshavenger** [comment]
Assign me on this

**Comment by sidhuiwnl** [comment]
https://github.com/user-attachments/assets/7f23ad99-f8bb-4e70-bb43-cae3cb9fc899


I have implemented the scroll to top and navbar feature. can i add a pull request
