### ISSUE TITLE
🐛 Bug Report: Filters doesnt work in landing page 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#301]
### 📜 Description

[ Check the video recording out ] 
https://github.com/user-attachments/assets/0d59dc41-a209-4a99-8440-893d63aba76f

### 👟 Reproduction steps

Follow the video given above for ref

### 👍 Expected behavior

it should filter and show the data correctly 

### 👎 Actual Behavior with Screenshots

Given in the video 

### OS name

Linux

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Paribesh01** [comment]
Can I try

**Comment by kumawatkaran523** [comment]
Is someone working on this?
If not, can I try.....
