### ISSUE TITLE
✨ Improvement: UI improvement of /jobs page 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#303]
### 📜 Description

![image](https://github.com/user-attachments/assets/eae396f4-7e38-4d63-99ec-ea2623aced31)

### 👟 Reproduction steps

click on any job to view the jobs

### 👍 Expected behavior

https://remotejobs.com/job/61998421-945a-4e4d-b3bf-d036e5eb0350-growth-marketing-analyst-sem

build something like this, don't copy it wholely should be bearable enough to look at 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code assign me bro?

**Comment by Dark7177** [comment]
Assign me

**Comment by praneash2** [comment]
@VineeTagarwaL-code  can you assign me ill be starting to work on this

**Comment by Dark7177** [comment]
@VineeTagarwaL-code plz check the pr for integration

**Comment by VineeTagarwaL-code** [comment]
yeah checking

**Comment by VineeTagarwaL-code** [comment]
will open the issue again wtih new figma design soon
