### ISSUE TITLE
✨ Improvement: add create job button in the main landing page

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#304]
### 📜 Description

the button should redirect to  /create page 

![image](https://github.com/user-attachments/assets/a8fcb53e-abb1-4a7b-9272-f9fb5bb760c1)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Dark7177** [comment]
@VineeTagarwaL-code Assign me sir ji
