### ISSUE TITLE
🐛 Bug Report: Space is not getting registered in /create

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#305]
### 📜 Description

![image](https://github.com/user-attachments/assets/79faf645-45b6-4ecd-b21c-7126a34602f6)
![image](https://github.com/user-attachments/assets/dad2bc56-4624-4e66-b204-22e8da390b71)

### 👟 Reproduction steps

try to add space and then type, it wont get registered 

### 👍 Expected behavior

the space should get registered properly 

### 👎 Actual Behavior with Screenshots

given above 

### OS name

Linux

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by anuragnegi000** [comment]
assign me

**Comment by aniket-a** [comment]
Assign me
