### ISSUE TITLE
🚀 Feature: add razorpay payment integration 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#306]
### 🔖 Feature description

should have the same flow as of remotejobs

![image](https://github.com/user-attachments/assets/4eda12e1-401e-4f3d-bec2-b7103f46d334)

### 🎤 Why is this feature needed ?

To allow companies and get there jobs posted 

### ✌️ How do you aim to achieve this?

Via razorpay

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Suryansh777777** [comment]
assign me

**Comment by SwetanshuSingh** [comment]
assign me

**Comment by pratiiikkk** [comment]
assign me'

**Comment by anuragnegi000** [comment]
assign me

**Comment by ShivaBhattacharjee** [comment]
assign me

**Comment by developingright** [comment]
assign me

**Comment by kairveeehh** [comment]
Assign me

**Comment by ItsFlash10** [comment]
@VineeTagarwaL-code can please assign this to me, recently worked on it and have the code handy
