### ISSUE TITLE
✨ Improvement: add company image upload via s3

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#307]
### 📜 Description

![image](https://github.com/user-attachments/assets/0dd5c4b9-c91e-4957-acf4-7495a523a9c4)

### 👍 Expected behavior

get the image uploaded to s3 and then save the link in db 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by developingright** [comment]
assign me

**Comment by a-s-t-e-y-a** [comment]
I know you assign the issue to another geek , but in case it doesn't work out can you assign this issue to me

**Comment by Vidit-Jain2206** [comment]
assign me

**Comment by dev13-suthar** [comment]
i can work on this
