### ISSUE TITLE
🚀 Feature: GitHub summaries visible to recruiters for candidates applying to jobs

### ISSUE THREAD

**Issue by Divyanshu11011** [code100x/job-board#310]
### 🔖 Feature description

This feature fetches and displays detailed information about a candidate's GitHub repositories and contributions, offering a polished summary on the candidate's profile visible to recruiters. The summary provides recruiters with a clear, comprehensive view of the candidate's activity and expertise, including:

Total repositories where the candidate has contributed.
A visual contribution graph representing the candidate's activity over time.
A breakdown of languages and technologies related to the candidate’s contributions, highlighting their primary tech stack.
This helps recruiters quickly assess the candidate’s technical involvement and expertise.

### 🎤 Why is this feature needed ?

Recruiters often face the overwhelming task of manually reviewing each candidate's GitHub profile to assess their contributions, tech stack, and project involvement. This process can be time-consuming, especially when dealing with multiple candidates. By implementing a feature that summarizes a candidate's GitHub activity—highlighting key metrics such as total repositories, contribution history, and language breakdown—recruiters can quickly evaluate a candidate's technical expertise without having to sift through detailed GitHub pages.

For example, a recruiter looking to hire a front-end developer could instantly see that a candidate has contributed extensively to React-based repositories, with clear visualizations of their activity over time. This feature simplifies the candidate evaluation process, making it more efficient and data-driven.

### ✌️ How do you aim to achieve this?

The plan is to leverage the GitHub API to fetch relevant data from a user's GitHub account, including repository contributions, commit history, languages used, and more. Additionally, we will integrate an LLM (Large Language Model) to process this data and generate a concise, polished summary in the desired format. The final summary will be displayed in the recruiter's dashboard, presenting the candidate's contributions in an organized and visually appealing manner, making it easy for recruiters to assess the candidate's skills at a glance.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by KiranPolaki** [comment]
Can u work on this?

**Comment by Divyanshu11011** [comment]
@KiranPolaki yes i can

**Comment by Divyanshu11011** [comment]
@VineeTagarwaL-code @KiranPolaki can you assign this issue to me ?

**Comment by VineeTagarwaL-code** [comment]
we dont have a login system here, so this will be of no use tbh
