### ISSUE TITLE
🚀 Feature: Post a job form

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#316]
### 🔖 Feature description

take inspiration from remotejob.com 

### 🎤 Why is this feature needed ?

to allow peoples to come and post jobs and gigs

### ✌️ How do you aim to achieve this?

by adding the form 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by anuragnegi000** [comment]
assign me

**Comment by Ameerjafar** [comment]
Assign me sir

**Comment by toufiqfarhan0** [comment]
@anuragnegi000  @VineeTagarwaL-code  broo how many issues you'll get assigned mann give me atleat one

**Comment by ArpitBlagan** [comment]
I am also interested
