### ISSUE TITLE
✨ Improvement: Add scrollbar to the jobs page

### ISSUE THREAD

**Issue by Arafat-Shaikh** [code100x/job-board#319]
### 📜 Description

While scrolling through job listings, the selection options for categories, salary, and sort-by are moving out of view. To address this, a scrollbar should be added that scrolls through the job listings only, keeping the selection options fixed.
![Screenshot 2024-09-07 221442](https://github.com/user-attachments/assets/1f742a06-3e05-4771-8e1d-156d813163b6)

### 👍 Expected behavior

The functionality of the scrollbar should be implemented, but it should remain hidden to enhance the overall UI experience.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by sachan13harshit** [comment]
@Arafat-Shaikh please assign this issue to me
