### ISSUE TITLE
Chatbot Job Post Creator

### ISSUE THREAD

**Issue by Divyanshu11011** [code100x/job-board#324]
### 🔖 Feature description

A chatbot-based job posting creation system embedded in our website. Users can paste job descriptions, and the chatbot will create the job post automatically. If important information is missing, it will prompt the user to provide a complete description.

### 🎤 Why is this feature needed ?

Traditional form-based job posting is often tedious and manual. This chatbot system simplifies the process by:

Providing a user-friendly chat interface
Automatically creating job posts from pasted descriptions using LLM
Identifying and requesting missing important information
Streamlining the job posting creation process

### ✌️ How do you aim to achieve this?

- Develop a chat interface and integrate it into our website
- Utilize a Large Language Model to analyze job descriptions and create structured job posts
- Implement a system to identify missing important information
- Create prompts to request complete descriptions when information is lacking
- Integrate with the existing UI to trigger job publication once the post is complete

### 🔄️ Additional Information

This solution focuses on automating job post creation using a chatbot interface and LLM technology. The chatbot creates the post directly from the user's input, only intervening to request more information if necessary. Once complete, it seamlessly integrates with the existing UI to publish the job post.

![image](https://github.com/user-attachments/assets/949a9b71-b598-400c-b17f-4ba649c91048)
sequence diagram for Job Description Creation:

![image](https://github.com/user-attachments/assets/1c11a85e-64b5-4989-a1d0-ad93f66c36ba)
sequence diagram for the Missing Information Prompt scenario:

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Divyanshu11011** [comment]
@VineeTagarwaL-code can you assign this to me

**Comment by VineeTagarwaL-code** [comment]
to be honest this will be over engineering for a simple job board application

**Comment by Divyanshu11011** [comment]
> to be honest this will be over engineering for a simple job board application

fairly speaking , would just use the llm to extract the exact data- one would extract from the form and send it via payload to publish the job 😀 @VineeTagarwaL-code
