### ISSUE TITLE
✨ Improvement: Use Gmaps api instead of location enums

### ISSUE THREAD

**Issue by aakash2330** [code100x/job-board#325]
### 📜 Description

it'll remove the hardcode enum dependency

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by aakash2330** [comment]
@VineeTagarwaL-code can you assign me this .

**Comment by VineeTagarwaL-code** [comment]
any updates on this, quite important

**Comment by aakash2330** [comment]
> any updates on this, quite important

https://github.com/code100x/job-board/pull/339
