### ISSUE TITLE
🐛 Bug Report: header is not responsive

### ISSUE THREAD

**Issue by toufiqfarhan0** [code100x/job-board#332]
### 📜 Description

https://github.com/user-attachments/assets/8c055395-c52d-4d4e-8ba6-ae6bc8bfa0d8

### 👟 Reproduction steps

reduce the screen size 

### 👍 Expected behavior

https://github.com/user-attachments/assets/4f62b555-23c6-4a46-b040-b4bb9181dec6

### 👎 Actual Behavior with Screenshots

.

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aspired2001** [comment]
Please assign this issue to me

sir
@toufiqfarhan0

**Comment by toufiqfarhan0** [comment]
> Please assign this issue to me
> 
> sir @toufiqfarhan0

I have already raised PR #333
