### ISSUE TITLE
🚀 Bug:  validation message Fix

### ISSUE THREAD

**Issue by nolostra** [code100x/job-board#338]
### 🔖 Feature description

it will allow to post job posting for any cities with proper validation

### 🎤 Why is this feature needed ?

currently its only allowed for specific cities with any validation

### ✌️ How do you aim to achieve this?

we can use react-country-state-city fr getting all the cities and proper data with it

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
wait opening a proper one
