### ISSUE TITLE
[FEATURE]: add user profile page with DB schema

### ISSUE THREAD

**Issue by Saurav1509** [code100x/job-board#34]
Hi @VineeTagarwaL-code , We need to have a Profile page for users where they can update their information and for the same we need to have DB schema as well. I think we can create a schema like below. Please check and let me know if this is fine or something to be added? Assign this to me i will start working on same if it is fine.

![image](https://github.com/user-attachments/assets/25c5b080-e5a4-42df-9fe3-8950f926ef87)

**Comment by VineeTagarwaL-code** [comment]
Looks good and i think this is good enough for starting out
