### ISSUE TITLE
🚀 Feature: Env check 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#353]
### 🔖 Feature description

Add theo's env checker to make sure that app never starts without having all the required env var in .env

### 🎤 Why is this feature needed ?

to make sure, that new comers or in production we don't run into errors due to env being missing 

### ✌️ How do you aim to achieve this?

https://env.t3.gg/docs/nextjs , implement this libarary 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nolostra** [comment]
assign me

**Comment by VineeTagarwaL-code** [comment]
Go ahead @nolostra

**Comment by Gowtz** [comment]
Hi @VineeTagarwaL-code  is this issue open I am interested  and I fixed it

Without env

![WithEnv](https://github.com/user-attachments/assets/48f70ca1-7762-4be0-92d8-18de0127a1a8)


After env

![NoEnv](https://github.com/user-attachments/assets/338eca7d-c9d3-410b-a632-cf2316cac3ed)

I would like to contribute. Can i push PR

**Comment by VineeTagarwaL-code** [comment]
sorry @Gowtz only the person assigned can push the pr, you can look at other issues or create on of you own

**Comment by Gowtz** [comment]
Ok thank you

**Comment by VineeTagarwaL-code** [comment]
@nolostra any updates

**Comment by nolostra** [comment]
working on it @VineeTagarwaL-code
