### ISSUE TITLE
🐛 Bug Report: fix alignment issue + better form validation

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#354]
### 📜 Description

Things to add - 

 - proper validation message 
 - fix the alignment issues to make it look aligned throughout 

![image](https://github.com/user-attachments/assets/8d027be3-3f90-4956-825e-93a8de153dfa)
![image](https://github.com/user-attachments/assets/c46e5c06-da2f-4c92-aa31-ab1e1f4b23a8)
![image](https://github.com/user-attachments/assets/4657d6a7-18f3-4516-b252-c7d46dda91ce)

### 👟 Reproduction steps

go to /create

### 👍 Expected behavior

it should look good and aligned along with proper validation error texts 

### 👎 Actual Behavior with Screenshots

posted above 

### OS name

Linux

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Paribesh01** [comment]
Can I try

**Comment by VineeTagarwaL-code** [comment]
Sure man go ahead

**Comment by vikas-viki** [comment]
Can I give it a try still ?

**Comment by gitcuber369** [comment]
Can you assgine it to me?

**Comment by Aman0413** [comment]
Could you please assign to me ?
