### ISSUE TITLE
✨ Improvement: loading skeleton for jobs list

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#355]
### 📜 Description

Loading skeletons rather than loaders / spinners  wherever necessary 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Ashutoshpadhi629** [comment]
assign me @VineeTagarwaL-code

**Comment by DeepanshuMishraa** [comment]
@VineeTagarwaL-code  assign me sir

**Comment by VineeTagarwaL-code** [comment]
@Ashutoshpadhi629 assigned thanks !
