### ISSUE TITLE
🐛 Bug Report: Admin Page Ui: FirstName and LastName are not visible with Card color

### ISSUE THREAD

**Issue by dev13-suthar** [code100x/job-board#357]
### 📜 Description

on /admin page the UserCard component is not matching Theme, and First name and Last Name not visibe due to white BG,
![Screenshot 2024-09-17 110839](https://github.com/user-attachments/assets/9d06f453-f27b-4cd8-9b75-58c751af4d04)

### 👟 Reproduction steps

Go to /admin page.

### 👍 Expected behavior

The UserCard component should Match Our App theme and When we apply app Theme on UserCard the firstName and LastName will automatically appear.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-09-17 110839](https://github.com/user-attachments/assets/4e134ab9-8582-4d8a-8022-3c80602a24ec)

### OS name

Windows

### browser name

Chrome

### 📃 Provide any additional context for the Bug.

Good first Issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nolostra** [comment]
assign me

**Comment by Shubham0523** [comment]
can i try >?

**Comment by Gowtz** [comment]
Can I Do.
