### ISSUE TITLE
🚀 Feature: ui change for the each jobs page 

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#363]
### 🔖 Feature description

![Screenshot 2024-09-18 231232](https://github.com/user-attachments/assets/b3971cab-bd61-43ad-b94e-396de47ebcc1)

### 🎤 Why is this feature needed ?

right now, each jobs page doesn't show much details about the job, so we can change that

### ✌️ How do you aim to achieve this?

i have created ui for this in the image above

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
yeah sure go ahead

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code should i work on this? because you have created this issue - #368

**Comment by poswalsameer** [comment]
Hi @VineeTagarwaL-code, is anyone working on this? If no, I would like to start working on this issue!

**Comment by Paribesh01** [comment]
@poswalsameer almost done with this

**Comment by poswalsameer** [comment]
> @poswalsameer almost done with this



> @poswalsameer almost done with this

sure, thanks for replying.

**Comment by VineeTagarwaL-code** [comment]
sorry bro, a new figma design was posted and an pr has been opened for that, sadly cant accept this pr anymore
