### ISSUE TITLE
🚀 Feature: add link tags in the description so that if someone adds some link in description it’s clickable

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#365]
### 🔖 Feature description

add link tags in the description so that if someone adds some link in description it’s clickable in the react-quill or React Text Editor

### 🎤 Why is this feature needed ?

to allow posters to have clickable links in the description 

### ✌️ How do you aim to achieve this?

by integrating react-linkify https://linkify.js.org/docs/linkify-react.html

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by bishalbera** [comment]
Assign me this please
