### ISSUE TITLE
✨ Improvement: Implement Figma design

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#367]
### 📜 Description

https://www.figma.com/design/0Acu1rj33FPBuCzFnqDiyW/100xdevs-Working?node-id=7251-100257&node-type=section&t=SAe4yVIH8cO5ZSow-0

Implement this design

![image](https://github.com/user-attachments/assets/8b7b8676-0f6f-4ca9-b507-5748245e6ad4)

### 👟 Reproduction steps

go to jobs page and job page

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by nolostra** [comment]
assign me

**Comment by Ashutoshpadhi629** [comment]
Can I work on this @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
@nolostra cant you have a unmerged pr right now

**Comment by toufiqfarhan0** [comment]
can i aslo work on this ??
