### ISSUE TITLE
🚀 Feature: Implement job page figma design 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#368]
### 🔖 Feature description

https://www.figma.com/design/0Acu1rj33FPBuCzFnqDiyW/100xdevs-Working?node-id=28-7357&node-type=canvas&t=SAe4yVIH8cO5ZSow-0

![image](https://github.com/user-attachments/assets/427fc199-3f82-4b9c-a9b4-f01d24e266d3)

### 🎤 Why is this feature needed ?

for improvment 

### ✌️ How do you aim to achieve this?

.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by amanbairagi30** [comment]
assign\

**Comment by toufiqfarhan0** [comment]
@amanbairagi30 too quick @VineeTagarwaL-code can also work on this ?

**Comment by VineeTagarwaL-code** [comment]
talk w him

**Comment by amanbairagi30** [comment]
ser @VineeTagarwaL-code , how is this looking?
![image](https://github.com/user-attachments/assets/076f56cd-5dee-4ec1-8f9d-c88039188603)
![image](https://github.com/user-attachments/assets/0af24c6d-0788-4066-aa45-049cf3d4ec0d)

**Comment by priyankashah3107** [comment]
I Want to Contibute can u assign this task to me.

**Comment by amanbairagi30** [comment]
@toufiqfarhan0 and @priyankashah3107 , i have added the PR  which will resolves this issue , pleases check #374
