### ISSUE TITLE
🐛 Bug Report: FAQ section click event not triggering on entire question div

### ISSUE THREAD

**Issue by SATYAM1000** [code100x/job-board#369]
### 📜 Description

Description: There is an issue with the FAQ section where the user is only able to toggle the answer by clicking directly on the question text or the down arrow icon or clicking on the space between the question  and arrow. Ideally, the answer should be revealed when the user clicks anywhere within the entire div containing the question and the arrow. This would improve the user experience and make the FAQ section more intuitive.

### 👟 Reproduction steps

Navigate to the FAQ section.
Attempt to click anywhere in the area surrounding the question text or arrow (within the div container).
Notice that clicking only on the text or the down arrow toggles the answer, but clicking elsewhere within the div does not.

### 👍 Expected behavior

Clicking anywhere within the entire div should trigger the toggle for revealing the answer.

### 👎 Actual Behavior with Screenshots

The answer is only toggled when clicking directly on the question text or the arrow icon or the space between the question and the arrow icon.

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by SATYAM1000** [comment]
Please assign me this issue

**Comment by ManikantaMandala** [comment]
I think, there is no problem in [production website](https://staging.placements.100xdevs.com/)
but while testing in dev mode, the above issue is true right? @SATYAM1000

**Comment by SATYAM1000** [comment]
Yes this issue don't exist in production website
