### ISSUE TITLE
✨ Improvement: In Home page we can improve job-landing component

### ISSUE THREAD

**Issue by akhil3110** [code100x/job-board#371]
### 📜 Description

Currently job landing component on home page looks like 

![image](https://github.com/user-attachments/assets/a27af23c-6829-43a5-b012-2d78ac25613d)

Here the job having salary not disclosed  can be improved.
And job having salary not disclosed should not have per annum suffix. 

Instead We can display only not disclosed and also current size of text is quite big. 

![image](https://github.com/user-attachments/assets/3b34a796-3542-4be2-a3e8-70a27427d063)

### 👍 Expected behavior

Instead of the current design we can have this design.

![image](https://github.com/user-attachments/assets/aa0e7af9-8a7a-4d87-82f0-4e9dd2d4829c)

I think this looks better than the previous design.

![image](https://github.com/user-attachments/assets/b3f43ef4-312c-4f3c-908b-ad6439136fe1)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by emadellaloggia** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by akhil3110** [comment]
@VineeTagarwaL-code  I have already worked on this if you think this changes should be made I can raise a pr

**Comment by AbdulBasit2733** [comment]
Hi, I have design for this:
Can We Do this Check The Design Here : 
[Figma](https://www.figma.com/design/Afkt6DxM3p3Po29J0Nf5i7/Untitled?node-id=0-1&m=dev&t=JI8jYLJ7sBRJjVeT-1)

**Comment by tushar-agarwal7** [comment]
@VineeTagarwaL-code  plz assign this issue to me

**Comment by sachan13harshit** [comment]
@VineeTagarwaL-code plz assign this issue to me

**Comment by sarthaklaptop** [comment]
@VineeTagarwaL-code I can work on this. Please assign it to me.

**Comment by VineeTagarwaL-code** [comment]
a new figma design will drop soon here no worries keep an eye out for that
