### ISSUE TITLE
✨ Improvement: If the CTC of the job is not disclosed then it should not show "per annum" text in the job posting

### ISSUE THREAD

**Issue by poswalsameer** [code100x/job-board#376]
### 📜 Description

If the salary or CTC of any job is not disclosed, then the text "per annum" shouldn't be written.

SCREENSHOT:
![Screenshot (38)](https://github.com/user-attachments/assets/5d937967-e7a9-4f38-b3c9-59b849eb9c7e)

### 👟 Reproduction steps

1. Go to the landing page.
2. Search for any job title.
3. You will see multiple job posts without any salary or CTC but "per annum" is still written there.

### 👍 Expected behavior

There should be only "Not Disclosed" text.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by dhirajudhani** [comment]
Hi @poswalsameer  can you assign this to me I'll be happy to contribute

**Comment by krixh-03** [comment]
should i ask before i try to contribute??
