### ISSUE TITLE
✨ Improvement: landing page ui

### ISSUE THREAD

**Issue by ajeeshRS** [code100x/job-board#378]
### 📜 Description

I saw the landing page design on the figma @VineeTagarwaL-code  shared and went ahead and started building it, even though I didn’t ask if it was needed. I’ve almost finished the build—just a few things like the mobilenav,recently added jobs and some little tweaks left. Do we want to go with this design, or are we sticking with the current one?

https://github.com/user-attachments/assets/4934ad4b-7864-4e8e-8c54-476bf804e6ee

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by toufiqfarhan0** [comment]
TBH current design is better

**Comment by ajeeshRS** [comment]
Mobile navbar also done 


https://github.com/user-attachments/assets/d6cf3e0c-de6c-4229-b1ba-03ad744ae8d9


https://github.com/user-attachments/assets/f9760967-1c74-4617-8b18-3771c8b093bb


https://github.com/user-attachments/assets/433d8fce-a517-4055-b028-80132ad95d73

Hey @VineeTagarwaL-code ,Can you check this out ?

**Comment by VineeTagarwaL-code** [comment]
damm nice work, sneaky hahaha i was waiting for the other two ui pr to get merged first  looks clean but how in the job card section are you hardcoding it ? 

open a pr

**Comment by ajeeshRS** [comment]
yes ,the job card section is currently hardcoded,should i raise pr in current state or make the recently added jobs working and raise the pr ?

**Comment by VineeTagarwaL-code** [comment]
yeah
