### ISSUE TITLE
Feature: to make all the pages responsive

### ISSUE THREAD

**Issue by anuragnegi000** [code100x/job-board#38]
No pages are responsive as per the current scenario

Current situation:-

https://github.com/user-attachments/assets/e3dd3fe9-202f-4f39-bcb0-80c14e2845c3

Expected results:-

Pages should be responsive for smaller devices

**Comment by GUNGODD** [comment]
working on it ....

**Comment by anuragnegi000** [comment]
> working on it ....
okay go ahead

**Comment by VineeTagarwaL-code** [comment]
Great Issue and PR's will give priority to the ones who did the best and the first to open the PR
