### ISSUE TITLE
✨ Improvement: Instructions for Google maps api key setup in ReadMe is missing

### ISSUE THREAD

**Issue by anirudhj2000** [code100x/job-board#383]
### 📜 Description

I was trying to setup the project  and .env had "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" , and there are no instructions for setting up this key in the readme file

### 👟 Reproduction steps

1. Checkout the latest .env.example 
2. Checkout the ReadMe 

### 👍 Expected behavior

Updated Readme to include to include steps required to setup the "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
yeah it is thanks for pointing out, would you like to add it ?

**Comment by anirudhj2000** [comment]
Sure, assign it to me.
