### ISSUE TITLE
🚀 Feature: I want to implement Direct Messaging System for Job Seekers and Employers

### ISSUE THREAD

**Issue by VanshikaSabharwal** [code100x/job-board#386]
### 🔖 Feature description

This feature would allow:

1. Job Seekers: To send inquiries regarding job postings, ask follow-up questions after applying, and communicate with employers directly.
2. Employers: To receive questions from interested candidates, send interview details, and manage communication with applicants.
3. Faster communication and better experience for both employer and user/job seeker.

### 🎤 Why is this feature needed ?

This feature will streamline the hiring process by enabling quicker and more direct communication between job seekers and employers, reducing the delays and confusion often associated with email or third-party tools.

### ✌️ How do you aim to achieve this?

1. Database: To store and manage the messages persistently for future reference and querying.

2. Kafka: For load balancing, ensuring that the system can handle high traffic and message queues efficiently without overloading a single server.

3. WebSocket: For real-time communication between job seekers and employers, ensuring that messages are delivered instantly.

### 🔄️ Additional Information

I have worked on a chat app and i know that other messaging platforms may offer similar features, but this system will be designed specifically for seamless communication between job seekers and employers, providing better integration and an optimized experience. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VanshikaSabharwal** [comment]
Please allow me to work on this issue and kindly assign it to me so that i can start working on it. @hkirat

**Comment by VineeTagarwaL-code** [comment]
Hey @VanshikaSabharwal thanks for this idea, this sounds really cool to have but for now we dont think we need this in our project so we will be skipping this issue for now but for sure will keep this feature in mind if we need it in future will open an issue thanks !
