### ISSUE TITLE
🐛 Bug Report: UI is not responsive for post a job page

### ISSUE THREAD

**Issue by MeerUzairWasHere** [code100x/job-board#393]
### 📜 Description

UI is not responsive for post a job page

### 👟 Reproduction steps

go to create a job post on mobile

### 👍 Expected behavior

It should be responsive

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/fb677c38-ba4c-43be-9ca3-ad7d3a3d77be

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SupriyaGo** [comment]
Hi @VineeTagarwaL-code , please assign this issue to me. Thanks!!!

**Comment by MeerUzairWasHere** [comment]
> Hi @VineeTagarwaL-code , please assign this issue to me. Thanks!!!

😑 Code is merged.

**Comment by SupriyaGo** [comment]
> > Hi @VineeTagarwaL-code , please assign this issue to me. Thanks!!!
> 
> 😑 Code is merged.

Oops, it was open so thought it is not done yet!!
