### ISSUE TITLE
🐛 Bug Report: Add Margin Between Payment Section and Footer

### ISSUE THREAD

**Issue by omkar342** [code100x/job-board#395]
### 📜 Description

There is no margin or space between the payment section and the footer, which causes the layout to appear cramped. This affects the visual hierarchy and user experience, as the elements are too close to each other.
![job payment page](https://github.com/user-attachments/assets/d944bae5-8ddc-4e97-93a7-d95b4b53a598)

### 👟 Reproduction steps

Go to 'post a job' page.

### 👍 Expected behavior

A margin or padding should be added between the payment section and the footer, ensuring proper spacing for a cleaner, more aesthetically pleasing layout.

### 👎 Actual Behavior with Screenshots

![expected behaviour](https://github.com/user-attachments/assets/f8414dba-4acc-45b3-9937-cc4e009acbfd)

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by PPS-H** [comment]
I fixed this issue
