### ISSUE TITLE
✨ Improvement: should use the twitter testimonials in place of dummy ones

### ISSUE THREAD

**Issue by vatan45** [code100x/job-board#396]
### 📜 Description

the testimonials should be used fro the twitters, the tweets of people who get placed because of 100xdevs .

### 👟 Reproduction steps

1. landing page
2. testimonials

### 👍 Expected behavior

it should use the twitter testimonials

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
that's a great idea, go for it

**Comment by SahilLamba0008** [comment]
> that's a great idea, go for it

can i work on this too ?

**Comment by vatan45** [comment]
@VineeTagarwaL-code  done with the issue, raised a pr, review please
