### ISSUE TITLE
✨ Improvement: UI for job list items with undisclosed salary can be improved

### ISSUE THREAD

**Issue by EbrahimAfridi** [code100x/job-board#397]
### 📜 Description

The current UI for the job list items is not good for the text "not disclosed" The text should appear in a single row and not wrap around to the next line.

<img width="998" alt="Screenshot 2024-09-23 at 1 09 40 PM" src="https://github.com/user-attachments/assets/ec95110e-203b-4010-83a2-8fa3cd4fdc27">

### 👟 Reproduction steps

1. Goto the home screen and scroll down to the job listing
2. See the job listing with undisclosed salary

### 👍 Expected behavior

The text "Not Disclosed" should appear in a single row and not wrap around to the next line.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by EbrahimAfridi** [comment]
Assign me this issue.

**Comment by poswalsameer** [comment]
Hi, there's already a PR #377 merged with this same issue. You can have a look at it. Thanks!

**Comment by divu777** [comment]
Saw the PR , i think it still does show the "NOT DISCLOSED" ,  i will say just find a better way to display like use "—" or "N/A." instead of "NOT DISCLOSED" just change the line and push the same PR no ned to raise another one just for one liner thing.
 
![image_2024-10-17_055545099](https://github.com/user-attachments/assets/98220767-08ee-49d3-9839-e7bc37da7f26)

**Comment by poswalsameer** [comment]
> Saw the PR , i think it still does show the "NOT DISCLOSED" , i will say just find a better way to display like use "—" or "N/A." instead of "NOT DISCLOSED" just change the line and push the same PR no ned to raise another one just for one liner thing.
> 
> ![image_2024-10-17_055545099](https://private-user-images.githubusercontent.com/108476115/377268620-98220767-08ee-49d3-9839-e7bc37da7f26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTQxODQsIm5iZiI6MTcyOTE1Mzg4NCwicGF0aCI6Ii8xMDg0NzYxMTUvMzc3MjY4NjIwLTk4MjIwNzY3LTA4ZWUtNDlkMy05ODM5LWU3YmMzN2RhN2YyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwODMxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2EyY2QzODljNGUwYmFiMGY2MWE3NWJiMjhmODE2NjQzNmZmZTIwNTExZjFkZjc3NzM0YTZjMzg4YTAzN2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.49ehJYxtwsc6Vk9WSL3LCVEcqaXZ8RX5-EBgQ7GVS9k)

Nice idea, I will discuss this with the members of this repository, and if they allow, I will surely do that.

**Comment by VineeTagarwaL-code** [comment]
opening a new issue for this
