### ISSUE TITLE
Open-Source to Startup Initiative

### ISSUE THREAD

**Issue by Jayant818** [code100x/job-board#4]
Hi @hkirat,
I have an idea: instead of just contributing to open-source projects, why not form a team to build these projects, cohort members assigned to different projects? We could identify innovative solutions to real-world problems, develop them together, and then pitch these projects to investors. This approach has several benefits. if we get the funding we can scale the project. This, in turn, can lead to job creation, not only for our team members but also for others as we grow. Moreover, this process provides valuable experience in entrepreneurship, project management, and business development, which are essential skills in today's market. Additionally, successful projects can inspire others in the open-source community.

Also I have an idea that I want to build : A Decentralized Social media platform, only for chatting. This way no one can get blocked and share their ideas freely. For now I have named it, DecenTalk.

Looking to hear your thoughts on this

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Interested to join a team to build this project
