### ISSUE TITLE
🐛 Bug Report: Horizontal Overflow Scroll Activation on Desktop Screens

### ISSUE THREAD

**Issue by omkar342** [code100x/job-board#400]
### 📜 Description

On normal desktop screens, without inspecting, the website activates horizontal (x-axis) scrolling, indicating an overflow issue. This happens because the content's width is not being handled properly, causing it to exceed the viewport's width.

The overflow seems to be triggered by either an element or a container stretching beyond the intended width, likely due to incorrect CSS width or margin/padding settings.

### 👟 Reproduction steps

1. Open the website on a desktop screen without using inspect tools.

2. Scroll horizontally and observe the unintended x-axis scroll bar.

### 👍 Expected behavior

This is the expected behavior:- 

![overflow after](https://github.com/user-attachments/assets/fce031d9-47b3-4151-a643-e46fabb3a125)

### 👎 Actual Behavior with Screenshots

This is the current screenshot:-

![overflow before](https://github.com/user-attachments/assets/38fe27f5-4292-42da-a0a9-796030ea06c2)

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MeerUzairWasHere** [comment]
@VineeTagarwaL-code
