### ISSUE TITLE
🐛 Bug Report: Job Post

### ISSUE THREAD

**Issue by sarthakbiswas97** [code100x/job-board#404]
### 📜 Description

**On clicking Post a job it doesn't work properly.**

### 👟 Reproduction steps

1. Go to homepage.
2. Click on Post a job.
3. see the error.

### 👍 Expected behavior

Should redirect to create job post page

### 👎 Actual Behavior with Screenshots

<img width="968" alt="Screenshot 2024-09-25 at 12 45 54 PM" src="https://github.com/user-attachments/assets/6feddcbd-0a21-41e2-8001-3e6469243670">

### OS name

MacOS

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Glitch-arch** [comment]
Prisma generate fixed it for me

**Comment by sarthakbiswas97** [comment]
> Prisma generate fixed it for me

<img width="955" alt="Screenshot 2024-09-25 at 1 11 35 PM" src="https://github.com/user-attachments/assets/ad1c2237-2ea2-4a86-9746-c425112c95e2">

**Comment by sarthakbiswas97** [comment]
Can you help me with one thing

**Comment by Ashutoshpadhi629** [comment]
@sarthakbiswas97, make sure the DB is running and give the right credentials to the .env files. If you are not using docker. Take a db from Neon.tech or Avian.
