### ISSUE TITLE
🚀 Feature: Login form for job posters

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#409]
are these features still needs to be implemented?
![image](https://github.com/user-attachments/assets/a20e9eba-0727-4d65-906a-fc2fd5837a3d)
![image](https://github.com/user-attachments/assets/9348d6fc-087a-40f2-ba86-441450a6eb6b)

If yes, I would like work on it..!!

**Comment by AakashIND** [comment]
I would like to work on this with you @CuriousCoder00 :)

**Comment by imsamad** [comment]
https://github.com/code100x/job-board/pull/412

hi just raised a PR for this feature. Feel free to review it and add any enhancements on top of it if needed. Happy to collaborate.

**Comment by VineeTagarwaL-code** [comment]
use nextauth, loved all the things

**Comment by CuriousCoder00** [comment]
@imsamad Please merge/resolve conflictss

**Comment by CuriousCoder00** [comment]
@AakashIND Not in my hands now brother, i was waiting for it to be assigned tbh 😅😅
