### ISSUE TITLE
🐛 Bug Report: The apply button is not working at any job/internship position.

### ISSUE THREAD

**Issue by Suraj-kumar00** [code100x/job-board#411]
### 📜 Description

I went to several job/internship position pages like this one https://staging.placements.100xdevs.com/jobs/9 and found that the apply button is not redirecting to the page it was meant to be.
- The apply button is not working in Brave, chrome browser as I have these two in my system.
- After trying multiple times I was unable to click on the apply to and it was not redirecting to the company's page so that people can apply there for that particular position.

### 👟 Reproduction steps

1. Just to the https://staging.placements.100xdevs.com/
2. then got the jobs/internships section. (And by the way Internship section/page is also not working.
3. After you go to the job section you can click on any position to apply.
4. And there you can find you aren't able to apply https://staging.placements.100xdevs.com/jobs

### 👍 Expected behavior

The expected behavior is that the **apply button should work** so that people can apply for the position they want.
And the **Internships section/page also works** currently it's not working.

### 👎 Actual Behavior with Screenshots

This is the current behavior of the apply button at any job/internship position. It's **not redirecting** to that company's page to apply for the position.
![image](https://github.com/user-attachments/assets/8d169e70-1151-427a-a81e-563382ec4cf2)

### OS name

Linux

### browser name

Brave

### npm version

7.0.0

### node version

20.0.0

### 📃 Provide any additional context for the Bug.

I mean let's fix this one so that people including me also can apply for the position you have here!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MeerUzairWasHere** [comment]
@VineeTagarwaL-code  I can give it a try. I'm free on weekend. 😊

**Comment by CuriousCoder00** [comment]
I think this issue is becuase of there not being any kind of link or onClick handlers when clicking on the button, as it is dummy data for the development.
And as you can see in the screenshot that there will be a apply link when job poster posts a job
![image](https://github.com/user-attachments/assets/7ed336cd-1853-4611-a64d-10175da1feb8)


And most probably these links will be attached to there companies career pages

**Comment by CuriousCoder00** [comment]
Hope i'm not wrong @VineeTagarwaL-code

**Comment by Suraj-kumar00** [comment]
> Hope i'm not wrong @VineeTagarwaL-code

Hi @CuriousCoder00, that could be true I also thought that but I'm not sure whether these are dummy jobs/internship or real

**Comment by CuriousCoder00** [comment]
@Suraj-kumar00 i think these are the dummy ones

**Comment by VineeTagarwaL-code** [comment]
hi guys, its the dummy data for now, if we put the correct link it will work
