### ISSUE TITLE
🚀 Feature: Add a "Bookmark" button to job listings.

### ISSUE THREAD

**Issue by VanshikaSabharwal** [code100x/job-board#413]
### 🔖 Feature description

The Job Bookmarking feature allows users to bookmark job listings they are interested in, enabling them to easily revisit and apply later. Users can click a "Bookmark" button on job listings to save them, and these saved jobs will be displayed on the user's dashboard.

### 🎤 Why is this feature needed ?

The Job Bookmarking feature allows users to bookmark job listings they are interested in, enabling them to easily revisit and apply later. Users can click a "Bookmark" button on job listings to save them, and these saved jobs will be displayed on the user's dashboard.

### ✌️ How do you aim to achieve this?

To implement this feature, I will:

1.  Frontend: Add a bookmark button to each job listing. The button will toggle between "Bookmark" and "Remove Bookmark" based on the user's interaction. 

2.  Backend: Create a Prisma model relation between users and jobs to store bookmarked jobs.

3.   API: Develop an endpoint to handle the adding/removing of bookmarks.

4.   Dashboard: Create a section in the user dashboard that lists all bookmarked jobs.

### 🔄️ Additional Information

Alternative solutions could involve using browser storage (like local storage) to temporarily store bookmarks, but this wouldn't persist across devices or sessions. The proposed solution ensures that bookmarks are tied to user accounts, allowing access from any device.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VanshikaSabharwal** [comment]
@hkirat please assign me this issue.

**Comment by MeerUzairWasHere** [comment]
> @hkirat please assign me this issue.

@VineeTagarwaL-code is maintainer, ask him.

**Comment by VanshikaSabharwal** [comment]
By using cookies, I can store a persistent userId for users without requiring them to log in, and associate their bookmarks in the database with that ID. This allows bookmarks to be maintained across sessions and devices without a login system. In this way, I can implement the bookmark feature without needing users to sign up. @VineeTagarwaL-code . @CuriousCoder00

**Comment by CuriousCoder00** [comment]
@VanshikaSabharwal Cookies are specific to the browser and device, meaning users would have different user IDs for different devices or browsers unless you synchronize them somehow.
To make bookmarks to be accessible across multiple devices, cookies alone won't be enough, as cookies are device/browser-specific. You'd need a way to link different cookies or synchronize data between devices, possibly requiring a login system or another form of shared identifier.

**Comment by VanshikaSabharwal** [comment]
Implementing a login system would be a good choice, as it ensures the safety of all options. Otherwise, things could get complicated if we use a UUID in the URL or a QR code to sync devices. Is it okay to add a login system?  I will implement the login feature and then create a bookmark feature. @CuriousCoder00

**Comment by CuriousCoder00** [comment]
@VanshikaSabharwal Idk abt implementing the login workflow for users that are applying for the jobs, as 100xjobs is a platform where user come and apply for the job in his/her niche that the job poster has posted on the site.

On the other hand job poster will need to login to post a job on the site

That's all what i found in notion docs.. well gotta confirm with maintainers in comments here or discord.

**Comment by CuriousCoder00** [comment]
but as far as i'm aware they're not looking for login worklow with normal users

**Comment by VanshikaSabharwal** [comment]
We can do this:- 
 1.Generate and Store UUID: Upon the user's first visit, generate a UUID and store it in a cookie for unique identification.

 2. Bookmark Creation: When users create a bookmark, send the UUID along with the bookmark details to the server for storage.

 3. Server-Side Storage: The server saves bookmarks in a database, associating them with the user's UUID.

 4. Cross-Device Syncing: Users can access the application from different devices by entering their UUID, which can also be shared via a link or QR code.

 5. Set Cookie on New Device: After retrieving bookmarks on a new device, set the cookie with the same UUID to maintain access to the saved bookmarks.

**Comment by CuriousCoder00** [comment]
This will lead to a lot of security issues

**Comment by VanshikaSabharwal** [comment]
> This will lead to a lot of security issues

@CuriousCoder00  You are right. Did you confirm with maintainers about login workflow?

**Comment by divu777** [comment]
Why don't just have like login workflow only if the user wants to bookmark it , i don't see any other approach

**Comment by VanshikaSabharwal** [comment]
> Why don't just have like login workflow only if the user wants to bookmark it , i don't see any other approach

Yes, It would be good if we can we add user login workflow

**Comment by Kashyap1ankit** [comment]
@VineeTagarwaL-code /assign it to me .
