### ISSUE TITLE
✨ Improvement: Scroll needed in job filter

### ISSUE THREAD

**Issue by Adarsh9977** [code100x/job-board#414]
### 📜 Description

Scroll needed while applying filtering the jobs. Its height is very large according to window size.
<img width="1420" alt="Screenshot 2024-09-27 at 12 37 15 PM" src="https://github.com/user-attachments/assets/ca0c13b2-9a35-4695-8a77-009721cb96eb">

### 👍 Expected behavior

It has to be a fixed height and scroll when hover.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Adarsh9977** [comment]
@VineeTagarwaL-code  I am working on it. I think its needed.

**Comment by Adarsh9977** [comment]
After the changes

 
https://github.com/user-attachments/assets/f6a07194-61fe-48ed-a56f-b249fa808fad

**Comment by VineeTagarwaL-code** [comment]
you are at previous code

**Comment by Adarsh9977** [comment]
is this feature already added
