### ISSUE TITLE
✨ Improvement: Job detail page

### ISSUE THREAD

**Issue by Shu12388y** [code100x/job-board#417]
### 📜 Description

Improve the UI of the job detail page

@hkirat assign this issue to me I want to work on it

![Screenshot (12)](https://github.com/user-attachments/assets/457c9888-9413-4ae9-b643-ccff04f0ca85)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by VineeTagarwaL-code** [comment]
its done will be made live soon
