### ISSUE TITLE
🐛 Bug Report: company searching input field gets loaded the page when hit enter

### ISSUE THREAD

**Issue by Shu12388y** [code100x/job-board#418]
### 📜 Description

I have observed that when we are searching for a job on the home page and hit enter the page gets reloaded this should not happen

@hkirat assigned this issue to me 

### 👟 Reproduction steps

1. Go to landing page
2. search for the company
3. And hit enter
4. The page will reloaded

### 👍 Expected behavior

It should not reload the page just show up the list of companies

### 👎 Actual Behavior with Screenshots

![Screenshot (13)](https://github.com/user-attachments/assets/dbdac5ea-ffa5-480f-b0b5-1acfb4265292)

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
please pull main
