### ISSUE TITLE
🚀 Feature: Share your story 

### ISSUE THREAD

**Issue by Shu12388y** [code100x/job-board#419]
### 🔖 Feature description

Adding a Share Your Story page where people can share their story and stories

![Screenshot (15)](https://github.com/user-attachments/assets/6bf4e422-118e-42bf-b5e9-d7a9a151116f)

### 🎤 Why is this feature needed ?

As in 100x dev YouTube channel we are posting success stories and adding this feature we can also showcase it on the website also

### ✌️ How do you aim to achieve this?

We have to create a new API route for that and a user input form where users can post their stories and we can also auth so that only verified users can post.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CuriousCoder00** [comment]
@Shu12388y this is a nice one

**Comment by VineeTagarwaL-code** [comment]
will think about this and get back to you

**Comment by VineeTagarwaL-code** [comment]
we dont need this for now, thanks for the issue
