### ISSUE TITLE
📦 [FEATURE]: Add Custom Job Option for enterprises

### ISSUE THREAD

**Issue by Pheewww** [code100x/job-board#42]
Many Companies will be interested in contacting us for the following:
- They have lots of posts requirement so they need to discuss discount
- They want to hire through a Hackathon
- They want to hire from people coming to their code base and contributing to it.
- They want to contact us to discuss more hiring ideas/partner with us.

Another site remotejobs.com has these features, while regular job posting is suitable for many ppl, lot of them will be interested in discussing more about it.

for reference- when u click on post a job on remotejobs, u get
![image](https://github.com/user-attachments/assets/dbfa28aa-e3e3-4aca-acd3-2338ad43ecab)

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
