### ISSUE TITLE
🚀 Feature: Company details page 

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#420]
### 🔖 Feature description

Each company will have its own dedicated page where they can post information about their organization. 

### 🎤 Why is this feature needed ?

Currently, the admin has to manually input company details into every job post, which isn't efficient.

### ✌️ How do you aim to achieve this?

i will create a page where, admin can post there company info and user can see it, also i have make some changes in the schema to store company info in admin user

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
it is already there i believe

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code no its not there, since company posting job will have same details about there company, they did not need to fill them in every job posting form, they can only fill it once

**Comment by VineeTagarwaL-code** [comment]
didnt got you ?
