### ISSUE TITLE
🐛 Bug Report: Google Auth Error

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#426]
### 📜 Description

It leads to the Localhost url when using google providers to login or signup
It might be an issue with .env in production
> GOOGLE_CLIENT_ID=
> GOOGLE_CLIENT_SECRET=
or at the time of generating these credentials on the google console `Authorized redirect URIs` wasn't redirected to the production url

### 👟 Reproduction steps

1. Go to Login or signup page https://staging.placements.100xdevs.com/signup or https://staging.placements.100xdevs.com/signup 
2. try signing in with google
3. It redirectes you to http://localhost:3000/api/auth/error?error=OAuthCallback

### 👍 Expected behavior

 It should not redirecte you to http://localhost:3000/api/auth/error?error=OAuthCallback

### 👎 Actual Behavior with Screenshots

 It redirectes you to http://localhost:3000/api/auth/error?error=OAuthCallback on production

### OS name

Windows

### browser name

Chrome

### npm version

10

### node version

20

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by VanshikaSabharwal** [comment]
Hey @CuriousCoder00 If we are adding google auth then i can easily implement. #413 issue.

**Comment by VanshikaSabharwal** [comment]
Ohh i got it , auth is just for job poster.

**Comment by CuriousCoder00** [comment]
Yeah @VanshikaSabharwal

**Comment by VineeTagarwaL-code** [comment]
yep need to update the env, will be done by today

**Comment by CuriousCoder00** [comment]
Then closing this issue @VineeTagarwaL-code

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code There's still a issue when trying to login with google, It looks like there's redirect url is missing

![image](https://github.com/user-attachments/assets/a7e48ddf-72b6-4077-b252-93e6fa1667df)
