### ISSUE TITLE
🐛 Bug Report: ContactUs in other routes isn't working

### ISSUE THREAD

**Issue by durgaprasad118** [code100x/job-board#429]
### 📜 Description

The contact us is taking to the testinomials in the Home page but when I'm on the login page, or jobs page it isn't routing to the testinomials as expected.

https://github.com/user-attachments/assets/82f06d73-2eb7-4539-a0e2-fea27f812a08

### 👟 Reproduction steps

One way is using absolute URL `https://staging.placements.100xdevs.com/#testimonials`  on clicking the Contact us page that takes directly to home page

### 👍 Expected behavior

It should open the testimonials section in the home page

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/2d8c75d4-a256-4d73-98c7-cbe408d53103

### OS name

MacOS

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by CuriousCoder00** [comment]
I think there's not a contact form or anything else yet... @VineeTagarwaL-code if it's needed I'd like to work on it.
Please can you assign it to me?

**Comment by durgaprasad118** [comment]
Yeah there isn't any contac form the contact us is linked to testinomials.

**Comment by VineeTagarwaL-code** [comment]
for rather than a contact form, add the logic where it opens up the email to vineetagarwal.now@gmail.com for now

**Comment by CuriousCoder00** [comment]
so there's no need to create new components or anything? just redirect to opening email @VineeTagarwaL-code
