### ISSUE TITLE
🚀 Feature: Company Details Management for Job Posters

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#430]
### 🔖 Feature description

This feature will enable job posters to save their company information after their first job post, so they don't need to re-enter the same details every time they post a new job. It will enhance the user experience by making job posting faster and more efficient.

### 🎤 Why is this feature needed ?

This feature will significantly improve the efficiency of job posting for users who frequently post jobs for the same company or multiple companies.

Benefits:
Reduces redundant data entry, improving the user experience.
Helps maintain consistency in company information across multiple job posts.
Allows for flexible management of multiple company profiles.

### ✌️ How do you aim to achieve this?

After logging in, the job poster will be presented with a form to submit their company details if they are posting a job for the first time.
The form will include fields like:
Company Name
Company Address
Website URL
Contact Email/Phone
Other relevant company details
Reuse of Previous Company Details:

If the job poster has posted jobs before, they should be able to select from the previously entered companies.
A dropdown or selection box will be provided to choose one of the previously used companies.
If the job poster is posting for a new company, they can fill out the form again, and the details will be stored for future use.

The company details will be saved in the user’s profile.
Each time the user posts a job, the form will automatically pull the previously stored company details if they exist.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CuriousCoder00** [comment]
Can you assing it to me? @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
yes thats good

**Comment by Paribesh01** [comment]
Hey @CuriousCoder00, if you're not working on this, can I take over?

**Comment by CuriousCoder00** [comment]
@Paribesh01 working on it.. if you want can work on it together

**Comment by Paribesh01** [comment]
@CuriousCoder00 that works for me.

**Comment by CuriousCoder00** [comment]
then i'll open a draft pr you can continue from there @Paribesh01

**Comment by Paribesh01** [comment]
@CuriousCoder00 ok

**Comment by VineeTagarwaL-code** [comment]
paribesh seems to be close to completing this will be closing this issue as one more like this is already opened

:rocket:
