### ISSUE TITLE
🚀 Feature: Add Contact Us page 

### ISSUE THREAD

**Issue by DeepanshuMishraa** [code100x/job-board#432]
### 🔖 Feature description

Add a contact us page along with its api route to send email to the admin using smtp

### 🎤 Why is this feature needed ?

This feature is necessary to facilitate seamless communication between users and the web admin, particularly for addressing issues or submitting queries. 

### ✌️ How do you aim to achieve this?

 - By creating a decent UI where users can submit their name along with their message 
 - By creating an api route that allows people to send the messages using smtp

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by DeepanshuMishraa** [comment]
@VineeTagarwaL-code  can i work on this?

**Comment by CuriousCoder00** [comment]
It was mentioned here.. 
#429
