### ISSUE TITLE
🐛 Bug Report: Post job form is being accessed by admin only

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#433]
### 📜 Description

The "Post Job" form is currently only accessible by the admin, but it should be accessible by both the job poster and the admin.

### 👟 Reproduction steps

1. Login
2. Go to `/create` or `Post a job`
3. Try accessing it as a job poster.
4. If you're admin then it's accessible by you, if not then it's not accessible

### 👍 Expected behavior

The "Post Job" form should be accessible by both the admin and the job poster.

### 👎 Actual Behavior with Screenshots

The form is only accessible by the admin.
Logged in with user credentials as Job poster: 
![image](https://github.com/user-attachments/assets/e6ed03c2-55c7-4c0d-84ca-ca9d7a0984a8)
Logged in with admin credentials
![image](https://github.com/user-attachments/assets/c957f2dd-a256-45a9-88f2-e983d1bcfff1)

### OS name

Windows

### browser name

Chrome

### npm version

10

### node version

20

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code I would love to work on it. please assign it to me.

**Comment by VineeTagarwaL-code** [comment]
yes that is how it is meant to be for v1, thanks for the issue
