### ISSUE TITLE
🚀 Feature: User profile page

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#434]
### 🔖 Feature description

User profile page to manage all the details such as current company, current company details etc.

### 🎤 Why is this feature needed ?

For better user experience it is good to have a profile page where user can see all the information and update them respectively in one place

### ✌️ How do you aim to achieve this?

Creating a user profile page with sub routes for better user experience

Example screenshot
![Screenshot 2024-09-30 140957](https://github.com/user-attachments/assets/0cd3a62d-85a2-4578-a4d1-9763d30c520f)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CuriousCoder00** [comment]
assign please..!!

**Comment by VineeTagarwaL-code** [comment]
need to make a little bit better ui to match our current design but great work

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code yes, this was js an example not the actual design

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code should i continue with this design?
![image](https://github.com/user-attachments/assets/d3046e64-0e5e-4ebf-a59f-1b394a5448ec)

**Comment by VineeTagarwaL-code** [comment]
looks good, remove jobs center and applications for now, we will need this in v2

**Comment by VineeTagarwaL-code** [comment]
just edit profile, account setting are good, what options are putting there in account settings ?

**Comment by CuriousCoder00** [comment]
> looks good, remove jobs center and applications for now, we will need this in v2

Sure



> just edit profile, account setting are good, what options are putting there in account settings ?

like delete account or deactivate

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code also can you confirm with which design should i move forward?
1. 
![image](https://github.com/user-attachments/assets/1f94afb9-952e-4b56-82cd-3f6f35931ae3)
2.
![image](https://github.com/user-attachments/assets/8dd6d96e-1eb5-4cfd-960d-4c73a916251b)

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code I've raised an PR. Please review it and tell me if there are any changes needed.
