### ISSUE TITLE
✨ Improvement: Landing page responsiveness 

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#435]
### 📜 Description

Landing page is not fully responsive, it is breaking the layout
![image](https://github.com/user-attachments/assets/97366768-4383-4994-bc77-61bf70395dfe)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by CuriousCoder00** [comment]
assign please

**Comment by VineeTagarwaL-code** [comment]
its done  i pushed this, cause it was looking bad
