### ISSUE TITLE
🚀 Feature: Add Input Field for Skills Tags in Job Creation Form

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#436]
### 🔖 Feature description

Adding an input field for skills tags will improve the job posting process and make job listings more informative.

### 🎤 Why is this feature needed ?

 Currently, while creating a job post, there is no input field to add skills tags.

### ✌️ How do you aim to achieve this?

i will add a filed where admin can add skills tags, 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
its already being done by other person
