### ISSUE TITLE
✨ Improvement: toaster for manage profile

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#437]
### 📜 Description

A little toaster that says "coming soon" when clicked on manage profile on the profile dropdown 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by vatan45** [comment]
can i take this sir .....? assign please

**Comment by SwarnenduG07** [comment]
Can I work on this

**Comment by vatan45** [comment]
@VineeTagarwaL-code  done with the issue

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code Is this issue still there?
