### ISSUE TITLE
🚀 Feature: New Loading ui for the jobs and job page 

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#438]
### 🔖 Feature description

![Screenshot 2024-10-03 005728](https://github.com/user-attachments/assets/0e49df00-7fa6-44e0-b11d-9cfed22ba0f9)

![Screenshot 2024-10-03 010126](https://github.com/user-attachments/assets/997795af-c8f5-45da-bbfd-8265676f178d)

i can implement it in both dark and light mode

### 🎤 Why is this feature needed ?

current loading ui for the old ui

### ✌️ How do you aim to achieve this?

i have created ui for this in image above

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awesome-pro** [comment]
@Paribesh01  Most probably you will see a PR resolving this issue by morning ✨

**Comment by wraith2009** [comment]
can i work on it . if no one is working?
