### ISSUE TITLE
🐛 Bug Report: Prisma Error shown in toast 

### ISSUE THREAD

**Issue by Suksham-sharma** [code100x/job-board#441]
### 📜 Description

When i tried to login , using Appxdevs creds , i got a toast , which showed prisma error . It should be a more user friendly form .
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3f7858a8-1c5c-482a-8039-c4a344f2d6ac">

### 👟 Reproduction steps

Try to sign In -> Error is toast (if user not found) 

### 👍 Expected behavior

It shouldn't display , the complex error , and should give more readable form 

### 👎 Actual Behavior with Screenshots

Should be a more readable form .

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aakash2330** [comment]
it could be that you haven't migrated to latest schema changes , can you try doing that ?

**Comment by Suksham-sharma** [comment]
I'm facing these on the deployed site , not on local

**Comment by VineeTagarwaL-code** [comment]
will be solved soon
