### ISSUE TITLE
🐛 Bug Report: User Sign Up error .

### ISSUE THREAD

**Issue by Suksham-sharma** [code100x/job-board#442]
### 📜 Description

Unable to Sign Up , Internal Server Error 
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/c8c123b9-e301-424c-8127-34a747f36463">

### 👟 Reproduction steps

Tried Sign - up , unable to do that , Internal Server errror .

### 👍 Expected behavior

It should create a user account , and proceed to the dashboard 

### 👎 Actual Behavior with Screenshots

It gave internal Server error . 

### OS name

MacOS

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by aakash2330** [comment]
have you used correct env's and is your db synced ?

**Comment by Suksham-sharma** [comment]
facing this on the deployed version .

**Comment by aakash2330** [comment]
yeah , the production is kinda bugged rn , we'll be fixing it soon .

**Comment by poswalsameer** [comment]
Hi @aakash2330, can you assign this to me or should I directly start working on this?

**Comment by VineeTagarwaL-code** [comment]
hey guys the prod is bugged will fix it soon on worries

**Comment by poswalsameer** [comment]
> hey guys the prod is bugged will fix it soon on worries

no worries!
