### ISSUE TITLE
🐛 Bug Report: getting `TypeError: Unknown file extension ".ts"` error while setting up the project locally

### ISSUE THREAD

**Issue by apsinghdev** [code100x/job-board#444]
### 📜 Description

When we setup the project locally and run `npm run db:seed` command, we get this error `TypeError: Unknown file extension ".ts" for /Users/ajeetpratapsingh/Developer/os/job-board/prisma/seed.ts`

### 👟 Reproduction steps

1. cd into the root directory
2. run `npm install`
3. run `npm run db:seed`

### 👍 Expected behavior

Ideally, it should seed the data successfully.

### 👎 Actual Behavior with Screenshots

<img width="1094" alt="Screenshot 2024-10-03 at 4 32 15 PM" src="https://github.com/user-attachments/assets/20c0ac71-ce99-4afb-ba0f-bc8a5896deee">

### OS name

MacOS

### browser name

Chrome

### npm version

10.8.3

### node version

22.9.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by apsinghdev** [comment]
@VineeTagarwaL-code can I please get it assigned?

**Comment by apsinghdev** [comment]
If I change the extension of seed.ts file to `.js` and change the `seed` command to use `esm`, it successfully seeds the db with a warning error
<img width="1152" alt="Screenshot 2024-10-03 at 5 16 06 PM" src="https://github.com/user-attachments/assets/ca4c3e46-4151-417b-b993-4678e13ea555">

Probably need a bit of tinkering to fix it.

**Comment by Suksham-sharma** [comment]
facing the same issue too . woks  on docker , but the issue arises there too , but it crashes on local .

**Comment by CuriousCoder00** [comment]
this happens because you can't compile TS when it's set to commonjs and changing the format to `.js` gives a warning error
You can also use `tsx` instead of `ts-node`
ALthough this solution is temp

**Comment by VineeTagarwaL-code** [comment]
if anyone wants to fix this, just opt will assign

**Comment by CuriousCoder00** [comment]
We can fix this with adding tsx in dev dependency and changing the seed value to tsx seed.ts in prisma object in package.json file

**Comment by VineeTagarwaL-code** [comment]
@CuriousCoder00 open a pr then

**Comment by VineeTagarwaL-code** [comment]
will assign apsinghdev as he asked first

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code ofcourse
