### ISSUE TITLE
🚀 Feature:  Bulk Upload Feature

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#445]
### 🔖 Feature description

allow users (job posters) to upload multiple job postings at once via a CSV or Excel file.

### 🎤 Why is this feature needed ?

 This feature should make it easier for job posters to manage large numbers of job postings efficiently.

### ✌️ How do you aim to achieve this?

i will create a input field for bulk upload, then i will parse the excel or csv file and will upload it in db

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code can i work on this

**Comment by akshatg5** [comment]
@VineeTagarwaL-code Can I start working on this?

**Comment by SahilLamba0008** [comment]
Can I work on this as well @VineeTagarwaL-code ?

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code i think #430 have to merge before this to work

**Comment by VineeTagarwaL-code** [comment]
let me think about this and then get back to you, obviously a good pr but right now ned a working admin dashboard

**Comment by SupriyaGo** [comment]
Hi @VineeTagarwaL-code, can you please assign this to me? I find lots of learning from this task and it will be my first contribution. Thanks !!

**Comment by VineeTagarwaL-code** [comment]
for now this feature is not needed pick other ones

**Comment by SupriyaGo** [comment]
Thanks @VineeTagarwaL-code
