### ISSUE TITLE
🐛 Bug Report: Multiple H1 Tags on Home Page

### ISSUE THREAD

**Issue by Anurag-Kochar-1** [code100x/job-board#449]
### 📜 Description

There are multiple `<h1>` tags on the home page. One is being used for the hero section, while others are incorrectly applied to section titles.

### 👟 Reproduction steps

1. Open the browser's developer tools.
2. Navigate to the "Elements" tab.
3. Search for `<h1>` tags by using the shortcut `Ctrl + F` and typing `<h1>`

### 👍 Expected behavior

There should be only one `<h1>` tag on the home page (for the hero section). Other section titles should use `<h2>` heading tags.

### 👎 Actual Behavior with Screenshots

Multiple `<h1>` tags are present on the home page
![image](https://github.com/user-attachments/assets/c8a732dd-1a1b-4638-a9fb-0eb23fe92de2)

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
great find go ahead
