### ISSUE TITLE
✨ Improvement: Cosmetic fixes

### ISSUE THREAD

**Issue by CyberSpyderX** [code100x/job-board#452]
### 📜 Description

Suggestions for cosmetic improvements (with screenshots for current build):

1. Separator for the final job filter accordion item: The UI would look cleaner without the last separator in the job filters div
![Screenshot 2024-10-04 125156](https://github.com/user-attachments/assets/fd3c6672-4b9e-4859-a9de-601664ad5c61)

2. Pointer cursor for filter text: The cursor should be pointer when hovered over the filter text (i.e. Full Time, Part Time etc.) to make it more visually engaging. We can also highlight the checkbox when it is hovered over.

3. Better text formatting for recommended job cards: We can follow the text formatting similar to the formatting in job cards in /jobs page i.e. space between location and work type, capitalized first letter for work type
![Screenshot 2024-10-04 132219](https://github.com/user-attachments/assets/aba8a287-ccff-4d74-8612-d12cee8ed450)

4. No scrollbars in job cards: We can remove the scrollbars for job cards as they already adapt to window resizing.
![image](https://github.com/user-attachments/assets/486df0b7-805f-470e-9132-24bfe641d5f6)

5. Icons for undisclosed attributes: We can keep the icons even when some attributes are not disclosed to better convey what metrics are missing from the job post. We can use different shades to indicate the unavailability of a metric.
![image](https://github.com/user-attachments/assets/57008a8b-760c-40f0-9fb2-4486ef05ff51)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by CyberSpyderX** [comment]
@VineeTagarwaL-code @aakash2330 Could you please advise on what fixes to focus on and which ones to discard?

**Comment by VineeTagarwaL-code** [comment]
yes do that, tag me @aakash2330 is not a maintainer
