### ISSUE TITLE
✨ Improvement: The testimonial cards are not looking consistent

### ISSUE THREAD

**Issue by NawinKumarSharma** [code100x/job-board#459]
### 📜 Description

![image](https://github.com/user-attachments/assets/4521a3e1-744a-48f1-b7e3-e140ae60471a)

### 👟 Reproduction steps

1. go to landing page and scroll to testimonial section

### 👍 Expected behavior

revove the empty card

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by NawinKumarSharma** [comment]
@VineeTagarwaL-code , is it necessary to show empty testimonials on main landing page? some of the testimonial cards are empty which makes the user confused with their own internet stability or something wrong. can i improve the testimonial cards? if yes plz, assign me?
![image](https://github.com/user-attachments/assets/7e2adfdb-6a66-45b7-b982-6ee19588bccd)

**Comment by VineeTagarwaL-code** [comment]
Go ahead work on it
