### ISSUE TITLE
🚀 Feature: Add HR role 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#463]
### 🔖 Feature description

add HR role so that they are also able to post job

### 🎤 Why is this feature needed ?

To allow HR to come and post jobs

### ✌️ How do you aim to achieve this?

By adding the functinality for it

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nolostra** [comment]
assign me
