### ISSUE TITLE
🐛 Bug Report: overflow issue

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#464]
### 📜 Description

![Screen Shot 2024-10-06 at 20 37 48](https://github.com/user-attachments/assets/bbed5233-b44e-4bfc-a798-b4090d021133)

### 👟 Reproduction steps

go to landing page in mobile view

### 👍 Expected behavior

should be fit in the screen

### 👎 Actual Behavior with Screenshots

https://github.com/code100x/job-board/pull/300

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by wraith2009** [comment]
Assign me sir
