### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#465]
### 📜 Description

![image](https://github.com/user-attachments/assets/c8cf7bd2-10ce-458a-8c61-6777697a581d)

### 👟 Reproduction steps

![image](https://github.com/user-attachments/assets/4ffd4c3d-cad0-477a-94e1-3f96d7245738)

### 👍 Expected behavior

should be consistent in height

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/e7a6e5e9-5fc2-4c6e-bd49-7a901c842552)

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by pratiiikkk** [comment]
assign
