### ISSUE TITLE
⭐ [IMPROVEMENT]  : Landing Page Design upgrade 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#47]
# Enhance Homepage Design with Centered Content, Improved Footer, and Framer Motion Animations

## Description
We need to improve the overall design of our homepage to make it more visually appealing. The current design leaves too much empty space, and the footer needs enhancement. Additionally, we should add animations using Framer Motion to bring more life to the page.

## Tasks
1. **Center the content**:
    - Ensure the content remains responsive and looks good on various screen sizes.

2. **Fill the empty space**:
    - Add a background pattern or gradient to the page to make it visually appealing.
    - Consider adding subtle decorative elements to the background.

3. **Enhance the footer**:
    - Improve the footer design with better typography and layout.
    - Add social media icons with links, make it look good
    - Ensure the footer design is consistent with the overall theme of the page.

4. **Add animations using Framer Motion**:
    - Implement smooth animations for the main content as it loads.
    - Add interactive animations to buttons and links.
    - Ensure animations are subtle and enhance the user experience without being distracting.

## Additional Context
- Current design screenshot is attached for reference.
- Ensure all new design elements are consistent with our brand guidelines.
- Test the new design on various devices and screen sizes to ensure responsiveness.

## Pull Request Context
This issue will be handled on a first-come, first-serve basis. We will not assign or lock this issue to any specific contributor. The pull request (PR) that comprehensively addresses all the listed tasks and ensures that every aspect is completed will be reviewed and merged.

- Please make sure to reference this issue in your PR.
- Ensure your changes are well-tested and do not introduce any new issues.
- Include screenshots or screen recordings of the updated design.
- Follow our contribution guidelines and code style.

Good luck, and thank you for your contribution!
## Current Design
![image](https://github.com/user-attachments/assets/59afbbe5-b6f2-4704-bf4e-fb1520072567)

**Comment by mayank2130** [comment]
Do you think this landing page is a good starting point? 
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/69c71608-f564-482b-97ef-82dc460c0704">
@VineeTagarwaL-code

**Comment by SwetanshuSingh** [comment]
> Do you think this landing page is a good starting point? <img alt="image" width="1264" src="https://private-user-images.githubusercontent.com/124957319/355606532-69c71608-f564-482b-97ef-82dc460c0704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTg0NDYsIm5iZiI6MTcyMjk5ODE0NiwicGF0aCI6Ii8xMjQ5NTczMTkvMzU1NjA2NTMyLTY5YzcxNjA4LWY1NjQtNDgyYi05N2VmLTgyZGM0NjBjMDcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwMjM1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDFlZTQ5NjdmZThiY2UzMGQ3MzY1MTQzY2ZhYWM2MjEyZTYwZDQ1MTcxODQ4NWQ0NmViMjEyOGM1YmY0ZTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZKS45rtKoG0cTmOz9PaOi4DQwpXqjuyYHPDLG1DXMWI"> @VineeTagarwaL-code

Don't the change the original design, enhance that one. There is a reason we are following this design and please try to keep it mimilistic

**Comment by mayank2130** [comment]
Looks way neat.
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/2ffc2f37-ec13-42ed-b5cf-844e453315c2">

**Comment by mayank2130** [comment]
Hey @VineeTagarwaL-code, implemented framer motion as well if it looks fine, happy to create a PR.

https://github.com/user-attachments/assets/e9cb30e8-a1d9-414b-89b7-81361b9998b7

**Comment by AxBwal** [comment]
Added footer for landing page and for all other pages too . @VineeTagarwaL-code  .
Here is the PR ; - https://github.com/code100x/job-board/pull/64
![Screenshot 2024-08-07 120350](https://github.com/user-attachments/assets/a70091cb-7d72-46d8-a7d8-44a62983d67b)

**Comment by Harit007x** [comment]
As you mentioned above Swetanshu, I tried to keep the original design approach and improved on the other key elements of the design. Kept it both minimal and appealing.

My PR : https://github.com/code100x/job-board/pull/69

https://github.com/user-attachments/assets/3c620174-cd09-4474-bbad-d7513b329f22

Let me know your thoughts on these, any feedback would be appreciated.
@SwetanshuSingh @VineeTagarwaL-code

**Comment by NawinKumarSharma** [comment]
Hey, I was also working on the same issue.
@SwetanshuSingh , can i proceed and raise a pr?
![image](https://github.com/user-attachments/assets/b4302568-f101-4fe8-9da1-bbdce36e55b9)

**Comment by NawinKumarSharma** [comment]
@VineeTagarwaL-code can you review my PR #76 ?

**Comment by VineeTagarwaL-code** [comment]
@mayank2130 Great PR merged !

**Comment by VineeTagarwaL-code** [comment]
@Harit007x , Great PR merged
