### ISSUE TITLE
🐛 Bug Report: Docker Compose fails with "target stage 'development' could not be found"

### ISSUE THREAD

**Issue by RutamBhagat** [code100x/job-board#470]
### 📜 Description

When running the command docker compose up --build, I encountered an error stating that the target stage "development" could not be found in the Dockerfile.

![image](https://github.com/user-attachments/assets/e0d6bad8-0ece-4afd-97de-5c59beed5a13)

### 👟 Reproduction steps

1. Navigate to the project directory root.
2. Do the initial steps to setup the project.
3. Run the command docker compose up --build.
4. Observe the output and error message.

### 👍 Expected behavior

The Docker Compose should successfully build the application and start the services defined in the Dockerfile without errors.

### 👎 Actual Behavior with Screenshots

The output shows the following error:
```css
failed to solve: target stage "development" could not be found
```
![image](https://github.com/user-attachments/assets/ee9722f2-430f-4bf4-8bb0-0fab1b229ec8)

### OS name

Windows + WSL2

### browser name

Other

### npm version

10.8.2

### node version

v20.18.0

### 📃 Provide any additional context for the Bug.

It appears that there may be an issue with the multi-stage builds in the Dockerfile. I believe the target stage "development" is not defined or correctly referenced.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vishnud05** [comment]
Apart from this, there are a bunch of other docker setup issues as well
1. No development stage (already mentioned)
2. DB not seeded correctly
3. Env variables not configured correctly
4. Prsima Studio not working

**Comment by vishnud05** [comment]
#498
