### ISSUE TITLE
🚀 Feature: Add Clear All Button for jobFilter

### ISSUE THREAD

**Issue by Ahmadmidlaj** [code100x/job-board#471]
### 🔖 Feature description

Add a "Clear All" button to the jobs page filter section

### 🎤 Why is this feature needed ?

Currently, when users apply multiple filters on the jobs page, there's no quick way to reset all filters at once. Users have to manually deselect each filter individually, which can be time-consuming and frustrating, especially when many filters are applied.

Adding a "Clear All" button would significantly improve the user experience by allowing users to quickly reset their search and start over with a clean slate.

Examples of when this would be useful:
1. A user applies several filters but doesn't find suitable results and wants to start a new search.
2. A user accidentally applies an unintended filter and wants to quickly reset.
3. A recruiter frequently switches between

### ✌️ How do you aim to achieve this?

1. Add a "Clear All" button next to the existing filter options on the jobs page.
2. When clicked, the button should:
   - Deselect all currently selected filters
   - Reset any text input fields related to filtering (if applicable)
   - Trigger a new search with no filters applied
   - Update the UI to reflect that no filters are selected

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by CyberSpyderX** [comment]
Can I work on this?

**Comment by SupriyaGo** [comment]
Hi @Ahmadmidlaj  @VineeTagarwaL-code , Please assign this issue to me
