### ISSUE TITLE
🐛 Bug Report: Testimonial component render

### ISSUE THREAD

**Issue by CyberSpyderX** [code100x/job-board#479]
### 📜 Description

Issues with testimonial components:
1. Does not render in the first go 
2. Abrupt animation restart once the scroller reaches the end.
3. Inconsistent height issue and content cutoff with current changes

### 👟 Reproduction steps

1. Go to the landing page and scroll down to the testimonials section
2. Observe several testimonial cards with different heights
3. (For animation issue) Wait until the final testimonial card

### 👍 Expected behavior

1. Load all the testimonials right away when the landing page is rendered
2. Smoother transition to the beginning of the list
3. Even dimensions for testimonial cards

### 👎 Actual Behavior with Screenshots

1. Does not render in the first go 
![image](https://github.com/user-attachments/assets/b2b83887-570d-4a40-9f3d-b694379a305b)
2. Abrupt animation restart once the scroller reaches the end.

https://github.com/user-attachments/assets/4e93776d-652e-4526-b0dc-b731a7f6e2c7

3. Inconsistent height issue and content cutoff with current changes
![Screenshot 2024-10-07 154935](https://github.com/user-attachments/assets/88cada17-6f6c-4c84-8b88-03684bef1d16)
![image](https://github.com/user-attachments/assets/fae4a1b8-6f49-4ccb-b7ef-27d0ef63e7e0)

### OS name

Windows

### browser name

Chrome

### npm version

9.8.1

### node version

22.7.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by SupriyaGo** [comment]
Hi @VineeTagarwaL-code , please assign this to me
