### ISSUE TITLE
:star: [ IMPROVEMENT ] : Login Page UI and Form Validation

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#48]
### Title
Enhance Login Form Design and Add Proper Validation with Zod

### Description
The current login form needs improvement in both design and functionality. The form should be visually appealing, user-friendly, and include proper validation using Zod. Additionally, a "Sign up with Google" button should be added to enhance the user experience.

### Tasks
1. **Improve the Design**:
    - Enhance the overall look and feel of the form to make it more attractive and user-friendly.
    - Ensure the form is responsive and looks good on various screen sizes.
    - Use appropriate colors, fonts, and spacing to improve readability and aesthetics.
    - Add a "Sign up with Google" button with appropriate styling.

2. **Add Validation with Zod**:
    - Implement proper validation for email and password fields using the Zod library.
    - Ensure the form provides user-friendly error messages for invalid inputs.
    - Highlight the input fields with errors to provide clear feedback to the user.

3. **Additional Enhancements**:
    - Add smooth animations for form transitions using Framer Motion or any other animation library.
    - Ensure the form is accessible and follows best practices for accessibility.

### Additional Context
- Refer to the attached screenshot for the current design.
- Ensure the new design is consistent with our brand guidelines.
- Test the form on various devices and browsers to ensure compatibility.

### Screenshots
![Current Login Form](https://user-images.githubusercontent.com/123456789/123456789-abcdef.png)

## Pull Request Context
This issue will be handled on a first-come, first-serve basis. We will not assign or lock this issue to any specific contributor. The pull request (PR) that comprehensively addresses all the listed tasks and ensures that every aspect is completed will be reviewed and merged.

- Please make sure to reference this issue in your PR.
- Ensure your changes are well-tested and do not introduce any new issues.
- Include screenshots or screen recordings of the updated design and functionality.
- Follow our contribution guidelines and code style.

Good luck, and thank you for your contribution!

**Comment by mayank2130** [comment]
Something like this?
![loginUI](https://github.com/user-attachments/assets/106ef368-bd4b-4856-b0fc-1a1232c526c4)

**Comment by VineeTagarwaL-code** [comment]
Looks neat, can build on this too ! @mayank2130

**Comment by mayank2130** [comment]
Sure.

**Comment by SwetanshuSingh** [comment]
@mayank2130 @VineeTagarwaL-code  The project is exclusively for the cohort community, adding sign in with google does not makes sense as of now. We will move to magic login links if needed in future

**Comment by VineeTagarwaL-code** [comment]
Nice PR's folks, all the pr are awesome but @SwetanshuSingh PR looks good and neat, will assign PR's to folks now
