### ISSUE TITLE
🚀 Feature: Expand Sorting Options for Jobs

### ISSUE THREAD

**Issue by Arpit-Khandelwal** [code100x/job-board#481]
### 🔖 Feature description

At present, users can only sort jobs by two options: Latest Jobs and Oldest Jobs. I suggest enhancing the user experience by adding more sorting options, such as:

- Highest Paid
- Most Viewed
- Most Applied

### 🎤 Why is this feature needed ?

This functionality is similar to what is available on sites like remoteok.com and would give users more flexibility in finding relevant jobs.

### ✌️ How do you aim to achieve this?

- Highest paid sorting is straightforward
- Most viewed: add a counter for each Job in DB which tracks the number of clicks on the Job card
- Most Applied: similar to most viewed, add counter to DB which tracks number of clicks on "Apply now" on a particular Job

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
go ahead

**Comment by Vivek-1102** [comment]
@VineeTagarwaL-code any open issue I need to make my first contribution in code100x, can you please assign me the next issue ?
