### ISSUE TITLE
🚀 Feature:  candidate onboarding

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#484]
### 🔖 Feature description

We need to take basic info about the candidate and save in our database 

things needed 

1. experience 
2. projects 
3. skills
4. resume 

Things needed for every point above is mentioned below in this picture

all the feature should implemented after the first time user signs up for us, sort of "onboarding"
![image](https://github.com/user-attachments/assets/3b083ec0-5e92-4b3c-8804-b4f1e9adc19c)

flow needed : - 

![image](https://github.com/user-attachments/assets/66cd5736-b692-409d-8fab-135c827c29c9)

https://mui.com/material-ui/react-stepper/ - use this for multipart form ( vertical stepper is a very good choice ) 

### 🎤 Why is this feature needed ?

for for onboarding

### ✌️ How do you aim to achieve this?

by os

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by Ashutoshpadhi629** [comment]
Can I work on this @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
i am opening a lot of issues right now

**Comment by VineeTagarwaL-code** [comment]
@ashishmohanty10 pick the other one, opening in a min assigning ashuthosh this one

@Ashutoshpadhi629 ETA for this will be ?

**Comment by Ashutoshpadhi629** [comment]
@VineeTagarwaL-code , sure

**Comment by Husain01** [comment]
Can I work on this?

**Comment by SahilSuman1011** [comment]
Is this issue closed or still open ? i would like to work on this .
