### ISSUE TITLE
🐛 Bug Report: Fix create Job button

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#485]
### 📜 Description

The create job button doesnt work right now, for some reasons 

### 👟 Reproduction steps

go to post job page and try to create a new job 

admin@gmail.com
123456

for admin access

### 👍 Expected behavior

it should create the job 

### 👎 Actual Behavior with Screenshots

it does create the job 

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by CyberSpyderX** [comment]
Can I work on this too?

**Comment by ashishmohanty10** [comment]
seems like the issue is already fixed @VineeTagarwaL-code
