### ISSUE TITLE
🐛 Bug Report: Non approved jobs are showing up 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#486]
### 📜 Description

un-approved jobs are showing up. only show the ones that has been approved 

### 👟 Reproduction steps

go to explore page and search for this job

Build and maintain server-side logic.Backend dev ( it is not approved still shows up ) 

### 👍 Expected behavior

only approved ones will show up 

### 👎 Actual Behavior with Screenshots

nan

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by nolostra** [comment]
assign me

**Comment by CyberSpyderX** [comment]
Can I work on this?

**Comment by RutamBhagat** [comment]
I would like to work on this issue

**Comment by tushar-agarwal7** [comment]
@VineeTagarwaL-code  plz assign this issue to me
