### ISSUE TITLE
lets name it Hire100x, happy to work on it

### ISSUE THREAD

**Issue by Tarunmeena0901** [code100x/job-board#5]
hey, I am happy to work on this lets keep most of the stake same as CMS, which will be Next, next-auth , tailwind, prisma, postgress, recoil or maybe redux maybe little bit framer motion 
For notification others anytime a new job post come in we can use cohort discord servers

have look at job section (It stills incomplete just to give an idea)
![image](https://github.com/user-attachments/assets/e2f2df6b-aaba-40c6-af20-2b968a1921c8)

**Comment by Tarunmeena0901** [comment]
you can look at my github or have a look at my recent project : https://landing-page-template-beige.vercel.app/

**Comment by yhbarve** [comment]
Hey! This looks pretty good. I am happy to work on it too.

**Comment by Smnthjm08** [comment]
@Tarunmeena0901 Keeping the theme same as 100xdevs.com will work fine.

**Comment by Ankur02Sarkar** [comment]
Lets also add Gen AI to help peeps find jobs/interships easily. I'm thinking about integrating something like Buildspace Sage (https://sage.buildspace.so/) . @hkirat what do you think?

**Comment by Tarunmeena0901** [comment]
lets add the first basic functionality a job platform should have which includes auth and notification system then we can build on top of it

**Comment by Tarunmeena0901** [comment]
as maintainers are assigned i am closing this issue
