### ISSUE TITLE
🐛 Bug Report: OAuth Error: Redirect URI Mismatch (Error 400) During Google Sign-In

### ISSUE THREAD

**Issue by x15sr71** [code100x/job-board#500]
### 📜 Description

Encountering an Error 400: redirect_uri_mismatch when trying to sign in with Google in the production environment. The app is unable to complete the authentication flow due to a mismatch in the redirect URI.

### 👟 Reproduction steps

1. Set up Google OAuth sign-in.
2. Deploy the app in a production environment.
3. Attempt to sign in with Google using a valid account.
4. Receive the error: "Access blocked: This app’s request is invalid. Error 400: redirect_uri_mismatch".

### 👍 Expected behavior

The app should successfully authenticate the user via Google sign-in without redirect URI mismatch errors.

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-10-12 132250](https://github.com/user-attachments/assets/98ddcd6e-44d5-4995-9dbb-d51261ddaa5d)

### OS name

Windows

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by CuriousCoder00** [comment]
@x15sr71 are you using it on local or deployed?

**Comment by x15sr71** [comment]
@CuriousCoder00 deployed

**Comment by CuriousCoder00** [comment]
@x15sr71 on which link?

**Comment by x15sr71** [comment]
@CuriousCoder00 https://staging.placements.100xdevs.com/signin

**Comment by CuriousCoder00** [comment]
> @CuriousCoder00 https://staging.placements.100xdevs.com/signin

It won''t work as it hasn't been configured yet on the main url
you can use job.vineet.tech tho

**Comment by x15sr71** [comment]
@CuriousCoder00 Thanks for the clarification! I assumed the staging environment was set up for Google OAuth.
