### ISSUE TITLE
🐛 Bug Report: handleFormSubmit function does not properly handle error

### ISSUE THREAD

**Issue by prakhyatc** [code100x/job-board#504]
### 📜 Description

If an error occurs during the submission process, it will be caught by the generic catch block, but the error message will not be displayed to the user.

### 👟 Reproduction steps

1. Ensure the createJob API endpoint or the uploadFileAction function is mocked or simulated to return an error response (e.g., 500 Internal Server Error
2. Click the submit button to trigger the handleFormSubmit function.
3. Observe the console or error logs.

### 👍 Expected behavior

The error should be caught and displayed to the user through the toast notification system.

### 👎 Actual Behavior with Screenshots

The error is caught by the generic catch block, but the error message is not displayed to the user.The error is logged to the console, but no user-friendly error message is shown.

### OS name

MacOS

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
nice work on this
