### ISSUE TITLE
🐛 Bug Report: Error Handling in submitImage

### ISSUE THREAD

**Issue by prakhyatc** [code100x/job-board#505]
### 📜 Description

The submitImage function does not handle errors properly. If the image upload fails, it will log an error message to the console, but it will not notify the user.

### 👟 Reproduction steps

To trigger the bug :
1. Fill out the form with valid data.
2. Attempt to upload an invalid or corrupted image file (e.g., a text file renamed to .jpg).
3. Observe the console or error logs.
4. Verify that the image upload fails and an error message is logged to the console.
5. Check the UI for any error notifications or messages.

### 👍 Expected behavior

1.The error should be caught and displayed to the user through the toast notification system or an inline error message
2. The user should be notified that the image upload failed

### 👎 Actual Behavior with Screenshots

1. The error is caught by the catch block, but only logged to the console.
2. No user-friendly error message is displayed to the user.
3. The form submission process may continue without notifying the user of the image upload failure

### OS name

MacOS

### browser name

Chrome

### 📃 Provide any additional context for the Bug.

test with network errros, server-side errors, validation errors

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by devsharmagit** [comment]
This can be fixed by adding a check before whenever the handleFileChange is triggred.
I have done this locally. I can open a pull request.
![image](https://github.com/user-attachments/assets/253cca02-95da-445b-8ca9-f7aa8368bb36)
