### ISSUE TITLE
🐛 Bug Report: Account Delete Bug

### ISSUE THREAD

**Issue by Kashyap1ankit** [code100x/job-board#507]
### 📜 Description

When user tries to delete their account they get nextjs error .

![Screenshot from 2024-10-15 20-21-37](https://github.com/user-attachments/assets/78f5c726-7239-4373-a4e0-1dcbcd8125a0)

### 👟 Reproduction steps

1.Login with credentials 
2. Goto Profile Page >> Edit Profile
3. Click on Delete Account Option

### 👍 Expected behavior

It should delete the user account from database and then make the user logout

### 👎 Actual Behavior with Screenshots

It actually throwing the error

### OS name

Linux

### browser name

Chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Kashyap1ankit** [comment]
@VineeTagarwaL-code assign it to me .. i have checked the error root cause so can easily and quickly fix it

**Comment by CuriousCoder00** [comment]
I was not able to reproduce the error...!!! can you show what's the error?

**Comment by Kashyap1ankit** [comment]
> I was not able to reproduce the error...!!! can you show what's the error?

When you try to delete your account it will give this error "Only plain objects can be passed to Client Components from Server Components"

**Comment by VineeTagarwaL-code** [comment]
Nice catch
