### ISSUE TITLE
🚀 Feature: Add ShareJobDialog Component for Multi-Platform Job Sharing

### ISSUE THREAD

**Issue by Ahmadmidlaj** [code100x/job-board#510]
### 🔖 Feature description

Add a new `ShareJobDialog` component that allows users to share job postings across multiple social media platforms (Twitter, LinkedIn, WhatsApp) using a dialog interface. This feature will replace the current Twitter-only sharing button with a more versatile and user-friendly sharing option.

### 🎤 Why is this feature needed ?

Currently, our job sharing functionality is limited to Twitter only. Implementing a multi-platform sharing feature will:
1. Increase the reach of job postings by allowing users to share on their preferred platforms.
2. Improve user experience by providing more sharing options in a clean, intuitive interface.
3. Potentially increase engagement and applicant numbers for job postings.

### ✌️ How do you aim to achieve this?

1. Create a new `ShareJobDialog` component using Shadcn UI's Dialog component.
2. Implement sharing functions for Twitter, LinkedIn, and WhatsApp.
3. Replace the current Twitter share button in the `Job` component with the new `ShareJobDialog`.
4. Ensure the dialog is responsive and accessible.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ameeetgaikwad** [comment]
would like to work on this!

**Comment by Ahmadmidlaj** [comment]
> would like to work on this!

I worked on this issue and raised PR already

**Comment by VineeTagarwaL-code** [comment]
ig this was just merged
