### ISSUE TITLE
🚀 Feature: Stack based project listing 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#522]
### 🔖 Feature description

In the current onboarding form we have project input 

modify that to allow user to first choose from the specific stack mentioned below and also add "other" as an option 

allow user to post live link and github ( already done ) 

![image](https://github.com/user-attachments/assets/d6ef77cf-3479-4375-b768-1361e1d83677)

### 🎤 Why is this feature needed ?

to allow user to show project specific to stacks 

### ✌️ How do you aim to achieve this?

by implementing this 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by CuriousCoder00** [comment]
assign

**Comment by SahilLamba0008** [comment]
assign me @VineeTagarwaL-code
