### ISSUE TITLE
🐛 Bug Report: non disclosed salary filtering 

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#523]
### 📜 Description

Currently the non disclosed salary jobs are appearing at top when we try to filter using the highest  salary in explore page 

![image](https://github.com/user-attachments/assets/6c91b75a-1a4a-445a-9ab9-3c62be1b37c7)

### 👟 Reproduction steps

explore page -> filter using highest salary 

### 👍 Expected behavior

the non disclosed ones should be at the bottom of the list 

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/41c1200c-640e-4dd0-9791-0d986d44c634)

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by SahilLamba0008** [comment]
Assign me

**Comment by Harsh8089** [comment]
Can I also work ? @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
Already assigned no worries will more issues at 3:10pm

**Comment by Harsh8089** [comment]
Okay sir

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code can you create some more issue to work on

**Comment by Harsh8089** [comment]
done sir @VineeTagarwaL-code 
![image](https://github.com/user-attachments/assets/df9b7f66-f1f5-4d2c-bed8-8b3c6646c1f4)
![image](https://github.com/user-attachments/assets/30adba62-4cee-4cd0-9981-45b38aa2e1eb)
![image](https://github.com/user-attachments/assets/429b3f4f-5956-4ac7-9a29-3df713781366)

**Comment by VineeTagarwaL-code** [comment]
Open pr will accept then

**Comment by Harsh8089** [comment]
@VineeTagarwaL-code  done

**Comment by SahilLamba0008** [comment]
> @VineeTagarwaL-code done

Your solution works well for numeric fields like `maxSalary`, but it'll fail for non-numeric fields such as `postedat`. The issue is that `nulls: 'last'` is only valid for numeric fields. You should conditionally apply `nulls: 'last'` when sorting by `maxSalary` and omit it for fields like `postedAt` as it is or type `DateTime` here.
