### ISSUE TITLE
🐛 Bug Report: Project name being added to dependencies

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#531]
### 📜 Description

Project name being added to dependencies

### 👟 Reproduction steps

1. Go to `package.json`
2. inside dependencies you'll find the issue

### 👍 Expected behavior

It should not be added

### 👎 Actual Behavior with Screenshots

 "dependencies": {
    "100xdevs-job-board": "file:",
    ..
...
}

This is the current package.json where you can see it is being added
![image](https://github.com/user-attachments/assets/205e8115-baa2-4661-b7d7-75b4da4603ad)

### OS name

Windows

### browser name

Chrome

### npm version

10

### node version

20

### 📃 Provide any additional context for the Bug.

This issue seems like to be caused by some extension (e.g.  [Red Hat Dependency Analytics](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics&ssr=false#review-details)  ) that is active on a few contributers system
This kind of extensions cause this issue they add project name as dependency

For now removing the `"100xdevs-job-board": "file:"` from `package.json`
Looking for solutions or any script so that it doesn't get pushed to the repo

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by VineeTagarwaL-code** [comment]
opsieee

**Comment by VineeTagarwaL-code** [comment]
?
