### ISSUE TITLE
🐛 Bug Report: Deleted jobs are showing to the users 

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#535]
### 📜 Description

delete jobs are showing to the user

### 👟 Reproduction steps

just go to the jobs page, even if the jobs are deleted by the admin, it is showing to the user

### 👍 Expected behavior

deleted job should only be visible to the admin and not user

### 👎 Actual Behavior with Screenshots

deleted job should only be visible to the admin and not user

### OS name

Windows

### browser name

Chrome

### npm version

-

### node version

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mrsingh-rishi** [comment]
@VineeTagarwaL-code please assign this to me
