### ISSUE TITLE
🚀 Feature: Update job feature

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#537]
### 🔖 Feature description

The "Update Job" feature enables job posters to modify existing job listings directly on the platform.

### 🎤 Why is this feature needed ?

The "Update Job" feature allows job posters to modify the details of existing job postings.

### ✌️ How do you aim to achieve this?

by creating a update jobs form, which hits the server action to update the job

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code can i start working??

**Comment by shwetaa94** [comment]
pls assign it to me @VineeTagarwaL-code

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code I am almost done with this

**Comment by VineeTagarwaL-code** [comment]
No dont, wait for my confirmation atleast
