### ISSUE TITLE
🚀 Feature:  Implement Undelete Feature for Job Listings and Delete job from the db after certain time 

### ISSUE THREAD

**Issue by Paribesh01** [code100x/job-board#538]
### 🔖 Feature description

The "Undelete Jobs" feature enables job posters to restore previously deleted job listings, also if user deletes the job then job will be remove from the db after 1-2 months

### 🎤 Why is this feature needed ?

The "Undelete Jobs" feature allows users to recover accidentally deleted job listings, also if we donot delete the deleted jobs from the db then our db will be full of deleted jobs which are no use

### ✌️ How do you aim to achieve this?

creating a server action to restore the deleted job, and to deleted job after certain time, i will create a timer in the job and the cron job checks it every day and if 1-2 months have passed then it deletes it from the db

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code can in start working

**Comment by mrsingh-rishi** [comment]
@VineeTagarwaL-code can I work on this

**Comment by shwetaa94** [comment]
pls assign it to me @VineeTagarwaL-code

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code I have already started working

**Comment by VineeTagarwaL-code** [comment]
why will user delete the job ?

**Comment by VineeTagarwaL-code** [comment]
and restoring is a good option tbh, but 1-2 months will be a stretch keep it like 10 days
