### ISSUE TITLE
🚀 Feature: Add socials

### ISSUE THREAD

**Issue by CuriousCoder00** [code100x/job-board#539]
### 🔖 Feature description

Creating a form section where user can add there social such as github, linkedin, twitter

### 🎤 Why is this feature needed ?

so a recruiter can reach out to the job-seeker or user via there social media that they have provided

### ✌️ How do you aim to achieve this?

creating a little form that accepts social platform name and social platform url

### 🔄️ Additional Information

It would look something like this

![image](https://github.com/user-attachments/assets/b409d60d-60f0-4c1f-83f9-2fdfdc24aa08)
![image](https://github.com/user-attachments/assets/3c3156ea-32d8-4f90-9fba-4a6e67c7f9c1)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by CuriousCoder00** [comment]
@VineeTagarwaL-code if you find this relevant please assign it to me, i'll raise a pr asap just need to create actions

**Comment by vlokesh08** [comment]
@VineeTagarwaL-code please assign this
Plan of action : will be adding a Dialog and a dropdown for various social links, if no links are present will be adding a note saying you have no media links linked and a button to add one

**Comment by CuriousCoder00** [comment]
@vlokesh08 as you can already see in the screenshots provided I'm already done with most parts of it. You can change another issue that are to come soon.

**Comment by mrsingh-rishi** [comment]
@VineeTagarwaL-code can i work on this please assign it to me

**Comment by shwetaa94** [comment]
pls assign it to me @VineeTagarwaL-code

**Comment by VineeTagarwaL-code** [comment]
dont start working without me assigning, or giving a feedback 

three new feature request will open shortly, keep an eye out for that
