### ISSUE TITLE
🚀 Feature: UI update of admin page

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#547]
### 🔖 Feature description

GO through this and update the ui of admin page 

https://www.figma.com/design/0Acu1rj33FPBuCzFnqDiyW/100xdevs-Working?node-id=28-7357&node-type=canvas
![image](https://github.com/user-attachments/assets/a3ba008a-379e-49de-80bd-1fdee16e5101)

### 🎤 Why is this feature needed ?

to enhance the look

### ✌️ How do you aim to achieve this?

by implementing

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by VineeTagarwaL-code** [comment]
@Paribesh01 do you have any other pr assigned ?

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code no, done with all

**Comment by VineeTagarwaL-code** [comment]
@Paribesh01 submit the pr by tomorrow evening, assigning you

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code ok, i will start working....

**Comment by Ameerjafar** [comment]
@VineeTagarwaL-code can you assign me this issue sir.

**Comment by VineeTagarwaL-code** [comment]
@Ameerjafar hey thanks for asking, currently this issue is already assigned but if i dont hear back from @Paribesh01 within 1 day, i will assign you

**Comment by codervinod123** [comment]
Hii @VineeTagarwaL-code this issue is assigned to someone else but i was working on it for learning and  he had not submit PR by today evening so i raised one feel free to avoid it.
I don't have any problem if you will give his PR higher priority , if possible then please review it.

**Comment by Paribesh01** [comment]
@VineeTagarwaL-code done with the work, review the pr
