### ISSUE TITLE
🚀 Feature: Job seeker page ui update

### ISSUE THREAD

**Issue by VineeTagarwaL-code** [code100x/job-board#548]
### 🔖 Feature description

Add the job seeker page, with edit and manage integrated all at once 

-> url - /profile/[userid]
-> only if the user is logged in and in viewing his own page will be able to see the add more and edit buttons, for viewers that are not logged in or not viewing there own profile, we shouldn't be showing the edit and add more buttons 
-> for the forms that will open up after clicking on edit or add more, use the drawer component from shadcn 
-> the ui given in the figma should be cloned fully without any misses
![image](https://github.com/user-attachments/assets/cdd735ed-9c88-4463-ae0b-7c45c6626d9f)

figma  

https://www.figma.com/design/0Acu1rj33FPBuCzFnqDiyW/100xdevs-Working?node-id=28-7357&node-type=canvas

### 🎤 Why is this feature needed ?

to allow job seekrs to view profile very easily 

### ✌️ How do you aim to achieve this?

by implemeting

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

**Comment by devsharmagit** [comment]
can i work on this?

**Comment by VineeTagarwaL-code** [comment]
@devsharmagit are you clear with instructions ?

**Comment by VineeTagarwaL-code** [comment]
shoot me a discord dm, this will be a very big pr so want to get in real talk with you and help you clear your doubts ( if any )

**Comment by devsharmagit** [comment]
sure sir

**Comment by pavanydg** [comment]
@VineeTagarwaL-code  can i also work on this?

**Comment by CuriousCoder00** [comment]
Looks like i got left out in this one 😅😅

**Comment by subbuwu** [comment]
@VineeTagarwaL-code This should be done by assigned peeps or can anyone take up this and raise a pr ?

**Comment by devsharmagit** [comment]
@codervinod123 
I will raise PR by tomorrow evening. If I will not be able to do it then I will seek help.

**Comment by codervinod123** [comment]
sure! thanks @devsharmagit
