### ISSUE TITLE
🚀 Feature: Weekly Job Alert Subscription

### ISSUE THREAD

**Issue by ajeeshRS** [code100x/job-board#549]
### 🔖 Feature description

--> Users can subscribe to weekly job alerts, receiving emails with the latest job listings from the past week.

### 🎤 Why is this feature needed ?

In my use case, this feature will help users stay updated with recent job listings and increase overall user engagement and activity.

### ✌️ How do you aim to achieve this?

<img width="1440" alt="Screenshot 2024-10-24 at 11 53 02 AM" src="https://github.com/user-attachments/assets/5dcdeb15-42d9-4b7d-b995-bf4088fc30c1">

These are my initial thoughts, I would love to get suggestions for improvements.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by ajeeshRS** [comment]
@VineeTagarwaL-code

**Comment by subbuwu** [comment]
Can i take this up ?

**Comment by VineeTagarwaL-code** [comment]
not needed for now but will add this in v2
