### ISSUE TITLE
✨ Improvement: mobile view dialog ui

### ISSUE THREAD

**Issue by vamsi4845** [code100x/job-board#551]
### 📜 Description

While Creating a Profile in mobile view the add dialogs are just coinciding with the screen, and the share job dialog too
 currently,shadcn  dialog uses 100vw width so we can reduce 5% in mobile view to fix this,

### 👟 Reproduction steps

While Creating a Profile in mobile view the add dialogs are just coinciding with the screen, and the share job dialog too

https://github.com/user-attachments/assets/d0622bc9-8c60-4160-be80-e3a03f0aa6d7

![chrome_L78RYzovpa](https://github.com/user-attachments/assets/c221b631-1710-49e1-b1c2-39562811b72a)

### 👍 Expected behavior

Same dialog is used in all of these so just giving an example
![chrome_BFwSNzOFwr](https://github.com/user-attachments/assets/07779bd6-3e33-440a-8eb1-95173f310dac)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by vamsi4845** [comment]
@VineeTagarwaL-code Can i create a pr for this?

**Comment by MuditxRajput** [comment]
This issue is solve , how i merge it , i am new to open source anyone help

**Comment by VineeTagarwaL-code** [comment]
we already have on feature req opened with similar goal
