### ISSUE TITLE
add validation to validate if job_seeker is 100xdev member or not 

### ISSUE THREAD

**Issue by Tarunmeena0901** [code100x/job-board#56]
I think this job-board is exclusive for all Cohort students only so if this is true we need validation logic to validate users only if he is joining with a role of job_seeker and different logic for recruiter

if this is a valid issue let me know I am happy to work on it

**Comment by anuragnegi000** [comment]
we can use the ID of users stored in the database of 100xdevs to validate them
like if email registered in100xdevs is:-
test@gmail.com

so the user can login with same email and can get access of Job-board

**Comment by SwetanshuSingh** [comment]
> I think this job-board is exclusive for all Cohort students only so if this is true we need validation logic to validate users only if he is joining with a role of job_seeker and different logic for recruiter
> 
> if this is a valid issue let me know I am happy to work on it

It is already implemented if you look at the code, there is a reason no register page exists.

**Comment by SwetanshuSingh** [comment]
> we can use the ID of users stored in the database of 100xdevs to validate them

correct @anuragnegi000 , we will migrate the db soon and sync it with 100x original db

**Comment by anuragnegi000** [comment]
> > we can use the ID of users stored in the database of 100xdevs to validate them
> 
> correct @anuragnegi000 , we will migrate the db soon and sync it with 100x original db

Yes this would be good

**Comment by Tarunmeena0901** [comment]
I am looking at this function and I dont see how we are validating user from AppX database

PS: ohh i guess 100xdev database already have register users only so we dont need to use AppX database to validate
nice, it this is the case we can close this issue

**Comment by SwetanshuSingh** [comment]
> I am looking at this function and I dont see how we are validating user from AppX database
> 
> PS: ohh i guess 100xdev database already have register users only so we dont need to use AppX database to validate nice, it this is the case we can close this issue

yes sir, you are correct
