### ISSUE TITLE
🐛 Bug Report: Log in page shows bad toast message

### ISSUE THREAD

**Issue by subhanahujha007** [code100x/job-board#561]
### 📜 Description

when you log in  the web app if user doesn't exist it shows a long message

### 👟 Reproduction steps

1. Go to login
2. enter credentials of a email thats not present in database

### 👍 Expected behavior

it should say user doesn't exists

### 👎 Actual Behavior with Screenshots

![Screenshot (309)](https://github.com/user-attachments/assets/c10c9bde-18a6-429b-bf4a-184ce68d445b)

### OS name

Windows

### browser name

Firefox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by devsharmagit** [comment]
This bug should be closed now.
