### ISSUE TITLE
✨ Improvement:  Enhance Password Validation Schema for Better Security

### ISSUE THREAD

**Issue by SinghAstra** [code100x/job-board#573]
### 📜 Description

Currently, the password validation in SignupSchema and SigninSchema only checks if a password exists (min length 1). This could lead to users creating very weak passwords. 

Suggested Enhancement:
Add stronger password validation rules using Zod's string validation methods. Recommended rules:

- Minimum length of 8 characters
- At least one uppercase letter
- At least one lowercase letter
- At least one number
- At least one special character
- Maximum reasonable length (e.g. 128 characters)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by Kevinkp09** [comment]
hey @VineeTagarwaL-code can i work upon this improvement?
