### ISSUE TITLE
✨ Improvement: Add loading spinner icon during form submission

### ISSUE THREAD

**Issue by SinghAstra** [code100x/job-board#574]
### 📜 Description

Currently, the signup and signin form shows only text feedback ("Please wait...") during form submission. Adding a loading spinner would improve the user experience by providing better visual feedback.

Proposed changes:
1. Add Loader icon from lucide-react during form submission
2. Place the loader next to "Please wait..." text
3. Maintain consistent styling using Tailwind CSS

Current behavior:
Button shows only text: "Please wait..."

Proposed behavior:
Button shows: [Loader icon] "Please wait..."

Technical implementation:
- Use lucide-react's Loader2 component
- Add Tailwind CSS animation for smooth spinning
- Maintain existing button states and accessibility

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/code100x/job-board/blob/main/CONTRIBUTING.md)

**Comment by lucky29-git** [comment]
Can I work on this? @SinghAstra @VineeTagarwaL-code
