### ISSUE TITLE
 📦 [FEATURE]: Enchancing the current job form and add view job details

### ISSUE THREAD

**Issue by SwetanshuSingh** [code100x/job-board#58]
1. The current job creation form only supports to create remote jobs. We need to update the form so it shows the state and country fields conditionally on selecting In Office and Remote Jobs.

I have already completed this form and I am completing the server action for this. 
Here is the preview for the new form: 
![image](https://github.com/user-attachments/assets/c9a76ddf-a2ac-438a-b16d-84eb62b9b8cc)

2. Adding the view full job details sheet inspired from wellfound.

@VineeTagarwaL-code As I am almost done with completing the features, I want you to assign this issue to me and I will rasie a PR soon

**Comment by VineeTagarwaL-code** [comment]
have you completed this ?

**Comment by VineeTagarwaL-code** [comment]
I have assigned you for the time being, expecting a reply within 24 hours

**Comment by VineeTagarwaL-code** [comment]
great checking it out !

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
