### ISSUE TITLE
📦 [FEATURE]: Create Profile Page with User Details Display

### ISSUE THREAD

**Issue by Shubham-Kumar1** [code100x/job-board#59]
## Create a profile page to display user details fetched from the server. The page should include the following features:
User Details Display:
Profile picture (if available)
Email
Full Name
Email Verified status
Role (e.g., ADMIN, USER)
User Authentication:
# 
Ensure the user is authenticated before accessing the profile page.
Redirect unauthenticated users to the login page.
Loading and Error Handling:
#
Show a loading spinner while fetching data.
Display appropriate messages for errors (e.g., user not found, fetch failures).
Navigation:
#
Provide a button to navigate to the edit profile page.

Hi @VineeTagarwaL-code 

I’m working on creating the profile page to display user details, including profile picture, email, full name, email verified status, and role. I’ve completed the initial setup and am currently finalizing the details.

Could you please assign this issue to me? I’ll raise a PR once everything is complete.
Thanks!

**Comment by mayank2130** [comment]
Happy to work on the functionality side of things & more, @VineeTagarwaL-code if this looks good you can assign this issue to me.  

https://github.com/user-attachments/assets/9a53b7bd-539a-4686-a816-a3e9e885eb03

**Comment by VineeTagarwaL-code** [comment]
Go ahead, assigned !

**Comment by VineeTagarwaL-code** [comment]
any updates ?

**Comment by mayank2130** [comment]
Yeah, completed functionality and server actions. Just finishing up a few things.

https://github.com/user-attachments/assets/8e59808f-a35a-47d1-9eb8-252a3cd419b6

**Comment by VineeTagarwaL-code** [comment]
When done let me know on discord ! you know how to reach me out

**Comment by mayank2130** [comment]
I do.

**Comment by VineeTagarwaL-code** [comment]
Great will merge it by tonight, will be merging one pr from #137

**Comment by mayank2130** [comment]
Good to know!

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that

**Comment by mayank2130** [comment]
What happened to this issue?

**Comment by VineeTagarwaL-code** [comment]
Initially, we planned to implement a profile page and login flow for users. However, as we progressed, it became clear that adding these features would be unnecessary at this stage. That's why I mentioned focusing on the issues that were opened after #137  was merged. Apologies for the confusion, but it was still a solid PR.
