### ISSUE TITLE
[Feature]: Job Details Page

### ISSUE THREAD

**Issue by vibhaw1904** [code100x/job-board#65]
Description:
We need to create a Job Details page that provides comprehensive information about a specific job listing. This page should include sections for the job title, a brief description, the job location, and the salary and an "Apply" button.

Requirements:
1.Job Title: Display the title of the job prominently at the top of the page.
2.Description: Provide a brief description of the job. This should include key responsibilities, requirements, 3.and any other pertinent details.
4.Location: Indicate where the job is based. This should include the city, state, and country.
5.Salary: Display the salary or salary range for the position. If applicable, include additional information about benefits and compensation packages.
6.Apply Button: Add a button that allows users to apply for the job

**Comment by vibhaw1904** [comment]
working on this issue

**Comment by VineeTagarwaL-code** [comment]
Why are you going forward with overlay approach exactly ? why not a specific page with job id used for routing ?

**Comment by vibhaw1904** [comment]
appreciate your feedback and suggestions. Regarding the approach for displaying job details:

Yup, we can keep both approaches. We can also add a specific page with a job ID for routing purposes. The overlay is also good because it allows users searching for jobs to easily see the details without navigating away from the current page, enhancing user interaction and convenience.
