### ISSUE TITLE
🐞 [BUG]: Footer is colliding on every page with the main content

### ISSUE THREAD

**Issue by prateekkumaroriginal** [code100x/job-board#67]
### Title
- Fix the css so that `<Footer/>` doesn't collide with page content and appear only when you reach the bottom of the page.
- Fix Home page, the `s` of `100xJobs` is getting cut a little bit.

### Description
The current `<Footer/>` collides with main content and the `s` of `100xJobs` is getting cut a little bit:-

https://github.com/user-attachments/assets/aae591c4-445f-4557-a8f7-ca847f25f9ec

### System Specs:-
- Device: Redmi Notebook 14
- OS: Windows 10
- Browser: Brave

**Comment by RutikKulkarni** [comment]
Working on this..

**Comment by VineeTagarwaL-code** [comment]
The video is not visible, please make sure its visible

**Comment by prateekkumaroriginal** [comment]
@VineeTagarwaL-code Video is now available. Already solved in #68

**Comment by VineeTagarwaL-code** [comment]
Okay great merged !
