### ISSUE TITLE
📦 [FEATURE]: Implement view job details overlay like remotejobs.com

### ISSUE THREAD

**Issue by Shubham-Kumar1** [code100x/job-board#70]
<img width="1307" alt="Screenshot 2024-08-07 at 2 06 49 PM" src="https://github.com/user-attachments/assets/09ebf5f5-c41e-4b1e-87a7-3b416986783e">

# Implementing job details overlay; PR coming soon.

**Comment by VineeTagarwaL-code** [comment]
if you can make a exact replica of this, sure work on this

**Comment by Shubham-Kumar1** [comment]
@VineeTagarwaL-code sure, i'll replicate it to the maximum extent possible. thank you!

**Comment by Shubham-Kumar1** [comment]
@VineeTagarwaL-code 
#70 done with the changes. this is the replicated version. i will improve it further if more details can be added to the addJob page.

<img width="1040" alt="Screenshot 2024-08-07 at 11 10 44 PM" src="https://github.com/user-attachments/assets/139f9f4a-68f9-4752-be20-626155a98188">

**Comment by VineeTagarwaL-code** [comment]
looks godd can you do something to match with the themes, also what happens when you click on apply button  ?

**Comment by Shubham-Kumar1** [comment]
sure working on it.

**Comment by VineeTagarwaL-code** [comment]
How will be the next step  when its clicked, dont work before discussing it

**Comment by Shubham-Kumar1** [comment]
@VineeTagarwaL-code on remotejobs.com, when you click "apply," it redirects to an external page where users can apply. should we do the same and redirect to the job's application page.

for that we need an attribute in Prisma for job ["jobURL"] which will link to apply button, so that it will redirect to that page.

**Comment by VineeTagarwaL-code** [comment]
looks good, will be reviewed soon

**Comment by VineeTagarwaL-code** [comment]
#137 as its merged will ask you to fix the conflicts and add this

**Comment by Shubham-Kumar1** [comment]
when #137 will be getting merged?, will update/conflicts after the merge if any.

**Comment by VineeTagarwaL-code** [comment]
New code is up, will highly recommend going over that and opening issues for that
