### ISSUE TITLE
[BUG] Fixed a minor bug for undefined salary range

### ISSUE THREAD

**Issue by ai-is-awesome** [code100x/job-board#77]
A bug in the job.ts getJobs function is causing no jobs to be displayed when the salRange variable is undefined. We need to handle the undefined salRange variable to ensure the evaluation is ignored if salRange is undefined.

For example, currently, page.tsx at /jobs is fetching jobs using:

`const response = await getJobs({});`

This is resulting in no jobs being displayed on the main page.

**Comment by VineeTagarwaL-code** [comment]
Closing this isssue and PR, create a fresh issue that explains the issue very well with proper video reference and explanation with steps on how to reproduce this
