### ISSUE TITLE
[Feature]  to add Dark mode toggle globally 

### ISSUE THREAD

**Issue by GUNGODD** [code100x/job-board#82]
Title: Add Dark Mode Toggle for Shadcn UI Components

Description:

This pull request introduces a dark mode toggle button that effectively switches themes for components built with Shadcn UI. However, it currently does not apply the dark mode styling to other components or elements within the application.

Changes Made:

    Added a dark mode toggle button in the UI.
    Implemented functionality to switch themes for Shadcn UI components.
    Updated tailwind.config.js to ensure proper dark mode support.

Known Issues:

    Dark mode toggle only affects Shadcn UI components.
    Other components and static elements do not change their theme with the toggle.

Next Steps:

    Investigate and apply necessary styles or configurations to extend dark mode support to all components and static elements.
    Seek feedback on current implementation and suggestions for broader applicability.

How to Test:

    Pull the branch and run the application locally.
    Use the toggle button to switch between light and dark modes.
    Verify that Shadcn UI components respond to theme changes.

Feedback Requested:

    Suggestions for extending dark mode functionality to non-Shadcn UI components.
    Code review for the current implementation.

Screenshots:
![Wed Aug  7 07:15:37 PM IST 2024](https://github.com/user-attachments/assets/ed01874d-fa68-4c18-a625-e1f218ebe13c)
![Wed Aug  7 07:15:41 PM IST 2024](https://github.com/user-attachments/assets/d9ecb95b-4e41-4716-b666-b969f3c2b6f8)

**Comment by GUNGODD** [comment]
you can see the dark mode toggle color in  both pictures..

**Comment by Parikshit2001** [comment]
Did you make pull request for this?

**Comment by VineeTagarwaL-code** [comment]
No need for that as of now, will surely add it as an adhoc thing after main features are completed
