### ISSUE TITLE
Dockerfile not working 

### ISSUE THREAD

**Issue by Sahil-Gulihar** [code100x/job-board#83]
![image](https://github.com/user-attachments/assets/c2befaef-de7f-4175-b067-18efcb78c662)
Dockerfile not working 
(I use Arch btw)

**Comment by GUNGODD** [comment]
i think you should update your npm version

**Comment by VineeTagarwaL-code** [comment]
Will you work on this @Sahil-Gulihar 
?

**Comment by iharsh02** [comment]
![image](https://github.com/user-attachments/assets/356a081b-2020-4d1c-9b26-0842e6090d28)
![image](https://github.com/user-attachments/assets/252c8401-ce81-4756-bc51-b2ae89e50b04)

working fine for me

**Comment by pawann-2000** [comment]
Dockerization has been completed in #27

**Comment by Sahil-Gulihar** [comment]
> i think you should update your npm version i use arch with i3 btw :)

Seems like I now need to install git, github, npm, prisma, perl, erlang, haskel, java, wsl, rust, golang and many other things to run a dockerfile now..

Thanks so much for your Guidance

**Comment by listenhereyoulil-NlGGA** [comment]
> i think you should update your npm version i use arch with i3 btw :)

[https://www.youtube.com/watch?v=ubIn3Qf1dtU](url)

**Comment by listenhereyoulil-NlGGA** [comment]
check this out @GUNGODD .
i use bun btw

**Comment by listenhereyoulil-NlGGA** [comment]
@GUNGODD leave the earf
