### ISSUE TITLE
Job Filter Makes multiple backend requests

### ISSUE THREAD

**Issue by Sahil-Gulihar** [code100x/job-board#85]
Job filter on sidebar makes 20+ requests/second which pushes the load to server

![Screenshot-07_08_2024-08-13-37](https://github.com/user-attachments/assets/ff654d85-5233-46de-a1f1-6222d99d24c9)

I feel like we shall add debouncing to the Filter calls

**Comment by Sahil-Gulihar** [comment]
#86

**Comment by Sahil-Gulihar** [comment]
#86

**Comment by VineeTagarwaL-code** [comment]
Issue is not detailed, need proper issue, reproduce step and then ask to get assigned for it
