### ISSUE TITLE
📦 [FEATURE] : Admin Job Management in Job Board Application

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/job-board#87]
### Description
We are introducing new features to the Job Board web application to enhance admin functionality. The following features will be added:

- **Edit Existing Jobs**: Admins will have the ability to modify job postings.
- **View Existing Jobs**: Admins will be able to see a list of all current job postings.
- **Delete Jobs**: Admins will have the capability to remove job postings.

### Requirements
- Ensure that admins can perform CRUD (Create, Read, Update, Delete) operations on job postings.
- Update the database schema if necessary to accommodate new functionalities.
- Implement necessary API endpoints for these actions.
- Ensure proper authentication and authorization to restrict access to these features.

### Acceptance Criteria
- Admins should be able to view, edit, and delete job postings from the admin panel.
- The UI should be user-friendly and consistent with the existing design.
- All changes should be reflected in the database and visible in the application.

**Comment by kushwahramkumar2003** [comment]
@VineeTagarwaL-code I want to work on it, please assign to me

**Comment by VineeTagarwaL-code** [comment]
without assigning, please dont open the PR i will close this, reopen with proper issue, after discussion i will assign you and then you can open the pr thank you !
