### ISSUE TITLE
📦 [FEATURE] : Implement Pagination in Jobs Page

### ISSUE THREAD

**Issue by kushwahramkumar2003** [code100x/job-board#89]
# Feature Request: Implement Pagination in Jobs Page

## Current Situation

Currently, all the jobs are displayed on a single page, which makes it difficult to navigate and find specific jobs. The absence of pagination leads to a poor user experience, especially when there are many job listings.

## Feature Description

We propose to implement a pagination feature in the jobs page. This will allow users to navigate through job listings more easily by splitting them into multiple pages.

## Video Demonstration

Below is a video demonstrating the current situation where all jobs are visible on a single page without the option to paginate:

https://github.com/user-attachments/assets/8057c18c-5c3a-40c2-ae28-be1517985b7e

## Benefits

- **Improved User Experience**: Users will be able to navigate through job listings more efficiently.
- **Performance**: Loading a limited number of jobs per page will enhance the performance of the page.
- **Scalability**: As the number of job listings grows, pagination will help in managing the display of jobs effectively.

I would like to work on implementing this feature. Please let me know if it's okay to proceed with this task.

Thank you!

**Comment by shrirajpawar4** [comment]
i can pick this up and work on it

**Comment by Debajit-Paul** [comment]
@kushwahramkumar2003 @VineeTagarwaL-code can I raise a PR for the changes I already made?

![Screenshot 2024-08-08 031422](https://github.com/user-attachments/assets/77ae9551-e0a6-44b2-9b48-5f4669349f8a)

**Comment by kushwahramkumar2003** [comment]
I have already done, i will open pr once @VineeTagarwaL-code approve this issue

**Comment by kushwahramkumar2003** [comment]
> @kushwahramkumar2003 @VineeTagarwaL-code can I raise a PR for the changes I already made?
> 
> ![Screenshot 2024-08-08 031422](https://private-user-images.githubusercontent.com/62774980/356001326-77ae9551-e0a6-44b2-9b48-5f4669349f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTMzMDIsIm5iZiI6MTcyMzA5MzAwMiwicGF0aCI6Ii82Mjc3NDk4MC8zNTYwMDEzMjYtNzdhZTk1NTEtZTBhNi00NGIyLTliNDgtNWY0NjY5MzQ5ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTIzYWYxYjZhMWIzODRiYjdhM2E2N2E4ZmY3OGYwMDBlNDgxYjRiOTU4NzhkMDYxNDY1ZDZhZWY5NjRmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GkUpPiODwoa4AXlZkDVLRPMMWedtdXjLMMDPBoiUpU)

Have you added Pagination in this page ?

**Comment by kushwahramkumar2003** [comment]
> @kushwahramkumar2003 @VineeTagarwaL-code can I raise a PR for the changes I already made?
> 
> ![Screenshot 2024-08-08 031422](https://private-user-images.githubusercontent.com/62774980/356001326-77ae9551-e0a6-44b2-9b48-5f4669349f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTMzMDIsIm5iZiI6MTcyMzA5MzAwMiwicGF0aCI6Ii82Mjc3NDk4MC8zNTYwMDEzMjYtNzdhZTk1NTEtZTBhNi00NGIyLTliNDgtNWY0NjY5MzQ5ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0NTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTIzYWYxYjZhMWIzODRiYjdhM2E2N2E4ZmY3OGYwMDBlNDgxYjRiOTU4NzhkMDYxNDY1ZDZhZWY5NjRmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4GkUpPiODwoa4AXlZkDVLRPMMWedtdXjLMMDPBoiUpU)

I have already opened pr like this for manage Jobs [https://github.com/code100x/job-board/pull/88](url)

**Comment by VineeTagarwaL-code** [comment]
I will write a proper doc on how to actually open issue and wait for me to look over it discuss and then assign, working on that before hand will be a waste most of the time ... i will open a fresh issue, discuss over it and then only you guys open the PR to it
