### ISSUE TITLE
📦[Fix]: Elements getting out of border in Job Filter

### ISSUE THREAD

**Issue by anurrags** [code100x/job-board#90]
<img width="229" alt="Screenshot 2024-08-07 at 22 11 11" src="https://github.com/user-attachments/assets/9a5fc86a-f55e-4aa2-acce-dca22fef49b3">

Choose currency and Job Location are out of the Job Filter element border.

**Comment by DevHrithik** [comment]
I fixed this issue @VineeTagarwaL-code can i make a pull request!?

**Comment by VineeTagarwaL-code** [comment]
@DevHrithik is already assigned for the same duplicate issues https://github.com/code100x/job-board/issues/95
