### ISSUE TITLE
⭐ [IMPROVEMENT] : Landing Page Design upgraded

### ISSUE THREAD

**Issue by AxBwal** [code100x/job-board#92]
Landing Page Design upgraded along with Footer issue Solved @VineeTagarwaL-code 

Uploading 2024-08-07 23-00-51.mp4…

**Comment by AxBwal** [comment]
https://drive.google.com/file/d/1-9u9f21kRt0CsnWe7fLL3g5rjZXQCMk_/view?usp=sharing

**Comment by VineeTagarwaL-code** [comment]
This is issue page no for pasting video link to possible solution, pleas open a pr only if you are assigned
