### ISSUE TITLE
[IMPROVEMENT] Select Div out of the sidebar , size is hardcoded

### ISSUE THREAD

**Issue by justanuragmaurya** [code100x/job-board#95]
The size of select in in side bar where we chose the inr/usd and remote/onsite is not properly sized , it is outside of the sidebar
<img width="1822" alt="Screenshot 2024-08-08 at 12 00 33 AM" src="https://github.com/user-attachments/assets/7bca3966-31c9-4b1a-9c61-8d41cee5a6d7">

**Comment by DevHrithik** [comment]
@VineeTagarwaL-code i fixed the issue can i make a PR!?

**Comment by VineeTagarwaL-code** [comment]
@DevHrithik asked first so assigning this to DevHrithik

**Comment by VineeTagarwaL-code** [comment]
@justanuragmaurya no need for closing it, hrithik is assigned
