### ISSUE TITLE
[FEATURE]:Create Job Details Page with Specific ID

### ISSUE THREAD

**Issue by vibhaw1904** [code100x/job-board#96]
Description:
We need to implement a Job Details page that dynamically displays job information based on a specific job ID. This page should fetch job data from the server using the provided job ID and display the relevant details such as job title, company name, salary, location, and job description. Additionally, the page should include an "Apply Now" button for users to apply for the job.

Tasks:
Create Dynamic Route:

Fetch Job Data:

Implement server-side data fetching to retrieve job details based on the job ID from the URL parameters.
Use the Prisma client to query the job details from the database.
Design Job Details Page:

Display job information including job title, company name, salary, currency, location, and description.
Style the page using Tailwind CSS 
Add "Apply Now" Button:

Include an "Apply Now" button that allows users to apply for the job.
The button should be prominently displayed and styled appropriately.

**Comment by Divyanshu11011** [comment]
hey @vibhaw1904 can you please assign this issue to me !?

**Comment by vibhaw1904** [comment]
hi @Divyanshu11011  already done ,you can pick other issue or create one and then start working on that

**Comment by VineeTagarwaL-code** [comment]
Without assigning, if you start working on it will be waste of time tbh

**Comment by VineeTagarwaL-code** [comment]
Similar Issue is already opened closing both the PR and issue for now thanks

**Comment by vibhaw1904** [comment]
Bro @VineeTagarwaL-code 
We discussed the JobDetails page for specific job IDs when I made the PR for the JobDetails overlay. I actually created the issue for the JobDetails page and have also made a PR for it. You can check it out!

**Comment by VineeTagarwaL-code** [comment]
Before opening a new issue, please ensure that there are no duplicate issues already present. If you have a better suggestion or alternative, feel free to contribute it under the discussions section of the existing issue.

**Comment by vibhaw1904** [comment]
there  is no PR for job details page as of yesterday  so I made one, atleast see  what i implemented  before closing any issue
